### ISSUE TITLE
Submit button issue

### ISSUE THREAD

**Issue by raxan** [mervick/emojionearea#10]
Hi,
When I click the submit button, if emojionearea is open then first of all occur event to close emoji, and submit form is not executed. I need to click one second time on submit button.
There is a way to prevent this?
Thanks

**Comment by joelcuevas** [comment]
Same here...

I think it would be great if the emojis could be displayed in a dropdown or popup that doesn't change the position of other elements in the page.

**Comment by mervick** [comment]
Fixed in [v2.1.0](https://github.com/mervick/emojionearea/releases/tag/v2.1.0). Now dropdown panel with the emojis has an absolute position and doesn't change the position of other elements.

**Comment by mervick** [comment]
Please, check this.

**Comment by raxan** [comment]
Hi,
I just make a test and work fine, but not in all case.
For example I have autoHideFilters enabled 
and when click submit, the first event that occured
is to hide filters.
If autoHideFilters is disabled, then seem work fine.
But is better to have always hidden also filters.

Now I also notice a new issues after upgrade
caused by position:absolute.

Before the textarea expand and submit button moved
after the tabs. Now tabs overlap the submit button,
so users should first of all close the tabs by click on filters,
and then click to submit.

I try to change template as below:

```js
template: "<tabs/><filters/><editor/>",
```
But this make tabs overlap on filters.

It's very well designed your emoji picker, 
but should be more intrusively.

For example check this one method:
http://one-signal.github.io/emoji-picker/
Your plugin seem more stable than that,
but you should consider to make an
option to setup single icon on top right of
textarea, which open a dropdown menu.

So this is closed and opened very quickly.

Check also this: https://github.com/tommoor/emojione-picker

I hope you can make this improvement.

Thank You!
