### ISSUE TITLE
Combine some options?

### ISSUE THREAD

**Issue by Vuurvlieg** [mervick/emojionearea#102]
First thanks for the plugin, amazing!

So I want to combine some settings. First of all I want to use the latest EmojiOne (v2.2.7), using the latest version of EmojioneArea (v3.16), use local PNG images instead of using CDN and at last the result should be using tabs like [this](http://www.jqueryscript.net/demo/WYSIWYG-Emoji-Converter-Picker-Plugin-For-jQuery-EmojiOne-Area/)

Is this possible to combine, if so do you have an example?

**Comment by mervick** [comment]
You can add any supported emojione version and emojionearea will use what version,
for use use local PNG you need to set `emojione.imagePathPNG`
