### ISSUE TITLE
How to destory emojionearea on some click event?

### ISSUE THREAD

**Issue by ahexdev1** [mervick/emojionearea#104]
I have initialized emojionearea with angualrjs, now i was seeking for some destroy function, so that we can remove emojionearea when not required.

**Comment by luizcarraro** [comment]
I am also in need of something like that to use with an EmberJS component. +1

**Comment by Blkc** [comment]
Wouldn't $.remove() would do for destroying the component?

**Comment by mervick** [comment]
@Blkc unfortunately no

**Comment by mervick** [comment]
duplicate of https://github.com/mervick/emojionearea/issues/104
