### ISSUE TITLE
URL Should be an Anchor

### ISSUE THREAD

**Issue by GaneshKandu** [mervick/emojionearea#107]
URL Should be an Anchor
When i writing an URL it Should be converted to an Anchor
 
Result
![screenshot-localhost-2017-02-13-22-53-00](https://cloud.githubusercontent.com/assets/12833130/22894528/4996df3a-f23f-11e6-84f1-786e820d7a8a.png)

Expecting
![screenshot-localhost-2017-02-13-23-00-45](https://cloud.githubusercontent.com/assets/12833130/22894846/79f8c570-f240-11e6-8a97-004d9d24bb97.png)

is there any option in ?
```js
var default_options  = {};
```

**Comment by HaiDangVo** [comment]
as my searching till now it is not possible, i must to detech an url and parse it to html a tag my self on keyup. Any suggess here?

**Comment by GaneshKandu** [comment]
Hi @HaiDangVo 
May This Help
[https://regex101.com/r/jO8bC4/23](https://regex101.com/r/jO8bC4/23)
[http://jsperf.com/javascript-replace-all/8](http://jsperf.com/javascript-replace-all/8)
