### ISSUE TITLE
Is it possible only to show emoji-pictures?

### ISSUE THREAD

**Issue by akudryav** [mervick/emojionearea#109]
Is it possible only to show emoji pictures instead of html-emoji-codes in a read only div, not making it editable?
I mean I have a chat, text area with emojionearea and I'd like to show the same emojis in chat history after message sending.

**Comment by Sergeniy** [comment]
+1

**Comment by Marreck** [comment]
The trick I used was (simplified): 

First get the text that was typed from the emojionarea in the keypress event:

```
var el = $("selector").emojioneArea();
el[0].emojioneArea.on("keypress", function (editor, event) {
 if(event.which != 13) return;

 // On enter keypress get the text from the input
 var msg = $("<div/>").html(this.getText()).text();
});
```

Then store this somewhere in a database or something. When you want to display this in a div there is no need to decode or extract the emoticons. EmojioneArea can do that for you. Just paste the text you stored it into the input and read the html.

```
// Set the text in the input
el[0].emojioneArea.setText(msg);

// Read the html
var html = el[0].emojioneArea.editor.html();

// Clear the input again
el[0].emojioneArea.setText('');

```

**Comment by mervick** [comment]
ref https://github.com/mervick/emojionearea/issues/18
