### ISSUE TITLE
Uncaught TypeError: myHandle.setText is not a function

### ISSUE THREAD

**Issue by dinhchuong7913** [mervick/emojionearea#111]
Hi 
var myHandle = $(".emojionearea").emojioneArea({});
myHandle.setText("<b data='1'>" + item.data('name') +"</b>");
I can not set text and get error
Uncaught TypeError: myHandle.setText is not a function

**Comment by Iworb** [comment]
I've got the same error. Does anyone found solution?

**Comment by mervick** [comment]
For getting handle use `$obj.data('emojioneArea');`

```js
var myHandle = $(".emojionearea").emojioneArea({}).data('emojioneArea');
myHandle.setText("" + item.data('name') +"");
```
