### ISSUE TITLE
Not Work with Vue Js Using Npm Package 

### ISSUE THREAD

**Issue by njhalaRhudara** [mervick/emojionearea#114]
When vue js directive bind el then element is hide

**Comment by dmecke** [comment]
Here is a demo how the emojionearea "steals" the binding from vuejs: https://jsbin.com/yajuwayuda/edit?html,js,output

**Comment by dmecke** [comment]
The workaround I am using now is to create a `syncMessage` method on my vue instance / component:
```
syncMessage() {
    this.message = $('.emojionearea-editor').html();
}
```
This method is triggered by the following emojioneArea-events:

- keyup (when the user types text)
- paste (when the user pastes text or emoji
- emojibtn_click (when the user uses the emojione-area panel

**Comment by seredot** [comment]
@dmecke how did you make it work? Can you copy the code here?

**Comment by zllovesuki** [comment]
@seredot here you go. I put this inside a method so I can call it on `mounted` (vuejs 2.x)

```javascript
var self = this;

$('#emoji-box').emojioneArea({
    pickerPosition: "left",
    tonesStyle: "bullet",
    autocomplete: false
})

this.emojioneArea = $('#emoji-box')[0].emojioneArea

this.emojioneArea.on('keyup paste emojibtn.click', function() {
    self.message = self.emojioneArea.getText()
})
```
