### ISSUE TITLE
keypress not working

### ISSUE THREAD

**Issue by arth1992** [mervick/emojionearea#119]
I found an issue with "keypress" event.  I am using latest version of this. 
My syntax is 
` sm[0].emojioneArea.on("keyup",eventHandler1);` 
 and  
```
var eventHandler1 = function(button, event) {
    console.log('event2');
     return false;
  };
```
as same as shown in docs. Keyup event is working fine but the keypress is not working properly.

**Comment by mervick** [comment]
duplicate of https://github.com/mervick/emojionearea/issues/30
