### ISSUE TITLE
On focus on textarea close filters and tabs

### ISSUE THREAD

**Issue by raxan** [mervick/emojionearea#12]
hi,
I use autoHideFilters and I would like that on focus textarea the filters and tabs is closed.
I suppose to use event on focus, but not sure how to hide them.

``` js
            events: {

                focus: function (editor, event) {
                  // Hide filters and tabs
                }
            }
```

**Comment by osamaaamer95** [comment]
Has this been implemented? Or is there a workaround to achieve this functionality?

**Comment by mervick** [comment]
deprecated
