### ISSUE TITLE
Instant Replace Text Smiley

### ISSUE THREAD

**Issue by divdax** [mervick/emojionearea#123]
Hey!

It is possible to instantly replace text smilies e.g. ```:)```, ```;)```, ```:p``` to emoji icon while typing like facebook does?

**Comment by mervick** [comment]
Hi,
Probably it possible, but for that need to review emojionearea code and add additional optioins/code

**Comment by mike3run** [comment]
with some `string.replace` and a regex possibly on the `keyup` event

**Comment by mervick** [comment]
Duplicate of https://github.com/mervick/emojionearea/issues/61
