### ISSUE TITLE
Compatibility with emojione v3

### ISSUE THREAD

**Issue by driptaroop** [mervick/emojionearea#124]
Since I got confused by versioning of emojione and emojionearea, is emojionearea v3 compatible with emojione v3? Asking because I'm getting all kinds of weird errors when I try to use them both.

[This is my repo link for reference](https://github.com/driptaroop/papri_chat).

**Comment by mervick** [comment]
Emojionearea v3 not supports emojione v3 yet

**Comment by sergkush** [comment]
@driptaroop I can send you my updated version of emojionearea with full support of emojione v3. how to contact you?

**Comment by mervick** [comment]
@sergkush you can open new pull request with your version of emojionearea

**Comment by joelcuevas** [comment]
@sergkush do you need a hand with this? I would love to see v3 support!

**Comment by mervick** [comment]
Added support emojione v3
