### ISSUE TITLE
Standalone Picker with a Custom Element

### ISSUE THREAD

**Issue by hwding** [mervick/emojionearea#125]
Using version 2 and I want to bind the picker onto my custom button, but the `$("#standalone").emojioneArea({standalone: true});` cracked my element and replaced it to its own style.

**Comment by mervick** [comment]
You can duplicate styles of your button to emojionearea button in custom css, 
i think it would be a faster way to handle this

**Comment by hwding** [comment]
@mervick OK, thanks, I'll try this.
