### ISSUE TITLE
use custom emojis as svg or font family?

### ISSUE THREAD

**Issue by mike3run** [mervick/emojionearea#126]
I was wondering if something like that is achievable, i would like to be able to change colors of the emojis and all of the font.

**Comment by mervick** [comment]
You can change the font by changing css
> i would like to be able to change colors of the emojis 

not sure what you mean.. plugin uses [emojione](https://github.com/Ranks/emojione) images from cdn

**Comment by mike3run** [comment]
well like flat emojis not colored ones, so an emoji of a single color  that i can change the colors with css. or make the emojis look something completely different you know... because designers 😛

**Comment by carpii** [comment]
You could get a Premium license from EmojiOne which lets you download their Emoji's in SVG format

From there you could use CSS to style the various SVG elements

But the idea of EmojiOne is to make Emojis consistent across all platforms. If you really need to do this, probably EmojiOne (and EmojiOneArea) is not the solution for you

**Comment by anamauad** [comment]
@mike3run If you really need different emojis, you can build your own emoji library replacing all emojione  images, and setup emojione to load the images from your image library. Mind that you'll get stuck to a emojione version, or you'll need to create your image for every new emoji image added to emojione.

**Comment by mike3run** [comment]
hey guys in this case I ended up using some custom made svg emojis but not with this library or any library i did a custom one for the ocassion, but I really appreciated reading some of the source code from here to learn how you guys dealt with the hell that his `contenteditable` haha
