### ISSUE TITLE
Parse initial and injected text

### ISSUE THREAD

**Issue by MerlinBB** [mervick/emojionearea#13]
Hey, thanks for a great plugin, I have a small feature request!

When initialising the plugin, it would be useful if the existing text was parsed and converted to emoji images.
```
<textarea>My existing text :smile:</textarea>
```

In a similar manner, it would also be useful if the ```setText``` method parsed input for emojis too.
```
.setText("My updated text :smile:")
```

**Comment by mervick** [comment]
Hi, It's works already, just set `shortnames` options to `true`, see example https://jsfiddle.net/oo7Ltvdw/2/

**Comment by MerlinBB** [comment]
Ahhh cool, my apologies and thank you again!

**Comment by marnusv** [comment]
Hi @mervick I have comments in a unsorted list, how can I convert the unicode emoji to emoji images but no enable the full functionality of the area plugin? Thanks in advance. 
![image](https://user-images.githubusercontent.com/24201598/139621043-05d21a90-9453-4a37-9676-6b8f7daef5c4.png)
![image](https://user-images.githubusercontent.com/24201598/139621216-f211c987-b143-476a-a52a-c039d5f5839b.png)
