### ISSUE TITLE
html from text replace

### ISSUE THREAD

**Issue by javansolo** [mervick/emojionearea#135]
Failing to replace entity:
```
&#10;    \n
&#60;    <
&#62;    >
&#09;    \t
```
for example:
`<textarea id="text" name="text">hi!&#10;&#60;b&#62;ali&#60;/b&#62;</textarea>`

**Comment by mervick** [comment]
Good catch!

**Comment by javansolo** [comment]
Time to fix this bug?

**Comment by carpii** [comment]
@javansolo @mervick could you explain this bug further please? I need to know the impact of it, and possibly fix it myself, thanks

**Comment by mervick** [comment]
@carpii use this for fix:
```js
$(".selector").emojioneArea();
var text = $(".selector").eq(0).data("emojioneArea").getText().replace(/&#10;/g, '\n').replace(/&#60;/g, '<').replace(/&#62;/g, '>').replace(/&#09;/g, '\t');
console.log(text);
```

**Comment by carpii** [comment]
@mervick - Thanks. I understand the original problem now.

**Comment by viperaykiri** [comment]
Hello, you know that in applications such as facebook, twitter, whatsapp, users write some expressions quickly and manually. As in the following examples;

**Expression:** ":)", ":-)", ":-D", ":-d", "(:", ":-o", ":-O", ":-(", ":("

**I want to be:** ":grinning:", ":grinning:", ":smiley:", ":smile:", ":grinning:", ":hushed:", ":hushed:", ":disappointed:", ":disappointed:"

How do I change the above examples?

**Comment by carpii** [comment]
@viperaykiri your suggestion does not belong on this ticket, but its duplicate of #61 anyway
