### ISSUE TITLE
Display just emoji image

### ISSUE THREAD

**Issue by waqas1987** [mervick/emojionearea#136]
I have div 

```
<div class="chatingBox">
:wink:
</div>

<script type="text/javascript">
$(document).ready(function() {
	$(".chatingBox").emojioneArea({});

});
</script>
```

but function display emoji in textarea and show add emoji option so, how just display image of emoji and disable edit emoji option?

**Comment by GaneshKandu** [comment]
i am also looking for same

**Comment by carpii** [comment]
Have you tried removing the contenteditable attribute from the emojionearea?

**Comment by GaneshKandu** [comment]
yes not works at all

**Comment by lasdeparq** [comment]
If you just need convert some shortnames into emoji images, you don't need emojionearea. You just import emojione.js lib and call the function emojione.shortnameToImage(":shortname:").
Emojionearea is a **emojione editor**, if you do not want a editor just use the lib emojione.

**Comment by mervick** [comment]
Converting emojione :
+ shortnames to images: https://demos.emojione.com/latest/jsshortnametoimage.html
+ unicode to images: https://demos.emojione.com/latest/jstoimage.html
+ php: https://github.com/mervick/emojionearea/issues/62#issuecomment-255026504
