### ISSUE TITLE
Is there an option to display shortnames in the emojioneArea?

### ISSUE THREAD

**Issue by Blkc** [mervick/emojionearea#137]
As starter, thanks for the library! As above in the title, how can I display :smile: as `:smile:` inside the emojioneArea instead of it being an image?

**Comment by mervick** [comment]
shortname: true

**Comment by Blkc** [comment]
Sorry, just a bit of clarification, but isn't that option just change it from unicode to shortname but both options still show the :smile: such as your fiddle https://jsfiddle.net/1v03Lqnu/71/ ? I want it to actually write `:smile:` inside the contenteditable div after selecting the emoji because I want to get the caret position for something else.

**Comment by mervick** [comment]
when you write in https://jsfiddle.net/1v03Lqnu/71/ it will opens dropdown menu with emojis in where you can select whatever you want

**Comment by mervick** [comment]
Sorry, i don't get you.
> As starter, thanks for the library! As above in the title, how can I display :smile: as :smile: inside the emojioneArea instead of it being an image?

Yo can't do it

**Comment by mervick** [comment]
But for what you need it?

**Comment by Blkc** [comment]
![screenshot from 2017-05-30 16-13-23](https://cloud.githubusercontent.com/assets/7827466/26603007/5308a9d8-4553-11e7-9a16-22e538b6e788.png) so after selecting the emoji from the dropdown, I can't let the text leave as is?

**Comment by mervick** [comment]
not, you can't do it without changing the code of plugin

**Comment by Blkc** [comment]
Can you point me to around where I need to change it?

**Comment by mervick** [comment]
if you need it just for saving, you can use option `saveEmojisAs: 'shortname'`, so it will be replaced to shortname in source

**Comment by Blkc** [comment]
I need to pop another dropdown containing some username for mentioning with @ and replace at the right location. Calculating caret position in contentEditable div with image tags is not as easy as I thought.

**Comment by mervick** [comment]
I am understanding you, but if you replace smileys with text it still be not some simple.
Emojionearea already use dropdown plugin, you can add some code to add your functionality

**Comment by Blkc** [comment]
ok I see thanks for your suggestion.

**Comment by mervick** [comment]
wait, I am creating some example code for you

**Comment by mervick** [comment]
there is working example: https://jsfiddle.net/1v03Lqnu/426/
with cachged lines (1046-1070), also remove code after line 1347

**Comment by Blkc** [comment]
Oh perfect! Thanks a lot!

**Comment by mervick** [comment]
Better solution here https://github.com/mervick/emojionearea/issues/233
