### ISSUE TITLE
update textarea when emoji selected and on keyup

### ISSUE THREAD

**Issue by justice93kg** [mervick/emojionearea#138]
Hello, how can i update textarea when i select emoji and when i type something?

**Comment by Blkc** [comment]
I think you can use the .on() method as specified in the documentation.

**Comment by justice93kg** [comment]
I handled this by this code

`var containerEmojiAreas = $('#container').find(".emojiarea").emojioneArea({
        events: {
          keyup: function(editor, event) {
          	// catches everything but enter
            if (event.which == 13) {
              this.trigger('change');
              editor.closest('form').submit();
              // event.preventDefault();
              // return false;
            }
          },
          emojibtn_click: function (button, event) {
            button.closest('.emojionearea').find('.emojionearea-button-close').click();
          },
        }
    });`
