### ISSUE TITLE
Cannot make it work

### ISSUE THREAD

**Issue by Cotel** [mervick/emojionearea#14]
Hi!

I'm having some problems with my node.js app.
I'm using Socket.io and Express along with other plugins. Every time I load the page where the input I want to transform is I get this error:
`Uncaught TypeError: Cannot read property 'indexOf' of undefined  emojione.js:367`
And looking into the trace there are a lot of calls to emojionearea.js

Any ideas?

Thank you! :)

**Comment by mervick** [comment]
If I understand correctly, you are talking about [Cotel/Chat2c1](https://github.com/Cotel/Chat2c1).
First of all, remove `emojione` resources from yours `link` and `script` tags, it's loads automaticly.
(lines 11, 16 from [index.html](https://github.com/Cotel/Chat2c1/blob/master/public/index.html)).
Replace your code in [main.js](https://github.com/Cotel/Chat2c1/blob/master/public/main.js) (lines 18-22) with this
```js
	window.emojioneVersion = "2.1.4";
	$("#cajaT").emojioneArea();
```

**Comment by Cotel** [comment]
Solved :D Thank you very very much.
