### ISSUE TITLE
Not Paste emoji and Get an empty string

### ISSUE THREAD

**Issue by BehroozBvk** [mervick/emojionearea#140]
Hello
When I click on the emoji, it will put a blank string in the alt="" of the image and the copy is corrupted.

![image](https://user-images.githubusercontent.com/17563730/27387528-37ead6aa-56ae-11e7-846d-ea12e770b71c.png)

**Comment by GaneshKandu** [comment]
make sure you have UTF-8 encoded File and your server response with  Content-Type	
text/html; charset=utf-8
use <meta charset=“utf-8”> in your html

**Comment by BehroozBvk** [comment]
![image](https://user-images.githubusercontent.com/17563730/27485985-4616d962-5844-11e7-8ac1-4ebe217d144e.png)
I checked Okay, but the problem is still over.

**Comment by GaneshKandu** [comment]
not works in editor but works in browser
mine is working
![dfg](https://user-images.githubusercontent.com/12833130/27636673-37c78d7c-5c2a-11e7-90d9-ce61f42523cd.png)
![sdzfc](https://user-images.githubusercontent.com/12833130/27636672-37c7102c-5c2a-11e7-9c5e-48593105c95a.png)

**Comment by mervick** [comment]
Make sure you are using:
+ `utf8` encoding on html 
+ `utfmb4` encoding in sql

**Comment by mervick** [comment]
duplicate https://github.com/mervick/emojionearea/issues/42
