### ISSUE TITLE
Compatibility issue with fancyBox3

### ISSUE THREAD

**Issue by MovehMakeh** [mervick/emojionearea#145]
If the textarea is located inside of a fancyBox pop-up, it makes the textbox un-usable. You need to right click on it for it put the cursor into the textarea or click the emoji button. Backspace is unusable within the textarea and just closes the fancyBox pop-up.

I edited your fiddle to show this issue:
https://jsfiddle.net/1v03Lqnu/

The other thing is that I am wondering if it is possible to limit the number of emojis they can insert. For example, I only want one emoji to be inserted?

Thanks!

**Comment by mervick** [comment]
> The other thing is that I am wondering if it is possible to limit the number of emojis they can insert. For example, I only want one emoji to be inserted?

No, currently where is no such functionality.

> If the textarea is located inside of a fancyBox pop-up, it makes the textbox un-usable. You need to right click on it for it put the cursor into the textarea or click the emoji button. Backspace is unusable within the textarea and just closes the fancyBox pop-up.

Backspace used in fancyBox, you need to disable it in fancyBox, maybe also some stylesheets of fancyBox make effect on emojioneArea.
I don't see this issue on https://jsfiddle.net/1v03Lqnu/, seems like it still mine version

**Comment by MovehMakeh** [comment]
My apologies.

Here is my fiddle: https://jsfiddle.net/o24gyeba/

If I use a normal textarea in fancyBox3, I am able to backspace normally.

**Comment by mervick** [comment]
I fixed your issue with non usable emojionearea, add this lines to your stylesheet:
```css
#posting-form {
    overflow: initial;
}
.emojionearea + button.fancybox-close-small {
  display: none;
}
```

Example: https://jsfiddle.net/o24gyeba/1/

**Comment by MovehMakeh** [comment]
Oh thank you! Sorry for my late response, didn't check since I closed it!
