### ISSUE TITLE
Emoji Parsing !!

### ISSUE THREAD

**Issue by o7abeeb** [mervick/emojionearea#147]
Hello,
I want to ask about displaying the emoji after submitting the form
for example, I have a form uses emoji picker, I need to display the emoji on displaying area
how to do that ??

**Comment by mervick** [comment]
Please use the search, there are many similar questions
https://github.com/mervick/emojionearea/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by o7abeeb** [comment]
@mervick Plz can u mention me on the real solution ??

**Comment by stof** [comment]
Use the [emojione JS library](https://github.com/emojione/emojione) (which is already a dependency of emojionearea btw, loading it from a CDN automatically if you don't already have it)

**Comment by stof** [comment]
be sure to use version 2 of emojione though. Version 3 is not yet supported (see #124)

**Comment by stof** [comment]
Or you can use the `.emojioneAreaText()` function available in emojioneArea too btw
