### ISSUE TITLE
Unable to clear value inside the emojipicker text box

### ISSUE THREAD

**Issue by Arbaz-Hundekar** [mervick/emojionearea#151]
I have two tabbed forms , When i switch tabs i want data to be cleared
But the emoji picker textbox data not getting cleared, Please let me know if there is any thing that can be done. Thanks

**Comment by carpii** [comment]
Why not just clear it manually when you switch tabs?

$("div.emojionearea-editor").text("");

**Comment by mervick** [comment]
use this code for this:
```js
$("div.emojionearea-editor").data("emojioneArea").setText('');
```
