### ISSUE TITLE
Close button is clicked when I click smily icon

### ISSUE THREAD

**Issue by Top-Developer** [mervick/emojionearea#156]
I am using emojionearea with ionic app.
When I click the smily icon that is right side first time, the pane is open.
But the pane is never displayed agin after that.
It seems that close-button is clicked.
But not sure.
emojionearea version : 3.1.8
emojione version : 2.2.7
jquery version : 2.2.4
jquery-textcomplete version : 1.8.4
Thanks! ;)

**Comment by mervick** [comment]
at least you need to provide example of your code https://jsfiddle.net/

**Comment by carpii** [comment]
@mervick May aswell close this ticket ;-)
