### ISSUE TITLE
More textarea on the same page with the same id

### ISSUE THREAD

**Issue by Ande1232** [mervick/emojionearea#157]
Hi, how can I insert more textarea into a page with the same id?
I have done:
```
	<script type="text/javascript">
	  $(document).ready(function() {
	    $("#messaggio").emojioneArea();
	  });
	</script>
```
```
    <textarea id="messaggio" name="messaggio">Text1</textarea>
    <textarea id="messaggio" name="messaggio">Text2</textarea>
```
In doing so, text1 becomes an "emojionearea", while Text2 remains a textarea. how do i make an emojiarea also text2, holding the same id?

![download 1](https://user-images.githubusercontent.com/23746676/30516715-3162549c-9b47-11e7-9556-536ce39a0563.png)

**Comment by Ande1232** [comment]
Fixed using class instead of id.

**Comment by carpii** [comment]
The ID attributes should be unique.
