### ISSUE TITLE
locally hosting jquery-textcomplete.js

### ISSUE THREAD

**Issue by carpii** [mervick/emojionearea#160]
EmojiOneArea seems to load jquery.textcomplete.js from raw.github.com...

https://cdn.rawgit.com/yuku-t/jquery-textcomplete/v1.3.4/dist/jquery.textcomplete.js?_=1507157503282

Is there an option to disable this, and specify its location myself (ie self-host it?)

**Comment by mervick** [comment]
You can disable auto-complete at all by option `autocomplete: false` or you can load `jquery.textcomplete.js` from your local and emojionearea will use it

**Comment by carpii** [comment]
Thankyou
