### ISSUE TITLE
Disable animations/fade in/fade out

### ISSUE THREAD

**Issue by gabrielepx** [mervick/emojionearea#161]
Is there an option or a way (beside edit source) to disable animations, fade in and fade out of the interface, since it does slow down users with less powerful browsers?

**Comment by lasdeparq** [comment]
You just need to override the css as follows:

```
.emojionearea .emojionearea-picker {
        -moz-transition: none;
          -o-transition: color 0 ease-in;  
     -webkit-transition: none;
             transition: none;
}
```

**Comment by jerryliu1997** [comment]
How do we make the animation quicker?

**Comment by carpii** [comment]
The same as the above answer. Override the CSS 

https://github.com/mervick/emojionearea/blob/master/scss/emojionearea.scss
