### ISSUE TITLE
Slow Load due to Text Complete

### ISSUE THREAD

**Issue by graingerkid** [mervick/emojionearea#163]
Hey, 

Love this, so thank you!!

However, I have a problem loading this over multiple forms - 100+ to be more precise.

When reviewing the bottleneck it's coming from the following URL being requested:

https://cdn.rawgit.com/yuku-t/jquery-textcomplete/v1.3.4/dist/jquery.textcomplete.js?_=1507219541073

I've set autocomplete to "off" hoping it would fix this issue but it hasn't.

My page takes around 30 seconds to load - is there a work around or way to stop this from happening?

Thanks, 
Craig

**Comment by graingerkid** [comment]
To be clear, the URL is requested for every textarea I have, so 100+ requests

**Comment by carpii** [comment]
EmojiOneArea loads the cdn script using $.getScript, which by default uses cached: false (meaning it adds the cache busting parameter).

If you look at #160 and #150, you could consider self-hosting the script, but this would still use the cache busting even on your server

You could configure your web server to issue a redirect for these requests, to a simple 'jquery.textcomplete.js', at which point they could be cached by the browser
Alternatively see https://api.jquery.com/jquery.getscript/ for ways you could disable script caching *globally* in your project
Or finally you could just hack the source and pass cached: false

**Comment by graingerkid** [comment]
Tried it as both - still not working:

```
<script type="text/javascript">
$(document).ready(function() {
$(".example1").emojioneArea(
{
pickerPosition: "bottom",
tonesStyle: "bullet",
saveEmojisAs: "shortname",
autocomplete: false
}
);
});
</script>
```

**Comment by graingerkid** [comment]
Did you host it locally? Have much effect?

**Comment by carpii** [comment]
I plan to, but haven't got round to it yet. It wasn't a pressing issue for me, since I just wanted it for reliability reasons rather than performance

**Comment by graingerkid** [comment]
oh ok. Looks like it has worked but still really slow :(

**Comment by carpii** [comment]
Take a look at chromes network tab and see why its so slow?
I think other tickets have pointed out the emojione assets are downloaded each time also (not sure). 

Do you really need all 100 textareas to support emojionearea at initial load time? Maybe you could just use native text area and convert them as and when needed?

**Comment by mervick** [comment]
When you will disable `autocomplete` (`false` not `"off"`), emojionearea will not load `jquery.textcomplete` at all:
```js
$("#emojionearea").emojioneArea({
    autocomplete: false
});
```
Example: https://jsfiddle.net/1v03Lqnu/683/

Even when autocomplete enabled it will be loaded only 1 time.

But creating 100+ emojioneareas can be very slow.

**Comment by carpii** [comment]
Yeah, I see what you mean...

https://jsfiddle.net/1v03Lqnu/688/

This creates 100 emojioneareas dynamically, and it quite slow

It doesn't seem to be related to network activity, just spends 4-5 seconds in scripting
https://i.imgur.com/u44CCSI.png

I don't really know what to suggest, other than showing a loading div while they initiate (or rethink whether you need to display them all at once)

**Comment by mervick** [comment]
> This creates 100 emojioneareas dynamically, and it quite slow

It's not a right way to create 100 contenteditables in one page when it loads.

**Comment by graingerkid** [comment]
What is the right way?

**Comment by mervick** [comment]
Right way is creating plugins dynamically when it's require.
For example you can investigate how facebook input works, there is only one plugin but multiple inputs.

Do you really think users will input 100 fields in same time?

In your case, I would advise something like this:
1) create fake contenteditable `div`s with the same css like for `emojionearea`
2) when user focus on one of the fake `contenteditable` create `emojionearea` and trigger `focus` with `setText()` from fake div
