### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by mervick** [mervick/emojionearea#164]
- [x] improve options section
- [x] improve methods section
- [x] improve events section
- [x] add properties section

**Comment by carpii** [comment]
@mervick Which bits need more documentation?

I see there are a few events which are not in the docs. Is there anything else?

**Comment by mervick** [comment]
Need to review all options and events

**Comment by mervick** [comment]
@carpii here I have site with outdated docs for emojionearea 2.x
* preview http://mervick.github.io/emojionearea/
* repo: https://github.com/mervick/mervick.github.io

If you want you can also update documentation and examples there (or create new pages for 3.x)

**Comment by carpii** [comment]
@mervick Ok I will try to update your doc site with 3.x, and then move 2.x to a subsection (then link both of them from github)

Are many users still using 2.x? 
I wonder if its worth just deprecating the 2.x altogether and then just having a single set of docs on github for 3.x ?

**Comment by mervick** [comment]
> Are many users still using 2.x?

I think they are not many,
You can just move exists docs of 2.x in the separated files, and leave in the primary README only link to the 2.x docs somewhere

**Comment by carpii** [comment]
@mervick Think I've done as much as I can with this, I'm just not familiar enough to document V2.x 

Feel free to close it, or create new tickets with anything specific that needs documenting
