### ISSUE TITLE
Flags and emojione version 3 emojis are not being displayed on the picker

### ISSUE THREAD

**Issue by lasdeparq** [mervick/emojionearea#169]
When using emojione 3, the flags that would appear in version 2 are not being displayed in the picker.

Besides that, the new emojis available on version 3 of emojione are not beeing shown too.

That is happening because the getDefaultOptions was not been updated, because it would broke previous versions of emojionearea.

I think it should have different default options when emojione 3.

**Comment by lasdeparq** [comment]
@johnsenpeder , take a look at [this fiddle](https://jsfiddle.net/lasdeparq/aw0o2thq/4/)

I override all categories. New emojis like zombies and elves appeared.

**Comment by johnsenpeder** [comment]
@mervick @lasdeparq what are your thoughts on how best to do this?
A separate `getDefaultOptions` file for emojione 3 or for example something like
```
filters: {
    default: {
        ...
    },
    emojione3: {
        ...
    }
}
```
or even
```
filters: {
    flags: {
        icon: "flag_gb",
        title: "Flags",
        emoji: {
            default: "...",
            emojione3: "..."
        }
    }
}
```

**Comment by mervick** [comment]
I think will be better to detect emojione version and after that:
```js
if (emojioneVersion == 3) {
    options.filters = {
        // [...]
    }
} else {
    options.filters = {
        // [...]
    }
}

```

**Comment by johnsenpeder** [comment]
@mervick are we talking within the `getDefaultOptions.js` file? :)

**Comment by mervick** [comment]
yeah

**Comment by johnsenpeder** [comment]
I'll take a look at it now :)

**Comment by lasdeparq** [comment]
I'm with @mervick.

For now, it will be better like that:
```js
if (emojioneVersion == 3) {
    options.filters = {
        // [...]
    }
} else {
    options.filters = {
        // [...]
    }
}

```

**Comment by mervick** [comment]
```js
define([
    'jquery',
    'var/emojioneVersion',
],
function($, emojioneVersion) {
    return function () {
        var options = $.fn.emojioneArea && $.fn.emojioneArea.defaults ? $.fn.emojioneArea.defaults : null;

        if (!options) {
            options = {
                attributes: {
                    dir               : "ltr",
                    spellcheck        : false,
                    autocomplete      : "off",
                    autocorrect       : "off",
                    autocapitalize    : "off",
                },
                // other options
            };

            if (emojioneVersion.substr(0, 1) == '3') {
                options.filter = {
                    // filters for emojione v3
                };
            } else {
                options.filter = {
                    // old filters v2 and below
                };
            }
        }

        return options;
    };
});

**Comment by johnsenpeder** [comment]
@mervick what about just using the `emojioneSupportMode` value instead?
```
if (emojioneSupportMode > 4) {
}
```

**Comment by johnsenpeder** [comment]
I'm having an issue where it seems on creation of the emojionearea `emojioneSupportMode` is first 0, but when it's the correct value, the default settings have already been set once and due to `return $.fn.emojioneArea && $.fn.emojioneArea.defaults ? $.fn.emojioneArea.defaults : defaultOptions` it will just use the already set defaults.

Thoughts?

**Comment by mervick** [comment]
I think it's because `getDefaultOptions()` used before `loadEmojione` callbacks, but must be after, to make `emojioneSupportMode` not empty

**Comment by pederjohnsen** [comment]
@mervick forgot to add the "fixes https://github.com/mervick/emojionearea/issues/169" in PR for this one, you'll have to close this manually :slightly_smiling_face:
