### ISSUE TITLE
Won't load. JS Error

### ISSUE THREAD

**Issue by jonathan-austen** [mervick/emojionearea#170]
I've copied your basic setup and nothing works. I keep getting emojioneArea is not a function.

Here's my js call in my cshtml file

 $(document).ready(function () {
        $('#DocText').emojioneArea({
            container: "#container",
            hideSource: false,
            useSprite: false
        });
    });
Here's my HTML

                                    <p>
                                        <textarea onkeyup="IsDocReady()" name="docText" id="DocText" spellcheck="true" data-toggle="popover" data-placement="left" data-trigger="hover"  style="width: 100%; height: 500px">@Model.DocumentText

                                        </textarea>
                                    </p>

And in my _layout file I have this after loading my jQuery files

    <link href="~/Content/emojionearea.min.css" rel="stylesheet" />
    <script src="~/Scripts/emojionearea.js"></script>
    <script src="~/Scripts/emojionearea.min.js"></script>

**Comment by carpii** [comment]
````
href="~/Content/emojionearea.min.css"
````

Can you confirm you are loading all this via an actual web server, and not just as a file from your local drive?

If so, you also need to include the EmojiOne library (and css), not just EmojiOneArea

**Comment by jonathan-austen** [comment]
Is that the emojione.js file?

**Comment by jonathan-austen** [comment]
When I do add that file I get the error JavaScript runtime error: 'define' is undefined. It's in the emojione.js file.

**Comment by carpii** [comment]
Yes, you need to include the Emojione css and js into your html. They are not part of EmojiOneArea

**Comment by carpii** [comment]
You need to create a https://jsfiddle.net/ if you are still having problems. 

Its too difficult to help just by discussing it all in English ;)

**Comment by jonathan-austen** [comment]
Yeah, there's no emojione.css. Just an emojionearea.css. Thanks for trtying.

**Comment by mervick** [comment]
Try this
```html
<html>
<head>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://rawgit.com/mervick/emojionearea/master/dist/emojionearea.js"></script>
    <link rel="stylesheet" type="text/css" href="https://rawgit.com/mervick/emojionearea/master/dist/emojionearea.min.css">
</head>
<body>
    <textarea id="emojionearea">Default :smile:</textarea>
    <script>
        $(document).ready(function() {
            $("#emojionearea").emojioneArea();
    </script>
</body>
</html>
```

**Comment by carpii** [comment]
@mervick  is it safe to host my own version of emoji one (js and css)?

I thought it was necessary, but now I see the library will load its own (maybe if its not already present, like it does with textcomplete). 
I guess I just need to make sure window.emojioneversion matches what Im hosting?

Thanks

**Comment by mervick** [comment]
> Is this not necessary? Is there any benefit to including it manually?

no, not necessary, except if you want load emojione from your host, by default it loads from cdn

**Comment by carpii** [comment]
@mervick thanks. I don't host EmojiOne scripts myself, I just include them explicitly from the official cdn (I guess this is kinda pointless if library pulls them in already).

I will remove them from HEAD and let EmojiOneArea decide where to grab them from, Thanks!
