### ISSUE TITLE
EmojiOne library creates JS error for missing 'includes' method

### ISSUE THREAD

**Issue by carpii** [mervick/emojionearea#172]
I'm using EmojiOneArea 3.x and EmojiOne 3.1.2
EmojiOne library seems to make calls to String.includes (which IE 11 doesnt support), and so it creates a javascript error

Has anyone else had this issue? 
It seems strange nobody has reported it already (and I can only reproduce on Windows 10, IE 11 on BrowserStack, not locally).
I have reported it to EmojiOne, but thought it was also worth asking here

Maybe there is some browser shim I should be using?

Thanks

**Comment by mervick** [comment]
Seems like IE don't support `String.prototype.includes()`
ref https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes

try this polyfill:
```js
if (!String.prototype.includes) {
  String.prototype.includes = function(search, start) {
    'use strict';
    if (typeof start !== 'number') {
      start = 0;
    }
    
    if (start + search.length > this.length) {
      return false;
    } else {
      return this.indexOf(search, start) !== -1;
    }
  };
}
```

**Comment by mervick** [comment]
please make a feedback whether this polyfill helped or not

**Comment by carpii** [comment]
@mervick, thanks I will try the polyfill.

It will be a few days I guess. Even on my local dev environment (Windows 10 and IE 11), I cannot reproduce the problem. 
Only when its live and via BrowserStack :(

**Comment by carpii** [comment]
@mervick Polyfill worked great, thanks. I also contacted EmojiOne to report the issue, but no response

**Comment by MartinSchmid2409** [comment]
This is not fixed by EmojiOne, yet. (At least no fix released.)

**Comment by carpii** [comment]
Looks like the most recent release of EmojiOne is still Jul 2017.

@mervick is it worth me adding the polyfill in EmojiOneArea do you think?
Otherwise everyone has this problem on IE until EmojiOne release a new version

**Comment by mervick** [comment]
@carpii it's a emojione bug, we don't need to fix that

**Comment by gvkweb** [comment]
Thank you @mervick , polyfill working fine to me.  Thank you 😃
