### ISSUE TITLE
SVG icons using sprites

### ISSUE THREAD

**Issue by k-zakhariy** [mervick/emojionearea#19]
How to switch to SVG from PNG icons ? 
I tried :
`emojione.imageType = 'svg';
emojione.sprites = true;
emojione.imagePathSVGSprites = './../assets/sprites/emojione.sprites.svg';`

but it not work

**Comment by mervick** [comment]
Unfortunately, since `v2.1.2` emojione changed CSS background-position from 
percentage to pixel offset due to the poor rendering in the latest release of Chrome.
So now it's no way to use any sprites with scaling.

**Comment by k-zakhariy** [comment]
Thank you for reply
