### ISSUE TITLE
Event Keypress Enter

### ISSUE THREAD

**Issue by thanhansoft** [mervick/emojionearea#193]
Hi Mervick,
before that I use this source code:
```
$('.message-input').on('keypress', function(e) {
if (e.which == 13){//something}
}
```
Now. I using emojionearea for Input. I want to use send message with Enter keyboard
```
$(".message-input").emojioneArea({
				inline: true,
				events: {
					keypress: function (editor, event) {
						console.log(editor);
						console.log(event);
						console.log('event:keypress');
					}
				}
			});
```

Please please

**Comment by mervick** [comment]
This is a known bug,
try to use `keyup` instead

ref https://github.com/mervick/emojionearea/issues/30
