### ISSUE TITLE
How to enable Emojione after append

### ISSUE THREAD

**Issue by thanhansoft** [mervick/emojionearea#195]
Hi Mervick,
I want to use emojione after append html. This is demo please fix me 
https://fiddle.jshell.net/thanhansoft/1oy335n7/

Please please

**Comment by carpii** [comment]
Here you go..

https://fiddle.jshell.net/1oy335n7/1/

**Comment by thanhansoft** [comment]
Hi Carpii,
I have a tag input hidden class talk_id, It is next to class="emoji".
I want to event click get value this hidden.
It not work. Please see https://fiddle.jshell.net/thanhansoft/1oy335n7/2/

`$(".btn-append").click(function(){
	$(".row-append").append('<div><input class="talk_id" type="hidden" vale="123" /><input type="text" class="emoji"/></div>');
  $(".row-append div:last .emoji").emojioneArea({
    pickerPosition: "top",
    tonesStyle: "bullet",
    events: {
						click: function (editor, e) {
								console.log($(this).parent().find('.talk_id'));
						}
					}
  });
});`

**Comment by lasdeparq** [comment]
@thanhansoft, in your case you need something like this:

``` javascript
console.log($(this.editor).parent().parent().find('.talk_id'));
```

`this ` at that context is not the dom element, but the object emojioneArea.

**Comment by carpii** [comment]
https://fiddle.jshell.net/1oy335n7/3/

Also note you misspelt "value" as "vale"
