### ISSUE TITLE
How to setText('') after clicked

### ISSUE THREAD

**Issue by thanhansoft** [mervick/emojionearea#198]
Hi admin,
Please help me setText input emojioneArea is Null '' after getvalue
https://jsfiddle.net/thanhansoft/1oy335n7/4/

This is my code:
`$(document).ready(function() {
$(".btn-click").click(function(){
  alert($(".emoji").val());
  //How to set value input class of emojioneArea
  $(".emoji").val('');
});

	$(".emoji").emojioneArea({
  	pickerPosition: "top",
    tonesStyle: "bullet"
  });
});`

**Comment by mervick** [comment]
You can't set emojionearea value using `val()` you need to use emojionearea functions, like this
```js
$(document).ready(function() {
    $(".btn-click").click(function(){
        alert($(".emoji").data("emojioneArea").getText());
        //How to set value input class of emojioneArea
        $(".emoji").data("emojioneArea").setText("");
    });

    $(".emoji").emojioneArea({
        pickerPosition: "bottom",
        tonesStyle: "bullet",
    });
});
```
example: https://jsfiddle.net/1oy335n7/7/

**Comment by thanhansoft** [comment]
Yes, thanks admin.
I want to get html of input: Like this:  not working
`$(".emoji").data("emojioneArea").html();`
Please please

**Comment by mervick** [comment]
`$(".emoji").data("emojioneArea").editor.html()`

**Comment by thanhansoft** [comment]
Thank you so much, have fun for you
