### ISSUE TITLE
Property 'emojioneArea' does not exist on type 'JQuery'.

### ISSUE THREAD

**Issue by okasha93** [mervick/emojionearea#199]
emojioneArea installed with npm.

**Comment by mervick** [comment]
make sure you are added emojionearea.js into your html

**Comment by okasha93** [comment]
@mervick i have already import it from node modules in my index.ts in my project.

import '../node_modules/emojionearea/dist/emojionearea.js';
import '../node_modules/emojionearea/dist/emojionearea.min.css';
import '../node_modules/emojionearea/dist/emojionearea.min.js';
import '../node_modules/emojionearea/dist/emojionearea.css';

**Comment by lasdeparq** [comment]
@okasha93 , paste some example of your code here.

**Comment by okasha93** [comment]
@lasdeparq I am using emojionearea in my angularJS project using npm package manager and webpack module bundler, so i used to include these files from node_modules folder in my index.ts of my project.

**Comment by carpii** [comment]
@okasha93 Check Chromes network tab to ensure all scripts are loading properly

Also check which line of code is causing the error. It should not be too difficult to debug

**Comment by okasha93** [comment]
@carpii  it's ok now i include all file in my index.html and they appear properly in network tab in chrome. but when i click on emoji icon nothing appears (i mean emoji pictures not displayed !!).

**Comment by lasdeparq** [comment]
Did some error is triggered at the console when you clicked?

**Comment by okasha93** [comment]
@lasdeparq thanks a lot .. yup mainly i have a problem in including js and css files !! for example when i include emojionearea.css it seems ok on network tab in chrome but i can't see file content that extists here : [https://github.com/mervick/emojionearea/blob/master/dist/emojionearea.css]
