### ISSUE TITLE
Hide Button on empty textarea

### ISSUE THREAD

**Issue by Nixen85** [mervick/emojionearea#204]
Hi mervick, 
thank you for the great feature and your support.

In the moment I am trying to recover my old functions, which I used in a chat-like website. The features were
// hide send button when no text in textarea (cf. whatsapp)
// enter key as submit button
// clear textArea after submit
// keep focus in textarea after submit

Unfortunately, I'm struggling to make it run again I would appeciate any hints to refactor the functionality.

**JS:**

```
 $(document).ready(function () {
            $("#chatTextarea").emojioneArea({
                inline: true,
                events: {
                    // Enter key as submit button
                    keyup: function (editor, event) {
                        console.log(editor.text());
                        if (event.which == 13 && $.trim(this.text).length > 0) {
                            // $('#chatTextarea').submit();
                            console.log("submit");
                            event.preventDefault();
                            return false;
                            // clear textArea after submit
                            $('#chatTextarea').data("emojioneArea").setText("");
                            // keep focus on textarea after submit
                            $("#chatTextarea").emojioneArea[0].focus;
                        }
                    }

                }
            });
            // hide send button when no text in textarea
            $("#chatTextarea").emojioneArea.on('focus change mousedown mouseout keyup mouseup', function () {
                if ($.trim(this.text).length > 0)
                    $('#send1').show()
                else
                    $('#send1').hide();
            })
        });
```
 
**HTML**

```
 <div class="chat_footer">
            <textarea class="chatTextarea" id="chatTextarea" name="chatTextarea" type="submit" maxlength="5000" placeholder="Deine Nachricht..."></textarea>
            <button id="send1" alt="Senden" type="button" onclick="myFunction()"><i class="material-icons md-light">send</i></button>
            <div class="chat-tools">
                <span class="micro"><a href="#"><i class="material-icons md-light" style="color: white;">mic</i></a></span>
                <span class="attachment"><a href="#"><i class="material-icons md-light" style="color: white;">attach_file</i></a></span>
                <span class="email"><a href="#"><i class="material-icons md-light" style="color: white;">email</i></a></span>
            </div>
        </div>
```

**Comment by carpii** [comment]
Please create an example at jsfiddle.net

Which features are not working for you? 

There is code in your keyup handler which are unreachable, due to the 'return false' above it

**Comment by Nixen85** [comment]
In the momemt the code does not work at all - I prepared an example https://jsfiddle.net/ko5gbu9d/5/
However, the picker is not shown. I will try to fix this...

In my project the picker at least is working, but all the four functions do not run properly...

**Comment by carpii** [comment]
Try this..  https://jsfiddle.net/ko5gbu9d/10/

- You must include jQuery before 
- Use `.focus()` not `.focus`
- Use `editor.text()` not `this.text`
- Use `$("#chatTextarea").data("emojioneArea").on` not `$("#chatTextarea").emojioneArea.on`

**Comment by Nixen85** [comment]
Thank you for your support. Now it´s working fine. There are just two minor issues remaining:

1. It does not count emojis as text and thus the send button is hidden when an emoji or multiple are sent alone.

2.  I tried to copy and adjust the keyup-event for the mousedown event (clicking on the #send1 button).  This unfortunately did not work out. Do you have some hints,?  I think this has nothing to do with the bug from i.e. #29.  

Here is my updated code: https://jsfiddle.net/ko5gbu9d/11/

Thanks for your help!
