### ISSUE TITLE
Delay when blurring textareas on the demo

### ISSUE THREAD

**Issue by erandros** [mervick/emojionearea#205]
https://jsfiddle.net/1v03Lqnu/  

I have like a half second delay when I unfocus out of every textarea.  
Is there a way to not have this?

Thanks for reading.

**Comment by carpii** [comment]
Using which browser?

Cannot reproduce using Chrome with all extensions disabled.

**Comment by erandros** [comment]
Chrome Version 59.0.3071.115
Ubuntu 16.04.2 LTS  
here's a gif (I click the instant the mouse stops moving on every textarea)
https://imgur.com/a/RseBH

**Comment by carpii** [comment]
I have added debugging info which outputs the focus and blur time for each emojiOneArea

See https://jsfiddle.net/1v03Lqnu/768/

Please recreate your GIF with this jsfiddle (including the console.log output in the recording)

**Comment by erandros** [comment]
Here's my results, now trying on chrome with no extensions on MacBook Pro 2011. My previous machine is from 2012. I still consider them ok enough, but it makes a lot of sense that you're getting less delay.  
https://i.imgur.com/NdoJ1F0.png  
But still, why are these delays happening? What work is being done when you blur a textarea? Is there a way to turn that off or reuse a textarea?

**Comment by carpii** [comment]
> it makes a lot of sense that you're getting less delay.

I'm working on a 2017 iMac, but I'm not sure I am seeing a lower delay than you. 
Based on your output, we are both seeing roughly a 120ms between blurring one emojieoneArea and fully focusing the next (including OSX painting the blue focus rect)

This delay has not been an issue for me if Im honest, although I am now curious as to what's causing it

Below is the performance audit from Chrome
It does confirm the 120ms timeframe, but also suggests the 120ms is split equally in jQuery.trigger() and emojioneArea.trigger()

https://i.imgur.com/Spe9kTk.png

I'm not familiar enough with the codebase to know what might be causing this, but it's possible it could be improved. I'll try to dig into it over the next few days.

> Is there a way to turn that off or reuse a textarea?

Bear in mind though, that when you create an emojioneArea, you are no longer using a native textarea. 
It sets the source input element to display:none, and then appends a set of divs

It cannot ever be as responsive as a native textarea, but thats not to say there isn't also a performance bottleneck in emojioneArea somewhere

**Comment by mervick** [comment]
Caused because of triggering `search.keypress` event after each `focus` and `blur` event

As a quick solution set `search` option to `false`
Example: https://jsfiddle.net/mervick/1v03Lqnu/772/

**Comment by carpii** [comment]
@mervick yup, genius :)

This is a recent change I think.... 
https://github.com/mervick/emojionearea/commit/fe2cc23fc5322523f9e1b46ac31bcfda0477e6b3

**Comment by mervick** [comment]
@carpii no, it's not that place

**Comment by carpii** [comment]
@mervick oh okay :)

**Comment by mervick** [comment]
Fixed in the latest release [v3.2.6](https://github.com/mervick/emojionearea/releases/tag/v3.2.6)
example https://jsfiddle.net/mervick/1v03Lqnu/776/

**Comment by erandros** [comment]
@carpii @mervick Thanks a lot for responding this, cheers.
