### ISSUE TITLE
Fix searchPlaceholder option

### ISSUE THREAD

**Issue by fernang** [mervick/emojionearea#208]
Hello,

Thank you, your plugin is awesome.
Emoji are saved in unicode in my database, so i need to display only emoji which belong  to a specific unicode version in the window.

Maximum version of unicode available need to be 4.1
https://emojipedia.org/unicode-4.1/

Currently your plugin will display "mouse emoji" but browsers will display alt="🐁" if you inspect it.
https://emojipedia.org/mouse/
I saw the function "getSupportMode" in your code but i don't know how to use it.

Another issue : 
I try to change 'searchPlaceholder' but it seems to have no effet. Indeed in emojionearea.js you have the word "SEARCH" used directly (L905) instead of the variable.

Thank you in advance!

**Comment by fernang** [comment]
I'm trying to be more clear. I don't want to display emoji which are display by a square by the browser.
some exemple here : https://emojipedia.org/unicode-6.0/

I can use the option "filters" but it's a huge work to do by hand.
Any idea ?

**Comment by carpii** [comment]
Why not use EmojiOne to add support for older browsers 

It seems strange you want to use EmojiOneArea for editing, but then display them as native platform emoji

**Comment by fernang** [comment]
I want to use this library in my backoffice as an emoji selector helper. 
On frontoffice, the library will not be used and thus the emoji should be natively displayed by the browser.

**Comment by mervick** [comment]
> Currently your plugin will display "mouse emoji" but browsers will display alt=":mouse2:" if you inspect it.

I don't get your problem, It works as expected

> Maximum version of unicode available need to be 4.1

It uses emojione, so probably it's their issue, 

>  in emojionearea.js you have the word "SEARCH" used directly (L905) instead of the variable. 

Thanks for your notice, this will be fixed

**Comment by mervick** [comment]
> I'm trying to be more clear. I don't want to display emoji which are display by a square by the browser.

Please make a screenshot of your squares, i see icons, not  squares

**Comment by mervick** [comment]
You can have this problem when you are not use utf8 encoding of you page
```html
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
```

**Comment by lasdeparq** [comment]
`I can use the option "filters" but it's a huge work to do by hand.`
Unfortunately in your case, I think it is the better way...

Or you could use emojione in your frontoffice too...

**Comment by fernang** [comment]
Thank you for your rapidity and answers.

Indeed your library works perfectly, it display mouse correctly. I figured out it's a browser problem.
Firefox will displayed mouse unicode but chrome will display a square for exemple.
Below screen of chrome vs firefox.
Chrome (v62):
![chrome](https://user-images.githubusercontent.com/1367667/32827586-f9cb665c-c9ec-11e7-9d56-ab9a086fc28d.png)
Firefox (v52.1):
![firefox](https://user-images.githubusercontent.com/1367667/32827692-5288f570-c9ed-11e7-9787-683d061b6d63.png)

You can see in "alt" tag that firefox understand mouse unicode but not chrome.

With your library my users will be authorized to save "mouse" emojti and it's will be transfer and used in front. For the moment i did not use emoji in front so it will display unicode logo.
My customers using chrome (same version as us) will see a square and the others using firefox (same version as us) will see a mouse (same case for opera, safari, ...).

I know we can't really do nothing about it.
Do you think there is a simple way to display in emotjioneare only emotji which availble and supported by chrome and firefox last version.
So the "mouse" will not be available in emojionearea.

Maybe the only solution it's to filters available emotji using a hard coded list.

**Comment by mervick** [comment]
All emojis are valid utf8 symbols and all major browser supports this.

You just do it wrong.

Chrome Version 60.0.3112.90 (Official Build) (64-bit):
![selection_012](https://user-images.githubusercontent.com/2429298/32829591-2da2c64c-c9fb-11e7-998d-1bd53a92dc8b.png)

**Comment by mervick** [comment]
Make sure you have valid charset of your html page

**Comment by fernang** [comment]
We are not speaking about the same mouse emotji. Indeed "mouse-face" works correctly on chrome but not "mouse"
mouse-face : https://emojipedia.org/mouse-face/
mouse : https://emojipedia.org/mouse/

It's not depending on my website, if i take an official page : https://emojipedia.org/unicode-6.0/
In my Chrome Version 62.0.3202.94 (Build officiel) (64 bits) it display square instead of unicode correct logo. 
I want to exclude all of that emotji. It is possible to give a range of available unicode used in of library ?

Thank you again.

**Comment by mervick** [comment]
do you see 3 lines or only 1 ?

**Comment by fernang** [comment]
3, maybe i need to install a specific font in my browser ?

**Comment by mervick** [comment]
And I see it perfect

![screenshot from 2017-11-15 12-00-26](https://user-images.githubusercontent.com/2429298/32830034-9a45e490-c9fc-11e7-8059-8e1c92862aa0.png)

**Comment by mervick** [comment]
It because default font what uses chrome have not full symbols on your system

**Comment by fernang** [comment]
Oh ok :) maybe it's because in work i'm in windows 8 with specific enterprise parameters.
I will try from another computer.
Sorry for the misunderstanding

I keep you in touch !

**Comment by fernang** [comment]
It works on my mobile (android/chrome). I will try to figure out the problem with my chrome entrerprise specific version.

Thank you mervick for your help and explication.

I will follow your commit, waiting for searchPlaceholder  correction.

**Comment by mervick** [comment]
It is not chrome, it's your windows

**Comment by fernang** [comment]
I let open the issue for the searchPlaceholder bug.
