### ISSUE TITLE
Help me Fix Emojionearea when use multi Dialog jquery

### ISSUE THREAD

**Issue by thanhansoft** [mervick/emojionearea#210]
Hi admin Mervick,
I'm using Dialog jquery make box chat, Tag input in dialog using Emojioneare,
But When I open the second dialog, the first dialog is inserted: "DiversityDiversityDiversityDiversityDiversityRecentSmileys "
And it makes the dialogue look messy

Please view my video record my problem and file attached
Video: https://youtu.be/b6GWC7MuB_Y
File: http://www.mediafire.com/file/9b1npjaa77r0kkx/fix_emojiarea_with_dialog.zip

Please help me. I am grateful to you

**Comment by mervick** [comment]
Please create example at https://jsfiddle.net/

**Comment by thanhansoft** [comment]
Hi,
Please check for me https://jsfiddle.net/thanhansoft/pjjjxah0/1/

**Comment by mervick** [comment]
See here my version https://jsfiddle.net/pjjjxah0/2/

**Comment by thanhansoft** [comment]
HI, Thank for so much admin
