### ISSUE TITLE
Div orverride my div

### ISSUE THREAD

**Issue by yasir-rafiq** [mervick/emojionearea#213]
I have this
                      <div class="at-text-area"  contentEditable="true" name="user-message" id="user-message"></div>
when I add
$("#user-message").emojioneArea();
It's override my div and create new div which stop my logic.

for example I am also using $('#user-message').atwho(userTags) on same div which stop working.

**Comment by mervick** [comment]
When you are use
```js
$("#user-message").emojioneArea();
```
it creates new editor, and instead of `$('#user-message').atwho(userTags)` you need to use
```js
$('#user-message').next(".emojionearea").find(".emojionearea-editor").atwho(userTags);
```
But I not sure, what your plugin will works with emojioneArea without conflicts
