### ISSUE TITLE
emojionearea & jquery.mentionsInput

### ISSUE THREAD

**Issue by himadrinath** [mervick/emojionearea#214]
@mervick i tired combine this two together but my every attempt failed.

can you place look into this..........

https://podio.github.io/jquery-mentions-input/

thanks

**Comment by mervick** [comment]
Sorry, but I can't help you,
currently emojioneArea not supports bundled plugins or custom html content except emojis

**Comment by himadrinath** [comment]
Thanks

**Comment by mervick** [comment]
See solution here https://github.com/mervick/emojionearea/issues/233
