### ISSUE TITLE
Set position of icon which open emojis box.

### ISSUE THREAD

**Issue by yasir-rafiq** [mervick/emojionearea#216]
I want to change the icon and position of that icon, can you guide how can I change it?

**Comment by mervick** [comment]
You need to change stylesheets of `.emojionearea-button`
https://github.com/mervick/emojionearea/blob/5971d752df036531b7fa3cb93f7babf66479e0be/scss/emojionearea.scss#L132-L139

**Comment by jicihome** [comment]
Could be nice to just have an option for (right left top bottom position)
