### ISSUE TITLE
Insert unicode in textarea

### ISSUE THREAD

**Issue by Abrahamlet** [mervick/emojionearea#221]
For starters, this is an AMAZING plugin! One of the best out there and worthy of use.

Now, my issue...

I'm currently using EmojioneArea version 2.x as it allows me to show the emoji picker right below the editor box. This plugin creates its own editor for the textarea. That means the textarea, unfortunately, becomes pretty much useless as all typing and emojis are entered via the editor. What I'd like is to have the textarea act as the editor _and_ have EmojioneArea insert unicode whenever someone selects an emoji (instead of the default <img />).

Is this possible with this version of the plugin, or must I use version 3.x to accomplish this?

**Comment by mervick** [comment]
Currently, it's not possible with any version

**Comment by MartinSchmid2409** [comment]
I wish it will be possible to preserve the original textarea in the future.

The fact that the original textarea is replaced by the emojionearea-editor (in a div) means that any spelling check features (e.g. Chrome @Android) do not work. So user´s might be frustrated that this does not work when typing in the editor.

Another solution may be to just replace 
<div class="emojionearea" role="application">
by
<textarea class="emojionearea" role="application">
Wouldn´t that solve the "issue"?

**Comment by mervick** [comment]
@MartinSchmid2409 
1) Actually spellcheck works, and that doesn't related to this issue,
see here https://github.com/mervick/emojionearea#attributes for enable default spellcheck attribute
Example: https://jsfiddle.net/1v03Lqnu/864/

2) textarea doesn't supports images, and I don't think what without images it would be useful for someone else
3) emojionearea 2.x has not been supported for a long time
