### ISSUE TITLE
Handle textarea overflow

### ISSUE THREAD

**Issue by Oranakia** [mervick/emojionearea#224]
Hi, great plugin.
I’m almost done with the implementation but I have one more question.
Is there a proper way to handle the textarea overflow?
Since the selector is inside the input area, setting overflow causes it to display improperly.
![scroll](https://user-images.githubusercontent.com/34228199/34688388-b4af2d3c-f490-11e7-8cde-663a13377d99.png)
https://jsfiddle.net/1v03Lqnu/
Is there a way to scroll the content of the textarea, but leaving the emoji selector as it is (pop up outside the box)?
![scroll2](https://user-images.githubusercontent.com/34228199/34688394-bc81828a-f490-11e7-8c1f-850347f8addd.png)

**Comment by mervick** [comment]
I don't understand you.
I can't reproduce your first image,
and second image I think is valid.
Can you please make some examples?

**Comment by Oranakia** [comment]
Sorry, for the inconvenience, I was placing the “overflow: scroll;” in the container div, causing the pop up to make the scroll appear.
I fixed it by placing overflow in emojionearea-editor.
https://jsfiddle.net/sLe6b4ch/
My mistake. Thanks anyways.
