### ISSUE TITLE
Editing emoji saved as image not rendering the emoji

### ISSUE THREAD

**Issue by anylyne** [mervick/emojionearea#225]
Hello Everyone, 

I started integrating the emojionearea. I can pick Emoji and save them as image; I can present it exactly as I choose previously; But when I try to edit this text that contains my Emoji it is not being presented correctly! Instead it is presenting the html code not rendered. Is there any attribute to render the emoji saved as image?

Thanks in advance!

`$("#direct_transfer_message").emojioneArea({
      pickerPosition: "bottom",
      saveEmojisAs: "image"
    });`

![emojionearea integration](https://user-images.githubusercontent.com/35921/35019081-02d2af40-fb79-11e7-821b-eb70a76c18a6.png)

**Comment by carpii** [comment]
I think saveEmojiAs: "image" is meant for presentation purposes only. It is not meant for you to then load it into an EmojiOneArea and start editing again.

Try using saveEmojiAs: "shortname", then when you need to present it you can use EmojiOne library to translate that into actual emoji images

**Comment by anylyne** [comment]
Thanks @carpii, 
Using this approach that you suggested, the comments#edit was fixed, as bellow:
`target_input.emojioneArea({
      pickerPosition: "bottom",
      saveEmojisAs: "shortname"
    });
  }`
`
$(".comm").each(function() {
      $(this).html(emojione.shortnameToImage($(this).html()));
    });`

However I did a workaround to have my comments#show presenting the same image that I had picked previously.
 
I required 'emojione' and call `p.html(emojione.shortnameToImage(p.html()));` in my comments#show page. The weird thing is the emoji sheet changed. Is there anyway to use the same emojione instance required at emojionearea?

**Comment by mervick** [comment]
Please create example at https://jsfiddle.net/

**Comment by anylyne** [comment]
Hello @mervick, 
Here is the example: https://jsfiddle.net/z587c4vj/21/
Thanks! 
p.s. In my real environment my comments#show is not the same page as comments#new and comments#edit.

**Comment by mervick** [comment]
Ok I see, the point is what you need to change emojione version, there are 2 ways to do this:
1) use older version of emojione (emojionearea uses emojione v 2.1.7 by default)
2) set `window.emojioneVersion` before emojionearea calls (ref https://github.com/mervick/emojionearea#customize-emojione-version)
example
```js
window.emojioneVersion = "3.1.2";
```
And at the end...  I found a bug, looks like emojionearea ignore `window.emojioneVersion`, and I will fix it soon

**Comment by mervick** [comment]
Fixed in [emojionearea@v3.2.8](https://github.com/mervick/emojionearea/releases/tag/v3.2.8)
and added usage of latest emojione v3.1.2 by default in the [emojionearea@v3.3.0](https://github.com/mervick/emojionearea/releases/tag/v3.3.0)

**Comment by anylyne** [comment]
Thanks, @mervick!
Fixed after update versions: 
<img width="984" alt="screen shot 2018-01-18 at 11 42 57 am" src="https://user-images.githubusercontent.com/35921/35074990-c69b73c8-fc44-11e7-9ed2-5404e4b47b7d.png">

**Comment by rajat304** [comment]
Hello,
The issue again reappears in EmojioneArea v3.4.1.
Please check the fiddle: https://jsfiddle.net/rajat_agarwal/z2epynta/2/

Replicate case:
1. select an emoji in emojionearea1.
2. click outside the emojionearea1 textarea.
3. You see emoji convert with img tag.

![edit fiddle - jsfiddle](https://user-images.githubusercontent.com/42024804/53684844-aa87cc00-3d38-11e9-9c09-fc0c0c912e0f.jpg)
