### ISSUE TITLE
Insert data into textarea not working with emojionearea

### ISSUE THREAD

**Issue by graingerkid** [mervick/emojionearea#226]
Hey,
I'm trying to insert text into a textarea with jquery but with emojione it's not working.

Can you tell me what might be preventing this?

My code it here: http://jsfiddle.net/Gcaqe/13/

Thanks

**Comment by mervick** [comment]
Hi,
with emojionearea you can to set value with method
```
$("selector").data("emojioneArea").setText(val)
```
and get value with method 
```
$("selector").data("emojioneArea").getText()
```
ref https://github.com/mervick/emojionearea#methods

The problem is what `jQuery.fn.val()` method don't makes any events,
and event `change` fires only when input is blur,
so it can't be listen in any legal way

**Comment by graingerkid** [comment]
I don't suppose I could trouble you for an example? You've lost me

**Comment by graingerkid** [comment]
I've put a complete example here: https://jsfiddle.net/ukLaz8cm/124/

**Comment by mervick** [comment]
https://jsfiddle.net/ukLaz8cm/127/

**Comment by graingerkid** [comment]
Ah, yea I was way off haha.

Thanks again 👍
