### ISSUE TITLE
Shortname for second and forth instances

### ISSUE THREAD

**Issue by sglazkov** [mervick/emojionearea#227]
Hi,
Thanks for the great plugin but I have one big issue:

I need to add 'shortname' to textareas, it works for main texarea but I have no idea how to get it from second and forth instances. Also 'button' and 'event' parameters don't have methods to get shortname from

Example: https://jsfiddle.net/un9yynme/

Please help!
Thanks!

**Comment by mervick** [comment]
Hi, 
this issue doesn't related to emojionearea,
it's a wrong logic of your code

you are use `textAreasAdded` which has changed when you are use it

```js
var textAreasAdded = 1;

jQuery(document).ready(function () {
    // ...

    $("#clickToAdd").click(function (event) {
        event.preventDefault();
        var textToAppend = "<textarea id='text" + textAreasAdded + "'></textarea>";
        textToAppend += "<textarea id='example" + textAreasAdded + "' style='display:none'></textarea><br/>";
        $("#newtextareas").append(textToAppend);

        var text
        var el2 = $("#example" + textAreasAdded).emojioneArea({
            standalone: true,
            shortnames: true,
            autocomplete: false,
            pickerPosition: "left",
            saveEmojisAs: "shortname",
            events: {
                emojibtn_click: function (button, event) {
                    console.log("emojibtn_click button html: " + JSON.stringify(button.html()));
                    //Need to add 'shortname', but have no idea how to get it from
                    //second and forth instances. Also 'button' and 'event' parameters
                    //don't have methods to get shortname from

                    console.log('textAreasAdded = ' + textAreasAdded); // = 2 !!!!

                    $("#text" + textAreasAdded).append(el2[0].emojioneArea.getText());
                },
            },
        });

        //console.log("Emoji "+textAreasAdded+" area " + (el2 ? console.log(JSON.stringify(el2)) : " data empty"));

        textAreasAdded++; // here textAreasAdded changed
    });
});
```

**Comment by sglazkov** [comment]
Slightly changed. Here is the new version: https://jsfiddle.net/hox9j3ya/
Seems that no method to get 'shortname' code for the second textarea.
For main textarea is OK, but the second - is not.

**Comment by sglazkov** [comment]
Corrected code version: https://jsfiddle.net/Lp55cuck/
Seems that method you proposed that gets 'shortname' for the second textarea is not correct.
For main textarea is OK, but for the second - is not - it just uses the 'shortname' selected in the first one.

**Comment by mervick** [comment]
It's not my code, it's yours.
I just said what it has wrong logic

**Comment by mervick** [comment]
This is my example:
https://jsfiddle.net/Lp55cuck/1/

**Comment by sglazkov** [comment]
Thank you!
