### ISSUE TITLE
I cant add the keyup event for this code. I tried the examples given. https://jsfiddle.net/2s9dhks8/1/

### ISSUE THREAD

**Issue by Alexarvinpillai** [mervick/emojionearea#229]
$('#emojionearea').keypress(
    function(e){
        if (e.keyCode == 13) {
            e.preventDefault();
            var msg = $(this).val();
            var snd ='<audio autoplay=true><source src="../pop.mp3"></audio>'
			$(this).val('');
			if(msg!='')
			//$('<div class="msg_b">'+msg+'</div>').insertBefore('.msg_push');
			$('.msg_body').scrollTop($('.msg_body')[0].scrollHeight);
  
  var uname = form1.uname.value;
  var xmlhttp = new XMLHttpRequest();
  
  xmlhttp.onreadystatechange = function() {
    if(xmlhttp.readyState == 4 && xmlhttp.status == 200) {
      document.getElementById('chatlogs').innerHTML = xmlhttp.responseText;
    }
  }
  xmlhttp.open('GET','insert.php?uname='+uname+'&msg='+msg,true);
  xmlhttp.send();
  $('body').append(snd);
      }
    });

This code work without $("#emojionearea").data("emojioneArea").editor.on("keyup", 

Thank you in advance

**Comment by mervick** [comment]
`$('#emojionearea').keypress` will not work, because `$('#emojionearea')` is a `textarea`,
and emojionearea creates contenteditable `div`, so `keypress` event will fire only on `div` element, not on `textarea` itself.

So, you need to listen `keypress` of `div`, but due to the bug https://github.com/mervick/emojionearea/issues/30,
I suggest to use `keyup` event:
```
$("#emojionearea").emojioneArea({
    events: {
        keyup: function (editor, event) {
            console.log(this.getText());
        }
    }
});
```

**Comment by Alexarvinpillai** [comment]
Hi mervick. I tried using key up. but it doesnt work with the code i attach above. 
     
        $(document).ready(function() {
$("#emojionearea").emojioneArea({
  pickerPosition: "top",
filtersPosition: "bottom",
  tones: false,
 autocomplete: false,
 inline: true,
 hidePickerOnBlur: false,
 events: {
        keyup: function (editor, event) {
            console.log(this.getText());
        }
    }
 }); 
});

**Comment by mervick** [comment]
Here your jsfiddle with fixed your issue
https://jsfiddle.net/2s9dhks8/11/

**Comment by mervick** [comment]
And here your latest code, which works great too
https://jsfiddle.net/2s9dhks8/13/

**Comment by Alexarvinpillai** [comment]
You are amazing. Perfect. Thanks alot. God bless you

**Comment by persiasama** [comment]
please why the original textarea is not updated in realtime when keypress on the wysiwg?
it's only updated when i leave the field.
Even if I stop writting nothing

**Comment by mervick** [comment]
@persiasama 
try this:

```js
$("#txtMessage").emojioneArea({
    events: {
      keypress: function (editor, event) {
        this.source.val(this.getText());
        //console.log(this.source.val());
      }
    }
});
```

Example: https://jsfiddle.net/1v03Lqnu/1397/
