### ISSUE TITLE
disable

### ISSUE THREAD

**Issue by Frimko** [mervick/emojionearea#23]
Will there be an option to disable ?
`if (!emojione || getSupportMode(detectVersion()) < 2) {
        $.getScript(cdn_base + emojioneVersion + "/lib/js/emojione.min.js", function () {
            emojione = window.emojione;
            emojioneVersion = detectVersion();
            emojioneSupportMode = getSupportMode(emojioneVersion);
            cdn_base += emojioneVersion + "/assets";
            var sprite = cdn_base +"/sprites/emojione.sprites.css";
            if (document.createStyleSheet) {
                document.createStyleSheet(sprite);
            } else {
                $('<link/>', {rel: 'stylesheet', href: sprite}).appendTo('head');
            }
            while (readyCallbacks.length) {
                readyCallbacks.shift().call();
            }
        });
    } else {
        emojioneVersion = detectVersion();
        emojioneSupportMode = getSupportMode(emojioneVersion);
        cdn_base += emojioneVersion + "/assets";
    }`
and add path to their own?

**Comment by mervick** [comment]
Yes, of course I'll do it in the next version

**Comment by OwlGreenApple** [comment]
Hi tried using disable and got some error says
