### ISSUE TITLE
Is there any settings to present unicode emoji on emojioneArea picker? 

### ISSUE THREAD

**Issue by anylyne** [mervick/emojionearea#230]
In my application, I have a restriction to save emoji as unicode. However the emojionearea picker present it as image. Is there anyway to set the picker component to present unicode?

<img width="124" alt="screen shot 2018-01-30 at 4 34 48 pm" src="https://user-images.githubusercontent.com/35921/35549932-0a428292-05dc-11e8-9b01-34c176a262d9.png">

Or any other solution for this missing emoji.

**Comment by rockers007** [comment]
I Have also same issue

**Comment by carpii** [comment]
If you only want to use unicode, there is no need to use EmojiOne, or EmojioneArea

Alternatively use EmojiOne library when you want to display them

**Comment by mervick** [comment]
I tried to do that, but emojionearea require emojione in any case,
so I can't remove emojione dependency and it will loads anyway,
so it has no sense to do this.
I close this issue
