### ISSUE TITLE
emojioneArea init break some emojies when call it on input with data

### ISSUE THREAD

**Issue by notgosu** [mervick/emojionearea#232]
Hi!

Thank you for your great work!

Here is my problem - when i call `$('.emoji-subject').emojioneArea()` on input with some data(text+emojies), it's break some of emojies code, for example 'Man pilot', 'Cloud Snow', 'Cloud Lightning', and therefore it's showing like unicode symbols, without transformation to images.

For example:
1) Init emojioneArea on my empty input
2) Fill it with some content http://joxi.ru/eAO6140hxXXEX2
3) Check it's content lenght via this code` (new TextEncoder('utf-8').encode($('.emoji-subject').val())).length`, it's return 60
4) Save this to db(utf8mb4_unicode_ci)
5) View record, check length before init emojioneArea, it's returns 60, everything is OK
6) init emojioneArea and check length again - it's returns 51! So, it's break some parts of unicode. But it's still looks ok http://joxi.ru/12MxjQ7hMzzKLm
7) Save data to db, view it again, init emojioneArea and there is no emojies - http://joxi.ru/n2Y05zRuozz5lm String length again returns 51

So, my question is - how can i fix it, because i need all of emojies to work fine.

Thanks!

**Comment by mervick** [comment]
Can you please create example at https://jsfiddle.net/?
Also check you document encoding, maybe it caused because of wrong charset

**Comment by notgosu** [comment]
sure https://jsfiddle.net/85xr14e9/ 

i'm using utf-8 html encoding.

**Comment by mervick** [comment]
Hmm.. I have no idea what is wrong.
Here 2 similar icons https://jsfiddle.net/85xr14e9/1/
first one is your, and second from picker,
looks like when you save it some function on your backend sanitize the icons 
```
md5(🌨) - d68542489b4694806e01330ef4b602d77a71cad2c72b8a601b0e85b4b511b8fc
md5(🌧️) - bf06fd12ec88a9c9dcb48fc1f96e24cefb85a7f01257a0995f08302a2d9f932b
```

**Comment by mervick** [comment]
For avoid this you can save emojis in shortnames
```js
        $('.emoji-subject').emojioneArea({
            saveEmojisAs: "shortname",
            shortnames: true,
        });
```
https://jsfiddle.net/85xr14e9/2/

**Comment by notgosu** [comment]
Ok, i've made a screencast http://take.ms/989bg, maybe it help with problem detection.

I've checked the backend, there is no additional sanitize, so I think maybe this bug related to some version of jQuery or another scripts? 

Have a look and tell me please what you think about. 

P.S. The way to store emojies in text format may be a solution, but i need to make sure there is no bug with emojioneArea plugin when saving unicode :)

**Comment by mervick** [comment]
@notgosu 
Try to select not length but md5 hash, and you will see.
I am use EmojioneArea in the project for years and it works great

**Comment by carpii** [comment]
@notgosu I would hexdump the string at each stage..

before encoding
after encoding
after you retrieve etc

Untested hexdump routine here https://gist.github.com/igorgatis/d294fe714a4f523ac3a3

**Comment by notgosu** [comment]
Oh man, i'm dunno what's wrong, but whith shortNames this bug also have a place :)

http://take.ms/d62bb

**Comment by notgosu** [comment]
Okay, i'll try a md5 check and post a result here.

**Comment by carpii** [comment]
@notgosu  Check your database library too. It is not enough that the database column is defined to use utf8mb4_unicode_ci

Your actual sql connection also has to be set to use that charset and collation (often by issuing a 'set names utf8mb4' command or whatever mechanism the library recommends

**Comment by notgosu** [comment]
Here is a results with md5. I've used a library for js md5 https://github.com/blueimp/JavaScript-MD5
Bug is still here, hash of string changed **after** emijoneArea is initialized.

Screencast: http://take.ms/QcOc6

@carpii i've use a utf8mb4 for connection, also tested SET NAMES utf8mb4; before saving to DB - the same result. What additional info of my environment is needed?

**Comment by mervick** [comment]
@notgosu 
don't use md5 of input val, it's a completely wrong, because emojionearea can adds `\n\r` symbols, need to get md5 of only utf8 symbols of emoji,
by the way in your last example emoji shows fine

**Comment by notgosu** [comment]
@mervick okay, can you show me the example of 

> get md5 of only utf8 symbols of emoji

> by the way in your last example emoji shows fine
it's shows fine, but save to DB broke emoji and it's looks like http://take.ms/gv0Cx

**Comment by mervick** [comment]
Here you can see right emojis saved in database and all works great
https://socialveo.co/post/789cd9c0-09c6-11e8-be7b-061f7800027c

**Comment by notgosu** [comment]
@mervick with those usual smiles i don't have troubles too:)

Can you try with your environment next steps?
1) Init emojioneArea on textarea
2) select few multi-symbols emoji's, such as 'Man Vampire', 'Man Pilot', 'white sun rain cloud' for example
3) submit form and save data to db without any sanitize
4) view form with emoji string in textarea from DB and init emojioneArea on textarea
5) save it again to DB
6) view form again and make sure that all emoji's still look like in emojioneArea picker


If everything OK, please, share with me details of your environment(OS, mysql encoding/collations, etc).

Thank you!

**Comment by mervick** [comment]
![peek 2018-02-06 02-08](https://user-images.githubusercontent.com/2429298/35836504-3b44a264-0ae9-11e8-9ab3-02a2c5e9557c.gif)

**Comment by mervick** [comment]
```sh
$ uname -a
Linux izman 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ mysql
 > SHOW VARIABLES LIKE "%version%";
+-------------------------+-------------------------+
| Variable_name           | Value                   |
+-------------------------+-------------------------+
| innodb_version          | 5.7.17                  |
| protocol_version        | 10                      |
| slave_type_conversions  |                         |
| tls_version             | TLSv1,TLSv1.1           |
| version                 | 5.7.17-0ubuntu0.16.04.2 |
| version_comment         | (Ubuntu)                |
| version_compile_machine | x86_64                  |
| version_compile_os      | Linux                   |
+-------------------------+-------------------------+
 > show create table table_name;
+-------+--------------------------------------------------------------------------------------------------
| Table | Create Table
+-------+--------------------------------------------------------------------------------------------------
| table_name  | CREATE TABLE `table_name` (
   ...
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 |
+-------+--------------------------------------------------------------------------------------------------
 >
```
From php used connection charset `utf8mb4`
