### ISSUE TITLE
Search+Tones block doesn't hide

### ISSUE THREAD

**Issue by gulakov-designer** [mervick/emojionearea#234]
Hi!
I wanted to hide block that is goes between filters and recent but after setting options, this block is still visible and have no content. Here is my code.
```
$("#add-post-area").emojioneArea({
        pickerPosition: "right",
        search: false,
        tones: false
});
```
Result: 
![screen shot 2018-02-05 at 15 59 02](https://user-images.githubusercontent.com/16059574/35808240-d49e17b2-0a8d-11e8-951f-e05c2b9878cb.png)

**Comment by gulakov-designer** [comment]
I checked that even deleting SEARCH and TONES blocks from DOM tree does not move content, because it's stick to bottom and have it's height. Seems like there is no ready solution in current version...

**Comment by mervick** [comment]
@gulakov-designer you can use css for avoid this behavior

**Comment by gulakov-designer** [comment]
That's exactly what I did 😆 
It's just perfectionist inside me, that is whispering: "It must work automatically..."
But aside jokes, maybe it's a good idea to not displaying this blocks as they are not in need and change the height accordingly? Seems to be not a big deal.

**Comment by mervick** [comment]
I agree with you, this should be fixed
