### ISSUE TITLE
get value from text area

### ISSUE THREAD

**Issue by yasir-rafiq** [mervick/emojionearea#236]
I have created multiple text area with and initialize emojionearea with dynamic Id's.
How can  I get text from textarea with ID?

**Comment by mervick** [comment]
```js
$("#id").data("emojioneArea").getText();
```

**Comment by yasir-rafiq** [comment]
It's throw error 
Uncaught TypeError: Cannot read property 'getText' of undefined
    at <anonymous>:1:45
Please have a look.

**Comment by yasir-rafiq** [comment]
There is another way if you can guide how can I get instance on created emojioneArea?

**Comment by mervick** [comment]
https://jsfiddle.net/1v03Lqnu/906/

**Comment by mervick** [comment]
it can throws error in case if emnojionearea not yet initialized

**Comment by yasir-rafiq** [comment]
Yeah that works but when I need to access values of the element that has emojionearea initialized on it, it doesn't work. Please keep in mind that the element has been created dynamically on click event on the DOM and then emojionearea instance is applied on it like:

`$(dynamicID).emojioneArea();`

The textarea and the emojionearea instance, both are created and instantiated dynamically.

**Comment by yasir-rafiq** [comment]
This all works fine on another element on the same page that has **NOT** been created dynamically, maybe this has something to do with dynamically created elements ?

**Comment by mervick** [comment]
No, seems you just try to use wrong id.
Please create your example here https://jsfiddle.net/1v03Lqnu/906/

**Comment by yasir-rafiq** [comment]
https://jsfiddle.net/1v03Lqnu/906/

Please have look and check get text function I'm not able to get text.

**Comment by mervick** [comment]
You don't saved it

**Comment by yasir-rafiq** [comment]
https://jsfiddle.net/1v03Lqnu/908/

**Comment by mervick** [comment]
```js
$("#emojionearea12").emojioneArea();
  var id = ".span4 .emojionearea-editor";
  $(id).attr('id','emojiarea'); // what is that ????? why?
};
```

**Comment by mervick** [comment]
https://jsfiddle.net/1v03Lqnu/909/

**Comment by yasir-rafiq** [comment]
I've to do some other operation in iner ID that why I created it.
BTW I got your point its fine.
