### ISSUE TITLE
It is possible to create the disabled option?

### ISSUE THREAD

**Issue by imatsu** [mervick/emojionearea#237]
Best regards.

This is the best emoji library, congratulations.

But it is posible to create disabled option?,

**Comment by carpii** [comment]
you mean so it doesn't respond to text entry, and the emoji picker doesnt appear?

**Comment by imatsu** [comment]
Yes of course, I need prevent to users type text in some moments.

**Comment by mervick** [comment]
You can use html attribute `disabled`
```html
<textarea id="emojionearea1" disabled=disabled></textarea>
```
or use methods `enable()` / `disable()`
```js
$("#emojionearea").data("emojioneArea").enable();
$("#emojionearea").data("emojioneArea").disable();
```
Example: https://jsfiddle.net/1v03Lqnu/903/

**Comment by pkwiatkowski0** [comment]
Unfortunately none of those solutions work for me:
For enable() / disable() I get:

> VM62979:1 Uncaught TypeError: $(...).data(...).disable is not a function
`$("#emojionearea").data("emojioneArea")`
returns a good result

**Comment by mervick** [comment]
@pkwiatkowski0 can you create example at jsfiddle?
My example works  https://jsfiddle.net/1v03Lqnu/905.
And if it does not works for you I suppose you have particular case.

**Comment by pkwiatkowski0** [comment]
On jsfiddle is working like a charm. I think I will need to figure out some workaround for it.
