### ISSUE TITLE
How to use EMOJI ONE AREA for IONIC 2 Applications?

### ISSUE THREAD

**Issue by ShafiqEssani** [mervick/emojionearea#238]
I've installed emoji one area using this command npm install emojionearea@^3.0.0 for my Ionic 2 Application.
How to use this please help?
Thanks

**Comment by carpii** [comment]
EmojioneArea requires JQuery. 
I'm not at all familiar with Ionic, but apparently there is a way to import JQuery into your Ionic app...

https://stackoverflow.com/questions/42305422/using-jquery-with-ionic-2
