### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by gumacuk15** [mervick/emojionearea#239]
Hi!

**I use:**
EmojioneArea v3.3.1
Emojione v2.2.7
Jquery v3.3.1

**If I add this library:**
https://cdnjs.com/libraries/emojione/2.2.7

**Then I get error:**
`emojionearea.js:102 Uncaught TypeError: Cannot read property 'length' of undefined
    at emojionearea.js:102
    at String.replace (<anonymous>)
    at p (emojionearea.js:94)
    at Object.<anonymous> (emojionearea.js:1372)
    at Function.each (jquery-3.3.1.min.js:2)
    at L (emojionearea.js:1372)
    at emojionearea.js:1372
    at Object.success (emojionearea.js:1372)
    at u (jquery-3.3.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.3.1.min.js:2)`

**Else (without Emojione v2.2.7):**
all fine

**Comment by gumacuk15** [comment]
I found that first need to import Emojione v2.2.7 and then EmojioneArea v3.3.1. Works. Conversely do not work.

**Comment by carpii** [comment]
You can omit the EmojiOne library, and EmojiOneArea will load it from the cdn automatically.

You can set window.emojioneVersion as per the docs

**Comment by mervick** [comment]
Please create example at https://jsfiddle.net

**Comment by gumacuk15** [comment]
i cant omit importing Emojione v2.2.7, i get error:

Uncaught ReferenceError: emojione is not defined
    at 2:445

**Comment by gumacuk15** [comment]
window.emojioneVersion

What is this? Emojione or EmojioneArea?

**Comment by mervick** [comment]
Is it working here?
https://jsfiddle.net/mervick/1v03Lqnu/765/

**Comment by muskangupta3** [comment]
Still not working
