### ISSUE TITLE
output emoji codes

### ISSUE THREAD

**Issue by SplayConsulting** [mervick/emojionearea#24]
I am looking for it to output emoji codes :smile: (:shortcut:) I thought that might have been the short names option but when I set that to true, it still outputs unicode.

**Comment by mervick** [comment]
You must use option `saveEmojisAs: "unicode"`,
https://github.com/mervick/emojionearea/blob/v3.0.3/src/var/default_options.js#L22

**Comment by SplayConsulting** [comment]
Perfect, thank you. Great job btw
