### ISSUE TITLE
Accessibility problem with TAB

### ISSUE THREAD

**Issue by hotgeart** [mervick/emojionearea#242]
For accessibility (W3C WAI-ARIA 1.0) reasons, I must be able to browse my web site with the TAB key.

If you take the demo : https://jsfiddle.net/1v03Lqnu/ you can't access to the others inputs. You're blocked in an 'infinite loop'.

There's a way to skip the emoji selector when we press TAB?

**Comment by carpii** [comment]
You can disable shortcut events being attached..

https://jsfiddle.net/1v03Lqnu/922/

**Comment by hotgeart** [comment]
Thx i'll go with this
