### ISSUE TITLE
I don't want to open emoji picker with ":" sign.

### ISSUE THREAD

**Issue by yasir-rafiq** [mervick/emojionearea#243]
Hello, actually I've add emojiareaone in bootstrap uib-dialog, when I type colon sign (:) its open emojis list but its hide behind the dialog. So I think its not good to open that list just user emojis picker.

Pls help,.

**Comment by mervick** [comment]
set `autocomplete` to `false`
```js
$(".emojionearea").emojioneArea({
    autocompleteTones: true
});
```
ref https://github.com/mervick/emojionearea#autocomplete

**Comment by yasir-rafiq** [comment]
thnks
