### ISSUE TITLE
Events for list show and hide

### ISSUE THREAD

**Issue by copperseed** [mervick/emojionearea#244]
It would be great to have events that can be triggered on show and hide of the emoji list.

**Comment by mervick** [comment]
There is already has event when picker show:
event `picker.show`

But there is no event triggered when it hide

**Comment by copperseed** [comment]
I see there is a trigger for `picker.hide` in the code. Any chance that can be used as an event in future? For now, the `picker.show` event works for my needs. Closing.

**Comment by mervick** [comment]
Yeah, looks like `picker.hide` works too

**Comment by mervick** [comment]
https://jsfiddle.net/1v03Lqnu/996/
