### ISSUE TITLE
Choice of emoji with readable input field?

### ISSUE THREAD

**Issue by trDjango** [mervick/emojionearea#245]
Hello mervick;
I just want to define a readable input field, meaning that you can not write in the user input field,   and you can only choose emojis, the following method did not work, what can i do in this regard?Thank you very much for your help.
`<input type="text" id="emoji" "name="emoji" value="Select Emoji" readonly>`

**Comment by mervick** [comment]
You can use standalone mode
https://github.com/mervick/emojionearea#standalone
and update your input when it will be changed

**Comment by trDjango** [comment]
thank you very much  mervick :)
