### ISSUE TITLE
ENTER key

### ISSUE THREAD

**Issue by senadburak** [mervick/emojionearea#247]
Hi,
I am trying to apply the emojionearea to an online chat module. For chat I am using SignalR and chat.js with its own keyup function. In this function we check if the keycode is 13, and if yes, we send the message from the input into the chat area.
The problem is that emojionearea.js replace this code and I am unable to find where this happen.

How can we ignore the emojionearea keyup processing?

Regards, Senad

**Comment by mervick** [comment]
Try to disable `shortcuts` (https://github.com/mervick/emojionearea#shortcuts
Example:
```js
$(".emojionearea").emojioneArea({
    shortcuts: false
});
```

**Comment by y-spreen** [comment]
This does not work for me.

**Comment by mervick** [comment]
https://jsfiddle.net/1v03Lqnu/1858/

**Comment by carpii** [comment]
Try this, I use this in my chat application

$(".emojionearea").emojioneArea({
	events: {
		keyup: function(editor, evt) {
			if (evt.keyCode === scancodes.ENTER)
			{
				/* do your processing here */
				
				/* prevent event from bubbling any further */
				evt.stopPropagation();
			}
		}
	}
});

**Comment by mervick** [comment]
keypress

**Comment by gerar19** [comment]
A mi me funciona así:
`  $(document).ready(function () {
 $("#txtMessage").emojioneArea({
                inline: true,
                pickerPosition: 'top',
                hideSource: true,
                events: {
                    // Enter key as submit button --> working
                    keyup: function (editor, event) {
                        if (event.which == 13 && ($.trim(editor.text()).length > 0 || $.trim(editor.html()).length > 0)) {
                            $('#btnSendMsg').click();
                            event.preventDefault();
                            event.stopPropagation();

                            editor.focus();
                        }
                    }
                }
            });
  });
}`
