### ISSUE TITLE
Hot to change the icon picker?

### ISSUE THREAD

**Issue by vynnus** [mervick/emojionearea#248]
Hi folks,

how do I change the icon picker?
I need to change the grey smiley icon to something else.
In photoshop I edited the sprite.png file located inside the images folder but no success.

**Comment by vynnus** [comment]
I found the answer on google :-)
Use a tool to convert image to data URL such as:

http://dataurl.net/#dataurlmaker

**Comment by mervick** [comment]
Actually you can did this with any known editor
