### ISSUE TITLE
Key up event

### ISSUE THREAD

**Issue by yasir-rafiq** [mervick/emojionearea#250]
Hello, I am calling function when user press enter by using key_up event.
Problem when I have open list for emojis and select emoji using enter same function call as well.

I just want to call function when have focus on main input.

**Comment by mervick** [comment]
You can check whether is picker is opened or not,

ref https://github.com/mervick/emojionearea/issues/244

**Comment by yasir-rafiq** [comment]
I am open another list as well, how can I check that list?

**Comment by mervick** [comment]
Please provide example of your code at https://jsfiddle.net/, then I will show you

**Comment by mervick** [comment]
You can set events for each instance separately

**Comment by yasir-rafiq** [comment]
https://jsfiddle.net/1v03Lqnu/1177/
When emoji picker open then enter keyup also work.

**Comment by yasir-rafiq** [comment]
waiting for your response?

**Comment by mervick** [comment]
Use `keypress` instread of `keyup`,

Example
https://jsfiddle.net/1v03Lqnu/1196/

It's not related to emojionearea, it's default events behavior,
you can't prevent default after `keyup`, because it's already printed

**Comment by yasir-rafiq** [comment]
keypress is not detect enter key code 13.

**Comment by mervick** [comment]
![selection_003](https://user-images.githubusercontent.com/2429298/36959905-3964395e-204d-11e8-9726-d89e29aa85c4.png)

**Comment by yasir-rafiq** [comment]
yes I checked fiddle but it's not work in my app.

**Comment by yasir-rafiq** [comment]
I am using it with angularjs, other keys are working with keypress but enter key is not detect.

**Comment by mervick** [comment]
create example at jsfiddle

**Comment by mervick** [comment]
maybe it related to angularjs?
