### ISSUE TITLE
How to insert symbol in caret position from event?

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [mervick/emojionearea#252]
I need to insert line breaks when Ctrl-Enter pressed. 
getText/setText is not enough to make it - because it does not give me information about caret position.

This is where i am now...
```JS
$( "#textarea" )
    .emojioneArea( {
        container: "#container",
        events: {
            keyup: (editor, event) => {
                if (event.originalEvent.ctrlKey === true && event.originalEvent.code === "Enter") {
                    // insert break line in caret position
                }
            },
        }
    } )
```

**Comment by rafaponieman** [comment]
Trying to accomplish the same thing. In my case, using it for a chat platform... I managed to get enter to send messages, but not ctrl+enter to generate linebreak.

**Comment by mervick** [comment]
```js
$( "#textarea" )
    .emojioneArea( {
        container: "#container",
        events: {
            keyup: (editor, event) => {
                if (event.originalEvent.code === "Enter") {
                    if (event.originalEvent.ctrlKey === true) {
                        // do nothing enter already inserts break line in caret position
                    } else {
                        // enter key without ctrl
                        // insert your code here
                        event.preventDefault(); // ignore line break
                    }
                }
            },
        }
    } )
```

**Comment by rafaponieman** [comment]
Hi @mervick, thank you!

I tried it, but ctrl+enter isn't generating a newline for me. It does nothing. Does it work for you?

**Comment by mervick** [comment]
Yes, you are right browser does not insert new line for ctrl :(
But if you replace `ctrl` with `shift` this code will work.
https://jsfiddle.net/1v03Lqnu/1760/

Seems there is no easy solution for ctrl+enter

refs:
https://google.com/search?q=contenteditable+insert+breakline+on+ctrl+enter
https://stackoverflow.com/questions/6023307/dealing-with-line-breaks-on-contenteditable-div
