### ISSUE TITLE
Want to change the height of the searchbar, editing css doesn't work

### ISSUE THREAD

**Issue by dunky11** [mervick/emojionearea#254]
Hello,

I want to edit the height of the searchbar, because it's buggy on my website, the window is too big.
I linked the .css files in the header.php file in the themes folder of my wordpress installation like that:

<script src="https://cdn.jsdelivr.net/npm/emojione@3.1.2/lib/js/emojione.min.js"></script>
<link rel="stylesheet" href="my_website/wp-content/themes/oceanwp/js/emojionearea-master/dist/emojionearea.css">

Editing the emojinonearea.css doesn't change anything, ive also already tried editing the _variables.scss and deleting my browser- and websitecache.

**Comment by dunky11** [comment]
Found a workaround, i disabled search with: pickerPosition: "right",
jQuery("#example1").emojioneArea({
      pickerPosition: "right",
      search: false,
      tones: false
 });

**Comment by mervick** [comment]
What is means "editing css doesn't work" ?
It's works
