### ISSUE TITLE
Display emoji but i want to store in emoji data-name in to db in angular js 

### ISSUE THREAD

**Issue by gvkweb** [mervick/emojionearea#256]
Hi, 
 Its working fine for me but i want dispaly emoji and store emoji data name : smile :  please give any suggestions 

ex: 
Hi helllo 😄 

Hi hello : smile :

**Comment by mervick** [comment]
If you want to store emojis in DB as `:shortnames:` you need to set option [`shortnames`][1] to `true`

```js
$(".emojionearea").emojioneArea({
    shortnames: true
});
```

[1]: https://github.com/mervick/emojionearea#shortnames

**Comment by gvkweb** [comment]
I did this actulay in mysql db inserted ??? marks.  I am trying to insert this actuality 😄 hello 😄  but in my db inserted like this  ??? hello ??? but when i am write data-name it will save fine  i am using php mysql angular js

$("#emojionearea2").emojioneArea({
        shortnames: true,
  	pickerPosition: "bottom",
  	filtersPosition: "top",
         tones: false,
         autocomplete: true,
         inline: true,
        hidePickerOnBlur: false,
      attributes: {
        spellcheck : false,
        autocomplete   : "off",
        id : "post_content"
    },

**Comment by mervick** [comment]
Look also at this option

ref [`saveEmojisAs`][1]

[1]: https://github.com/mervick/emojionearea#saveemojisas

**Comment by mervick** [comment]
```js
$(".emojionearea").emojioneArea({
    shortnames: true,
    saveEmojisAs: "shortname"
});
```

**Comment by mervick** [comment]
> I did this actulay in mysql db inserted ??? marks.

It's because you have a wrong charset in your DB, for mysql full utf8 charset is `utf8mb4`

**Comment by gvkweb** [comment]
Yes 👍  its working thank you 
saveEmojisAs: "shortname"
 its working  Thank you so much and i want disable some emojis activity and symbols i did this 
symbols: false, but it displays all this is the and is how to display it in angular js any method like filters or directives.

**Comment by mervick** [comment]
```js
$("#emojionearea").emojioneArea({
    filters: {
    	symbols: false
    }
  });
```
