### ISSUE TITLE
emoji wrapper z-index

### ISSUE THREAD

**Issue by gvkweb** [mervick/emojionearea#257]
![emoji error](https://user-images.githubusercontent.com/25583811/37453907-2f6c62d6-285f-11e8-9487-8ce2477351c3.PNG)
Hi 
 I want add z-index for emoji wrapper, and  I am trying here line 226 - emojionearea.css  How to solve this

**Comment by mervick** [comment]
Please create example at https://jsfiddle.net with your problem

**Comment by mervick** [comment]
You can take this https://jsfiddle.net/mervick/1v03Lqnu/765/ as start point

**Comment by gvkweb** [comment]
https://jsfiddle.net/2181d4gx/6/ this is fiddle but in this example fine but my application have same input box it hides the wrapper and i have another issue i want use multiple emojioneareas with same class name is it possible

**Comment by mervick** [comment]
How do you think I would help you if all fine in jsfiddle?
Seems you have something wrong in css of your application

**Comment by gvkweb** [comment]
Ok but i want use same emojionearea in multiple times by using same class name and how to emoji pngs from local why becoz some times  offline/internet slow  pngs dont load

**Comment by mervick** [comment]
First you need to set proper paths to emojione before emojioneArea will load, e.g.
```js
emojione.imagePathPNG = '/images/emoji/';
```

Also you need to disable option `useInternalCDN`
```js
$(".emojionearea").emojioneArea({
    useInternalCDN: false
});
```
ref [useInternalCDN][1]

[1]: https://github.com/mervick/emojionearea#useinternalcdn
