### ISSUE TITLE
Run emoji application with same id?

### ISSUE THREAD

**Issue by trDjango** [mervick/emojionearea#261]
I need to run the emoji application with the same id, but emoji in the first form is working while others are not.For example, the emoji application is run with different id on the link: [https://jsfiddle.net/mervick/1v03Lqnu/765/](https://jsfiddle.net/mervick/1v03Lqnu/765/)
what I want to do is:
```
$(document).ready(function() {
	$("#emojionearea1").emojioneArea({
  	pickerPosition: "right",
    tonesStyle: "bullet"
  });
<input type="text" id="emojionearea1" value=":smiley_cat:"/>
<input type="text" id="emojionearea1" value=":smiley_cat:"/>
```
How can i do, do you have an idea? Thank you very much for your help.

**Comment by carpii** [comment]
ids must be unique. Its not valid HTML to have duplicate ids

**Comment by trDjango** [comment]
Hello carpii,
thank you so much for your reply.I guess I ask the wrong way but I found out how it would be.firstly I have to correct the question.
have the same id in the same elements in two separate forms on the same web page, example:
```
<form id='form1' name='form1'>
  <input name='emojionearea1' id='id="emojionearea1"'>
  <input name='name2' id='name2'>
</form>

<form id='form2' name='form2'>
  <input name='emojionearea1' id='id="emojionearea1"'>
  <input name='name2' id='name2'>
</form>
```
I found the solution like this:
```
<script type="text/javascript">
	  $(document).ready(function() {
		  $("#form1 input[name=emojionearea1]").emojioneArea({
			  standalone: true,
			  autocomplete: false,
			  shortnames: true,
			  saveEmojisAs: "shortname"
			  });
	  });
  </script>
  
  <script type="text/javascript">
	  $(document).ready(function() {
		  $("#form2 input[name=emojionearea1]").emojioneArea({
			  standalone: true,
			  autocomplete: false,
			  shortnames: true,
			  saveEmojisAs: "shortname"
			  });
	  });
  </script>
```

**Comment by mervick** [comment]
@trDjango 

HTML id attribute must be unique! You can't use 2 the same id in one HTML page.

ref https://developer.mozilla.org/en-US/docs/Web/API/Element/id

> It must be unique in a document, and is often used to retrieve the element using getElementById. Other common usages of id include using the element's ID as a selector when styling the document with CSS.

ref https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#the-id-attribute

> An element's unique identifier can be used for a variety of purposes, most notably as a way to link to specific parts of a document using fragment identifiers, as a way to target an element when scripting, and as a way to style a specific element from CSS.

You can replace `id="emojionearea1"` with `class="emojionearea1"`

**Comment by Emmanuel-Oduro** [comment]
<input  id="emojionearea1">
<input  id="emojionearea1">
<input  id="emojionearea1">
<input  id="emojionearea1">
<input  id="emojionearea1">
<input  id="emojionearea1">
<input  id="emojionearea1">

How do I apply emoji to all the fields when page loads?

**_Thank you in advance._**

**Comment by Emmanuel-Oduro** [comment]
Hi guys I've done it.
**_thanks tho_**
