### ISSUE TITLE
Next line, <div>,<bt> missing 

### ISSUE THREAD

**Issue by gvkweb** [mervick/emojionearea#262]
I am save emojiarea data into db but in this case div or new line missing for example
  EX: I am entered two line of content it shows perfectly in editor
       hi this is krishna 😄  
      <div></div>
       hello this is krishna 😁 

but in db save  in single line 
     hi this is krishna 😄  hello this is krishna 😁 
     
how to save two lines or with <div>

**Comment by mervick** [comment]
EmojioneArea does not saves `<div>` or `<br/>` it replaces them with `\n` (new-line),

for convert new lines to `<br/>` you can use `php` function [nl2br](http://php.net/manual/en/function.nl2br.php)
example:
```php
echo nl2br($contentFromDb);
```
