### ISSUE TITLE
Shortname errors for some emojis 

### ISSUE THREAD

**Issue by gvkweb** [mervick/emojionearea#263]
Hi @mervick  
   I got one issue some emojis not convert into shortnames like keyboard  

⌨ : computer : : calling :
how to fix it i want to save all  are in short names

**Comment by mervick** [comment]
it's working
https://jsfiddle.net/1v03Lqnu/1516/

**Comment by gvkweb** [comment]
![emojis](https://user-images.githubusercontent.com/25583811/38130967-baeba8de-3422-11e8-94f3-2fd41706bea0.PNG)
 
In above image some converted fine but some not converted once kindly check it 
shortnames: true,
saveEmojisAs:'shortname',
pickerPosition: "bottom",
filtersPosition: "top",
tones: false,
 autocomplete: false,

https://jsfiddle.net/1v03Lqnu/1524/

**Comment by mervick** [comment]
It's depends of your browser and does nothing with emojionarea, your browser automatically replace it with images in console, but in browser it's ok

**Comment by gvkweb** [comment]
Console convert images its ok but in above image see id #emojiarea2 with display none values its some converted into short names and some converted into icons  and mysql database allows some icons but few icons save as ?????. How it solved please kindly give suggestions. This is the my options   to save shortnames

shortnames: true,
saveEmojisAs:'shortname',


Its working fine but only few emojis converted into small black and white icons.

**Comment by mervick** [comment]
Full description:
- which icons does not converted
- create jsfiddle example that fully shows error in html

Without this I will not help you

**Comment by gvkweb** [comment]
Hi @mervick  this is the jsfiddle once check it 

https://jsfiddle.net/1v03Lqnu/1540/

Please excuse me i am asking same issue no of times 🙏

**Comment by mervick** [comment]
Looks like emojione bug coming from v3,
in v2.1.4 works great

https://jsfiddle.net/1v03Lqnu/1545/

**Comment by gvkweb** [comment]
if i am set version 
 window.emojioneVersion = '2.1.4';
some emojis missed how to display all latest  emojis

**Comment by mervick** [comment]
You can't show latest icons in the old version

**Comment by mervick** [comment]
It's workaroud for the quick fix shortname issue,
but the best way is to fix it in emojione itself

**Comment by mervick** [comment]
Please open issue here https://github.com/emojione/emojione/issues/new
