### ISSUE TITLE
Caret positioning off on Firefox

### ISSUE THREAD

**Issue by rafaponieman** [mervick/emojionearea#269]
Before typing in the editor, caret positioning seems off on Firefox browser (at least version 59 on Linux). Once you start typing, it goes to the right position. Screenshots attached from the JSFiddle demo.

![selection_291](https://user-images.githubusercontent.com/757742/38784208-137eeb40-40e5-11e8-8617-3434c307e1e3.png)
![selection_292](https://user-images.githubusercontent.com/757742/38784209-1551228a-40e5-11e8-976f-9663552d3ab7.png)

Thank you, the editor is great!

**Comment by mervick** [comment]
Duplicate of #86

**Comment by mervick** [comment]
![38784209-1551228a-40e5-11e8-976f-9663552d3ab7](https://user-images.githubusercontent.com/2429298/38784421-475a6798-411a-11e8-8533-ebde790f9f7c.png)

This is firefox behavior for all WYSIWYG editors, it can't be fixed
