### ISSUE TITLE
TypeError: editor.textcomplete is not a function

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [mervick/emojionearea#275]
I get an error: `TypeError: editor.textcomplete is not a function `
at emojionearea.js:1028
```
"dependencies": {
    "emojionearea": "3.1.8",
}
```

```
$( "#id" )
    .emojioneArea( {
        container: "#container",
        shortnames: true,
        hideSource: true,
        autocomplete: true,
    } )
```

**Comment by carpii** [comment]
Cannot reproduce this using 3.1.8

https://jsfiddle.net/1v03Lqnu/1845/

**Comment by Vasiliy-Bondarenko** [comment]
I've found the error. 
My app is scoped inside Vue.js
While textcomplete is loading in global namespace. Correct?
And i don't have jQuery object in the global namespace, and i can not provide it, because i need my app to be isolated (scoped) from global namespace to avoid conflicts. It can reside on external websites, so i can't user global jQuery object. 
Is there a way to inject jQuery into textcomplete?

**Comment by Vasiliy-Bondarenko** [comment]
Thank you. It's working fine.

**Comment by DignaJames** [comment]
I am having the same error due to vendor.bundle.js , 
Please help to resolve
