### ISSUE TITLE
Vue.js & emojionearea

### ISSUE THREAD

**Issue by madi-madi** [mervick/emojionearea#278]
if use emojionearea with  v-model in vue.js  not work 
` <input type="text" placeholder="Write your Message here!"  v-model="msgFrom"  class="form-control"  name="message"   id="standalone"  />`

**Comment by madi-madi** [comment]
https://jsfiddle.net/w7ugm4rr/ 
@lasdeparq

**Comment by mervick** [comment]
Here is working example
https://jsfiddle.net/w7ugm4rr/1/

It's not issue of emojionearea,
it's a issue of vue.js
Read more you can here
https://vuejsdevelopers.com/2017/05/20/vue-js-safely-jquery-plugin/
