### ISSUE TITLE
Using with tinymce editor

### ISSUE THREAD

**Issue by ashish-mittal-quovantis** [mervick/emojionearea#280]
Is there any way to work with emojione area and tinymce editor together ?

**Comment by lasdeparq** [comment]
I suggest you to use standalone version and then treat the click in some emoji in picker to insert in your editor.

**Comment by ashish-mittal-quovantis** [comment]
yes it will work but when i pick any emoji it closes automatically. It is not remain open like without standalone version.

**Comment by lasdeparq** [comment]
@ashish-mittal-quovantis just set  hidePickerOnBlur: false in options

**Comment by ashish-mittal-quovantis** [comment]
Thanks for the help..Its working now.

**Comment by harshal-shirude** [comment]
Is there workaround to make it happen? I investigated it alot and most of the posts says I will have to write entire custom plugin which will work similar way emojiOne-area works.

**Comment by mervick** [comment]
duplicate of https://github.com/mervick/emojionearea/issues/235
