### ISSUE TITLE
I am getting emoji as PNG format i want in UTF8 Format.

### ISSUE THREAD

**Issue by Deepak2311** [mervick/emojionearea#283]
Hey  mervick,
Thanks for your support.
i am trying to implement the emoji in comment section along with text (like facebook) and Chat module.
but i am getting all the emoji as PNG format i want it to UTHey  mervick,
Thanks for your support.
i am trying to implement the emoji in comment section along with text UTF 8 FORMAT so i can send this to backend..

here is my code:

 $("#"+x).emojioneArea({
      autoHideFilters: true,
      saveEmojisAs: true,
      pickerPosition: 'bottom',
      events: {
      keypress: function (editor, event) {
          console.log('event:keypress', event.which); //work
         
          if(event.which == 13){
            console.log(x);
            console.log($('#'+x));
            console.log($('#'+x).val(editor.html()));
          }
       }
     }
    });
 }

**Comment by mervick** [comment]
Please format your code

**Comment by Deepak2311** [comment]
$("#"+x).emojioneArea({
autoHideFilters: true,
saveEmojisAs: true,
pickerPosition: 'bottom',
events: {
keypress: function (editor, event) {
console.log('event:keypress', event.which); //work

if(event.which == 13){
console.log(x);
console.log($('#'+x));
console.log($('#'+x).val(editor.html()));
      }
   }
 }
});
