### ISSUE TITLE
keep caret / focus after setText

### ISSUE THREAD

**Issue by yarekc** [mervick/emojionearea#285]
That's not real an issue: but I really could not find the solution: 
Can I keep the caret on tjhe emoji after I used: 

`emojiArea[0].emojioneArea.setText('hello world);`

It loses the focus and caret is hidden: any idea on how to position the caret at the end ?

regards

**Comment by mervick** [comment]
I think you can find answer on stackoverflow, EmojioneArea does not allow to change cursor position
