### ISSUE TITLE
Can i change the css of textarea

### ISSUE THREAD

**Issue by Deepak2311** [mervick/emojionearea#286]
because you use only one class EMOJIONEAREA...IF i change one place it reflects another place ...
i am using this three places first is comment, post div and another is chat ...so there are different css...
you can see this reference image ... and visit  https://syncyu.com/

![screenshot from 2018-06-06 17-12-31](https://user-images.githubusercontent.com/30972035/41036199-e1d3b88c-69ac-11e8-9147-1690cff7db4f.png)

please update.

**Comment by carpii** [comment]
Apply a css class to your source input, and it will be copied across to the EmojiOneArea

https://jsfiddle.net/1v03Lqnu/1927/

The library does not need updating for this
