### ISSUE TITLE
Angular 6. error TS2339: Property 'emojioneArea' does not exist on type 'JQuery<HTMLElement>'

### ISSUE THREAD

**Issue by isopen** [mervick/emojionearea#288]
@types/emojionearea already exists?
How to start?

**Comment by mervick** [comment]
I think it's a TypeScript stuff and does not related to this project, because EmojioneArea does not use TypeScript at all

**Comment by isopen** [comment]
For example, for jquery, there is an @ types/jquery interface for global connectivity.
True, I understand that `emojionearea` will not work in Angular projects?

**Comment by mervick** [comment]
I mean it's out of this plugin scopes. Does all js plugins have typescript types? 
Even `@types/jquery` is a separated library and does not bundled in the `jquery` itself.
Currently we don't have `@types/emojionearea` library and I think it's not a bug at all.
We don't support TypeScript and you should configure your typescript compiler to not compile emojioneArea.

**Comment by isopen** [comment]
I do not insist on a mistake. This is an extension of the current implementation.
This is not an error, but this leads to the fact that people will not quite correctly connect the library to Angular.
The library itself is very good and it definitely needs typecript support at the interface level.
I agree that `@type/jquery` has many authors.
I'd like to use it in my Angular project. Thanks.

**Comment by andreadompe** [comment]
Follow my steps

**1) Install jQuery. (skip if already installed)**

`npm install jquery --save`

**2) Install types for jQuery.**

`npm install @types/jquery --save`

**3) Import jQuery in app.module.ts.**

`import * as $ from 'jquery';`

4) Into the file where you use $(element).emojioneArea() add this after the imports

`declare var $: any;`

5) Now you can use it

```
$("#emojionearea1").emojioneArea({
      pickerPosition: "left",
      tonesStyle: "bullet"
    });
```

**Comment by wilydamtchou** [comment]
Not working in angular 7

**Comment by mervick** [comment]
@wilydamtchou
EmojioneArea works on every browser, if you don't know how to use it with angular - it does not means "it not working", but it means "you don't know how works angular"
