### ISSUE TITLE
Textarea too long on Firefox

### ISSUE THREAD

**Issue by PremiumScript** [mervick/emojionearea#293]
I'm using Firefox, if you typed a long content (with many new lines) into textarea (by emojione-area), then this textarea expanded for unlimited long, seems your max-height setting does not work; but this works fine on Chrome

Perhaps you should check this

Regards

**Comment by mervick** [comment]
Can you create an example at jsfiddle,
I can't reproduce it, 

works fine both in Crome and Firefox

![selection_129](https://user-images.githubusercontent.com/2429298/42122275-ffaeb07a-7c47-11e8-89fc-215f55961996.png)
