### ISSUE TITLE
Automatically adding div

### ISSUE THREAD

**Issue by Blades-of-Agony** [mervick/emojionearea#294]
While using emojionearea on input text field 

whenever i paste the the text which contain more than one line like
**this is one line
this is second line
this is third line**

It doesn't show everything in one line and automatically add this 
 `<div></div>`

After clicking outside of that input field div automatically get removed
![untitled](https://user-images.githubusercontent.com/28924136/42408201-78830912-81e6-11e8-90be-d362d8d0b0ec.png)

**Comment by mervick** [comment]
It's WYSIWYG editor, it uses `div`, `p`, `br` for line end
