### ISSUE TITLE
Add default value

### ISSUE THREAD

**Issue by orlando6644** [mervick/emojionearea#295]
Hi, Im using this plugin as title input. I want to know if it is posible to add a default value to the input.

**Comment by carpii** [comment]
Add a placeholder attribute to the source input, before converting it to EmojiOneArea

**Comment by mervick** [comment]
Value of textarea or input is default value

**Comment by orlando6644** [comment]
I already add the value to the input and it is removed when the plugin convert it to  EmojiArea.

**Comment by mervick** [comment]
https://jsfiddle.net/mervick/1v03Lqnu/765/

**Comment by orlando6644** [comment]
In my script does'nt work, It should be some jquery or anything else. I will check it! Thank you!

**Comment by orlando6644** [comment]
My problem is with images. i can´t get images as default values. i only get this:
&lt;img alt="????" class="emojioneemoji" src="https://cdn.jsdelivr.net/emojione/assets/3.1/png/32/1f605.png"&gt;

In the input field as default value. 

I tried with shortnames but in others sections i can see the emojis. I don't if i must include any file. What do you say?

**Comment by mervick** [comment]
Create en example with your problem here https://jsfiddle.net

**Comment by orlando6644** [comment]
https://jsfiddle.net/6q0ahryg/1/

When i get the title from database, that's the default value in the input field.

**Comment by mervick** [comment]
You have wrong encoding in your database
look here https://github.com/mervick/emojionearea/issues/42

**Comment by orlando6644** [comment]
It is using the shortnames. I am saving the emojis in the database as images. So they return in a right way. I think the plugin converts "  < to to the htmlentities. so the images turns wrong

**Comment by mervick** [comment]
Just use the right encoding in the database, it must be utf8 or utf8mb for mysql.

**Comment by orlando6644** [comment]
In the database is correctly saved, I can show the emojis in other pages without problem. the only issue is when i initcialize the plugin. It turn like i show you before.

**Comment by mervick** [comment]
> It turn like i show you before.

This code from your example

```html
<div class="row">
  <div class="span12">
    <input type="text" id="emojionearea1" value='Esta es una prueba<img alt=&quot;????&quot; class=&quot;emojioneemoji&quot; src=&quot;https://cdn.jsdelivr.net/emojione/assets/3.1/png/32/1f605.png&quot;><img alt=&quot;????&quot; class=&quot;emojioneemoji&quot; src=&quot;https://cdn.jsdelivr.net/emojione/assets/3.1/png/32/1f92a.png&quot;><img alt=&quot;????&quot; class=&quot;emojioneemoji&quot; src=&quot;https://cdn.jsdelivr.net/emojione/assets/3.1/png/32/1f60c.png&quot;><img alt=&quot;????&quot; class=&quot;emojioneemoji&quot; src=&quot;https://cdn.jsdelivr.net/emojione/assets/3.1/png/32/1f607.png&quot;>'>
  </div>
</div>
```

I see it saved in wrong encoding, because `alt` attribute must contain utf8 emoji but it shows ????,
I am absolutely sure you have the sane at the database
