### ISSUE TITLE
read the clipboard data

### ISSUE THREAD

**Issue by dlrudwns135** [mervick/emojionearea#299]
i want to paste clipboard data in chrome.
but i can't access clipboard.
i refer this url [JavaScript get clipboard data on paste event (Cross browser)](https://stackoverflow.com/questions/2176861/javascript-get-clipboard-data-on-paste-event-cross-browser)
but event has not data about clipboard

**Comment by mervick** [comment]
You can't do it, even with simple input or textarea

**Comment by mervick** [comment]
Use `.on('paste')` event, ref https://github.com/mervick/emojionearea#methods

```js
  var el = $("selector").emojioneArea();
  el[0].emojioneArea.on("paste", function(content, event) {
    console.log(content);
  });
```

**Comment by mervick** [comment]
or 
```js
$("selector").emojioneArea({
  events: {
    paste: function(editor, text, html) {
      console.log(text);
    });
  }
})

```

**Comment by dlrudwns135** [comment]
thanks.
It seems that it did not work properly because of the variable.
i use just editor and event as variable.
In my case, It did not work that way.
