### ISSUE TITLE
EmojioneArea in html tabs problem

### ISSUE THREAD

**Issue by efido** [mervick/emojionearea#300]
Hi there! 
I have created some tabs in html with <textarea> input and i was set TRUE the hidesource in emojionearea.js  but when i switch my tabs the emojione editor is dissapear and i don't know why.. 

see my jsfiddle script : 
 https://jsfiddle.net/ukLaz8cm/963/

**Comment by carpii** [comment]
This isnt an EmojiOneArea issue.

Just debug the show/hide code you've written

**Comment by efido** [comment]
Can u help me please? I'm not that good with javascript, thank you

**Comment by mervick** [comment]
By default emojionearea uses shortcuts and `tab` uses for open/close picker.
For disable this behavior set `shortcuts` to `false`
https://github.com/mervick/emojionearea#shortcuts
