### ISSUE TITLE
Error with emojis text in URL 

### ISSUE THREAD

**Issue by ManuelVK** [mervick/emojionearea#304]
When I put a url that contains: li :, the flag of Lithuania appears to me.
Is there any way that when I paste a URL it shows me: li: and not the Lithuanian flag?
![captura de pantalla 2018-09-03 a las 11 29 54](https://user-images.githubusercontent.com/23051941/44979205-bdc60480-af6c-11e8-86ce-c928fe97e4b5.png)

Thanks!!!!!

**Comment by mervick** [comment]
```js
$(".emojionearea").emojioneArea({
    shortnames: false
});
```
