### ISSUE TITLE
initializing this with the emojionearea initialized input element not working fine

### ISSUE THREAD

**Issue by mrshiva009** [mervick/emojionearea#305]
Im trying to add tributejs plugin to a emojionearea initialized input element its not working fine.
then i tried to add tribute to the div in which the input contains like
<div id ="tribute">
<input id="emojionearea">
when i did like this it worked fine its causing troubles for the emojionearea functionality like jumping the cursor to the left or starting point of the text and even emojionearea is toggling after selecting an emoji.
Are there any configurations to fix it.

**Comment by mervick** [comment]
We don't support tribute js, but for mentions you can use autocomplete plugin that used for autocomplete emojis, 
See here https://github.com/mervick/emojionearea/issues/233#issuecomment-362835140

**Comment by mrshiva009** [comment]
Mervick can u tell me whether emojionearea supports mentionjs or not

**Comment by mervick** [comment]
Emojionearea supports jQuery-textcomplete, and I sent link with example above

**Comment by mrshiva009** [comment]
Yaa i did try jQuery-textcomplete and its working fine now.Thanks @mervick
