### ISSUE TITLE
event cannot bind to the textarea in angular2 

### ISSUE THREAD

**Issue by shuxikql** [mervick/emojionearea#31]
I use emojionearea in an  angular2 project, and my textarea has an (keyup) event. But when I bind the emojionearea to the textarea, the event could not be called. I do not know how to solve this problem.

My textarea element likes this:
`<textarea id="emoji-dialog" class="form-control" rows="5" [(ngModel)]="textContent" (keyup)="myKeyup(p)" (keydown)="myKeyup(p)" (change)="myKeyup(p)" #p></textarea>`

And, the myKeyup() function likes this:
`myKeyup(p){
    this.numerator = this.textContent.length;
    if(this.textContent.length>this.denominator){
      this.textContent = this.textContent.substring(0,300);
      this.numerator = this.textContent.length;
    }else{
      this.flag = 0;
    }
  }`

Looking forward to your response, thanks !

**Comment by mervick** [comment]
You can't attach events via textarea attributes, 
use for that [events](https://github.com/mervick/emojionearea#events-v21) param in options.
Also currently `keydown` event [is not triggered](https://github.com/mervick/emojionearea/issues/30)

**Comment by shuxikql** [comment]
Thanks for your response! I will try it, thanks!

**Comment by shuxikql** [comment]
Hi, mervick! I have a problem with emojionearea. How can I input the text actually in the textarea element instead of in the emojionearea-editor. I pass the value of the emojionearea-editor to the textarea now, but in this way I could not trigger the (change) event in angular2. Thanks!

**Comment by glui2001** [comment]
In angular I set the ng-model of the text input field to the value of "this.getText()" in the events area.

events: {
                keyup: function(editor, event) {
                    var emojioneArea = this; //this is instance of EmojioneArea

                    if (event.keyCode === 13 && !event.shiftKey) {
                        $scope.onPressKeyTextarea(event);
                        emojioneArea.setText('');
                        emojioneArea.hidePicker();
                        editor.focus();
                    }
                    else {
                        $scope.newMessageTxt = emojioneArea.getText();
                        console.log('keyup---' + $scope.newMessageTxt);
                    }
                },
                //when an emoji is selected from the picker popup
                emojibtn_click: function (/*button, event*/) {
                    var emojioneArea = this; //this is instance of EmojioneArea

                    $scope.newMessageTxt = emojioneArea.getText();
                    console.log('emojibtn_click---' + $scope.newMessageTxt);
                }

**Comment by mervick** [comment]
duplicate https://github.com/mervick/emojionearea/issues/122
