### ISSUE TITLE
Bug when using with medium Editor.

### ISSUE THREAD

**Issue by EmmanualVincent** [mervick/emojionearea#310]
Hi there is this issue that im facing after i implemented emojionearea with medium editor. Whatever changes done with the medium editor on the editable div is reset by the emojionearea
![screenshot from 2018-10-01 14-21-57](https://user-images.githubusercontent.com/31568229/46279262-3d53ed00-c586-11e8-8764-2dc27e58f87f.png)

After the medium editor adds <b></b> , then when i click outside of the editable div,Whatever the html content medium editor added is overwritten to how it was before.

**Comment by mervick** [comment]
It's not a bug.
You can't use 2 conenteditable editors in one element.
You should create plugin for medium editor with emojionearea picker, and put in the medium editor emojis from emojionearea when you select emoji, but I can't help you with implementation

**Comment by EmmanualVincent** [comment]
okay Thank you @mervick
