### ISSUE TITLE
Atwho and Emojionearea not working ?

### ISSUE THREAD

**Issue by contergo20** [mervick/emojionearea#315]
Hello Mr Andrey,

thank you for this great plugin !

please how i can make emojionearea works with the atwho plugin ?

here's the code in the link below :

https://jsfiddle.net/ks3q8pu9/6/

and thank you so much for your effort .

**Comment by mervick** [comment]
Hi there!

Not sure how to make it work with atwho, but you can use textcomplete plugin
link https://github.com/mervick/emojionearea/issues/233#issuecomment-362835140

example: https://jsfiddle.net/1v03Lqnu/898/

**Comment by contergo20** [comment]
Thank you
