### ISSUE TITLE
How to change default smiley button 

### ISSUE THREAD

**Issue by ph4t0o0o0om** [mervick/emojionearea#317]
How to change the default smiley button to open the emoji container?

**Comment by mervick** [comment]
Using css
https://github.com/mervick/emojionearea/blob/996872753bb380454d25c8e4568b4bcb6d4e8fc5/scss/_variables.scss#L13

https://github.com/mervick/emojionearea/blob/996872753bb380454d25c8e4568b4bcb6d4e8fc5/scss/emojionearea.scss#L153

**Comment by ph4t0o0o0om** [comment]
How?
Because my only css file here is the emojionarea.min.css ?

**Comment by mervick** [comment]
https://github.com/mervick/emojionearea/blob/master/scss/emojionearea.scss

**Comment by ph4t0o0o0om** [comment]
So I need to download this scss file and link to my web do I need to remove
the emojionarea.min.css?

**Comment by mervick** [comment]
You need to clone https://github.com/mervick/emojionearea, then modify and compile scss file.

**Comment by mervick** [comment]
After that you will have new css file, if don't want that, you can create a new css file where you can override css rules for button

**Comment by mervick** [comment]
For compile scss file using grunt
read this https://semaphoreci.com/community/tutorials/getting-started-with-grunt-js
then run
```sh
npm install
grunt sass
grunt cssmin
```

**Comment by ph4t0o0o0om** [comment]
Last question sir.

Where is the file created located?

My console says " >> 1 file created. 27.2 kB → 22.03 kB

Done, without errors."


Regards,

**Comment by ph4t0o0o0om** [comment]
Am I required to install ruby?

**Comment by mervick** [comment]
> Where is the file created located?

`dist/emojionearea.css`
`dist/emojionearea.min.css`

> Am I required to install ruby?

Yes, you require to install `sass` preprocessor,
this package dependence `grunt-contrib-sass` which require `ruby` version of `sass`,
If you want you can install `node` version of `sass` by runnig
```
sudo npm install -g sass
npm uninstall --save grunt-contrib-sass
npm install --save node-sass grunt-sass
```
But I can't guarantee that everything will work

**Comment by mervick** [comment]
Also, as option you can create your `sprite.png` and add it in your `css` without changing `emojionearea.css`

```css
.emojionearea .emojionearea--button > div {
   background-image: url('path/to/your/sprite.png');
}
```

**Comment by ph4t0o0o0om** [comment]
Thank you for your response.

One thing


How can I redesigned the text area used in emojionarea? I already add css
to the text area and call the
ID of that text area but nothing works the default design of textarea is
still there.

How can I modify the design of text are? Because I want to add
border-radius and border color .


Regards,

**Comment by mervick** [comment]
It replace `textarea` with content editable `div`.
You can change it in `scss` file
https://github.com/mervick/emojionearea/blob/d829da181a86aa3891ef4223c2db7ae44655230f/scss/emojionearea.scss#L54-L55
https://github.com/mervick/emojionearea/blob/d829da181a86aa3891ef4223c2db7ae44655230f/scss/_variables.scss#L6-L7
https://github.com/mervick/emojionearea/blob/d829da181a86aa3891ef4223c2db7ae44655230f/scss/emojionearea.scss#L64-L66
https://github.com/mervick/emojionearea/blob/d829da181a86aa3891ef4223c2db7ae44655230f/scss/_variables.scss#L9-L10
