### ISSUE TITLE
Filter titles show up on textarea

### ISSUE THREAD

**Issue by Pela647** [mervick/emojionearea#318]
Emoji titles are showing up inside textarea, anyone had this issue before?? I have the following text inside my textarea _[ **RecentSmileys & PeopleAnimals & NatureFood & DrinkActivityTravel & PlacesObjectsSymbolsFlagsDiversityDiversityDiversityDiversityDiversityRecentSmileys & PeopleAnimals & NatureFood & DrinkActivityTravel & PlacesObjectsSymbolsFlagsDiversityDiversityDiversityDiversityDiversity**]_

**Comment by mervick** [comment]
Close this because there is no response

**Comment by wikiweb** [comment]
I have this issue too 
RecentSmileys & PeopleAnimals & NatureFood & DrinkActivityTravel & PlacesObjectsSymbolsFlagsDiversityDiversityDiversityDiversityDiversity

**Comment by mervick** [comment]
Please create screenshot or video, I can't reproduce

**Comment by surya304** [comment]
i had the same isssue i tried to create todolist with each input containing emoji area its worked for a sec  but when i tried to add new input it is appending this text 
"RecentSmileys & PeopleAnimals & NatureFood & DrinkActivityTravel & PlacesObjectsSymbolsFlagsDiversityDiversityDiversityDiversityDiversity"

**Comment by mervick** [comment]
Screenshot or video

**Comment by nikhilprasad11** [comment]
I was able to reproduce. 
1. Init emojionearea using the class method.
2. Try to apply again on some other widget with same class name.

**Comment by Adri96MH** [comment]
I have the same problem, any solution?

 I have the following text inside my textarea:
RecentSmileys & PeopleAnimals & NatureFood & DrinkActivityTravel & PlacesObjectsSymbolsFlagsDiversityDiversityDiversityDiversityDiversity

**Comment by mervick** [comment]
What browser do you use? Can you create an example with this bug on [jsfiddle.net](https://jsfiddle.net) ?

**Comment by Adri96MH** [comment]
It happens initiating again emojionearea  in some other widget with the same class name.
Here: https://jsfiddle.net/123utzwp/

**Comment by Adri96MH** [comment]
Another example: https://jsfiddle.net/123utzwp/2

Calling a function that do this: $('.emojiPicker').emojioneArea()[0].emojioneArea.getText() appears "RecentSmileys & PeopleAnimals & NatureFood & DrinkActivityTravel & PlacesObjectsSymbolsFlagsDiversityDiversityDiversityDiversityDiversity" in the text area

**Comment by mervick** [comment]
Ok, I see.
You don't need to call `emojioneArea()` constructor twice on the same element.
I made some changes on your fiddles to make it work right
https://jsfiddle.net/mervick/9n74x8fc/
https://jsfiddle.net/mervick/yf31kbe9/

**Comment by shivamsahu7** [comment]
please fix this problem RecentSmileys & PeopleAnimals & NatureFood & DrinkActivityTravel & PlacesObjectsSymbolsFlagsDiversityDiversityDiversityDiversityDiversity

**Comment by mervick** [comment]
You don't need to call emojioneArea() constructor twice on the same element.
