### ISSUE TITLE
Almost perfect! Handle to instance object

### ISSUE THREAD

**Issue by glui2001** [mervick/emojionearea#32]
Hi,

Great job on the component.  I really like what you did allowing some much flexibility and configurability.

That being said I wondered if there was a way to get a handle on an instance of the emojionearea object?  

For example, can it return a handle to something that I can call methods on?  I can call these methods in the event handlers, but I want to access these methods outside of that

```
var handle = $('.selector).emojioneArea();
handle.setText();
```

**Comment by mervick** [comment]
Hi,
You can do this
```js
var handle = $('.selector').emojioneArea().data('emojioneArea');
handle.setText();
```

**Comment by glui2001** [comment]
Awesome! Thanks for the prompt response!  Now my follow up question is whether I can use the handle and call a method to put the focus on the editable content div.

I see in the source code that the internal editor object is calling focus(), but it would be helpful to have a "EmojioneArea.prototype.focus" method exposed

**Comment by mervick** [comment]
I understand you. I can make that method in future,
currently you can use `handle.editor.focus()`

**Comment by glui2001** [comment]
`handle.editor.focus()` doesn't seem to work.  I'm calling it in conjunction with public handle methods

```
if (event.keyCode === 13 && !event.shiftKey) {
                        // $scope.onPressKeyTextarea(event);
                        emojioneArea.setText('');
                        emojioneArea.hidePicker();
                        emojiHandle.editor.focus();
                    }
```

**Comment by mervick** [comment]
Change `emojiHandle.editor.focus();` to
```js
emojioneArea.editor.focus();
```

**Comment by mervick** [comment]
I don't know exactly where you get `emojioneArea` variable, but it must be the same as 
```js
var element = $(".selector").emojioneArea({
    // options here
});
var emojioneArea = element[0].emojioneArea;
// ...
emojioneArea.setText('');
emojioneArea.hidePicker();
emojioneArea.editor.focus();
```

**Comment by glui2001** [comment]
`emojioneArea` is just a reference to `this` in the event config

```
events: {
                keyup: function(editor, event) {
                    var emojioneArea = this; //this is instance of EmojioneArea

                    if (event.keyCode === 13 && !event.shiftKey) {
                        // $scope.onPressKeyTextarea(event);
                        emojioneArea.setText('');
                        emojioneArea.hidePicker();
                        emojioneArea.editor.focus();
                    }
                    else {
                        $scope.newMessageTxt = emojioneArea.getText();
                        console.log('keyup---' + $scope.newMessageTxt);
                    }
                },
```

`emojioneArea.editor.focus();` is still not working for me

**Comment by mervick** [comment]
```js
keyup: function(editor, event) {
    editor.focus();
}
```

**Comment by glui2001** [comment]
It's part of a form, so when I submit it then focus is lost.  Somewhere in a success callback I want to set the focus on the emojioneArea again.
