### ISSUE TITLE
why sprite mest be emojioneSupportMode<3?

### ISSUE THREAD

**Issue by huobazi** [mervick/emojionearea#325]
Hi,
I don't understand why emojionearea use sprite must be emojioneSupportMode<3 ?

https://github.com/mervick/emojionearea/blob/996872753bb380454d25c8e4568b4bcb6d4e8fc5/src/function/init.js#L36

see also:
https://codepen.io/huobazi/pen/WYmwmG

**Comment by mervick** [comment]
Because [Emojione](https://github.com/emojione/emojione) removed sprite support in major releases die to the chrome bug and you can use sprite only in old releases

**Comment by huobazi** [comment]
@mervick i see the emojione assets repo 
https://github.com/emojione/emojione-assets/tree/master/sprites was commit on 4.0 

and i create a demo 
https://codepen.io/huobazi/pen/WYmwmG

**Comment by mervick** [comment]
Seems they added `png` sprites, but there is no way to use custom height of emojis, and there is no way to set it to default size 20x20.
They removed support of svg sprites, which was really awesome.

https://codepen.io/mervick/pen/yQmgrV
