### ISSUE TITLE
How to fix this? 

### ISSUE THREAD

**Issue by densavi** [mervick/emojionearea#329]
![image](https://user-images.githubusercontent.com/22726613/50978437-1601aa00-14fd-11e9-8347-b8d4c8627eec.png)

Ubuntu 18.04 
Google Chrome 70.0.3538.77

**Comment by mervick** [comment]
It's a bug with chrome.
refs:
https://productforums.google.com/forum/#!msg/chrome/yD9L8W9zF4g/1KsXelHkAQAJ
https://bugs.chromium.org/p/chromium/issues/detail?id=867813
