### ISSUE TITLE
focus not working

### ISSUE THREAD

**Issue by hacknlove** [mervick/emojionearea#331]
If I do:

```
$('textarea').data('emojioneArea').focus()
```

I get `TypeError: $(...).data(...).focus is not a function` because it is `undefined`

But the next, does work.
```
$('textarea').data('emojioneArea').setText('hello')
$('textarea').data('emojioneArea').showPicker()
```

So I think that there is something wrong with "focus" method

**Comment by mervick** [comment]
... seems wrong docs,
try to use `setFocus()` instead of `focus()`

**Comment by kak2z7702** [comment]
not working to..

`emojioneArea1[0].emojioneArea.setFocus();`

**Comment by mervick** [comment]
It's working, example
https://jsfiddle.net/mervick/qp6htx4c/1/

**Comment by kak2z7702** [comment]
yes)) sorry.. i have small js skills) i use this sample https://www.jqueryscript.net/demo/WYSIWYG-Emoji-Converter-Picker-Plugin-For-jQuery-EmojiOne-Area/
in this sample not visible textarea...  but I liked the smilie panel...
I will try to focus on this example.
thank you..

**Comment by mervick** [comment]
It's old outdated version of EmojioneArea

**Comment by kak2z7702** [comment]
but very nice example)

**Comment by mervick** [comment]
Working example for EmojioneArea 2.1.4
https://jsfiddle.net/mervick/qp6htx4c/3/

**Comment by kak2z7702** [comment]
thank you)) 
I don't have place for a pop up area)) so using the old version

**Comment by kak2z7702** [comment]
sorry)) How to set the cursor at the end of the text? Thanks)

**Comment by mervick** [comment]
https://jsfiddle.net/mervick/qp6htx4c/6/

**Comment by kak2z7702** [comment]
Sorry((( 
Am i doing something wrong? https://jsfiddle.net/1ym5nx4g/
I want to click on the name. Then get the focus in the editor.

**Comment by mervick** [comment]
https://jsfiddle.net/mervick/5npabce3/1/
