### ISSUE TITLE
Incompatibility with at.js in recent versions

### ISSUE THREAD

**Issue by stof** [mervick/emojionearea#333]
I am using [at.js](https://github.com/ichord/At.js) alongside emojionearea, by enabling it on the contenteditable editor of emojionearea. This worked fine with emojionearea 3.2.6 (note that I have `autocomplete` disabled for emojionearea. I haven't tried with it enabled). When upgrading to 3.4.1, this does not work anymore, because emojionearea removes the span used by at.js to wrap the range triggering it while its dropdown is opened.

**Comment by carpii** [comment]
@stof - at.js appears to be discontinued, in favour of tribute...  https://github.com/zurb/tribute

If you are having the same issue with tribute, provide a demo url I can test with, and I'll take a look
