### ISSUE TITLE
Dynamic Html with Emoji

### ISSUE THREAD

**Issue by tareqballan** [mervick/emojionearea#335]
Greetings,

I am working on a chat system, the story is that I am generating a chat box when the user clicks on a user icon, this chatbox contains an Input element where I am rendering the EmojiOneArea.

The problem:
The first generated chat box is working fine with EmojiOneArea, after I click on another user icon to start chatting, the first EmojiOneArea gets corrupted and unclickable but the new one (the second one) works correctly. The same scenario is applicable to the third generated chatbox and etc. 

My question is that a common issue? Does anyone know what the problem might be?

**Comment by mervick** [comment]
If you want help, the best way to share this error on https://jsfiddle.net/

**Comment by VishalChaturvedi** [comment]
I want to use it with newly created dom element(text area) after page render.
How can I use it?
