### ISSUE TITLE
How do I open the emojionearea window by clicking a bottom a create?

### ISSUE THREAD

**Issue by jerryliu1997** [mervick/emojionearea#336]
Hi, there. If I have a button whose ID is "emojiButton", what I wanted to do is to open up the emojionearea window directly by clicking the Button I created? 

Now, my understanding is I have to do everything from `@$("aTextArea").emojioneArea({
       pickerPosition: "right"
       searchPlaceholder: "Search"
       standalone: true
      })`
but doing so will also automatically add a button on it. Does anyone have any suggestions?

**Comment by mervick** [comment]
Use showPicker() method
https://github.com/mervick/emojionearea#showpicker

**Comment by jerryliu1997** [comment]
Thank you for your reply. I checked that before, but do I need to do a "@$("aTextArea").emojioneArea({ pickerPosition: "right" searchPlaceholder: "Search" standalone: true })" before using showPicker() method. If I do that, it will create a new button, which I don't want.

**Comment by mervick** [comment]
You can hide this button using css

**Comment by jerryliu1997** [comment]
Sounds good. Thank you!
