### ISSUE TITLE
on IE EDGE: Cursor pointer position is after placeholder text instead at start 

### ISSUE THREAD

**Issue by SaadAhmedSiddiqui** [mervick/emojionearea#337]
https://jsfiddle.net/k2gbjfwm/1/

here is the fiddle. you can open in chrome and all will work as expected but on IE Edge the cursor pointer is after placeholder text on the input field

**Comment by mervick** [comment]
I have not IE edge, and I don't care about this shitty browser

**Comment by waleedramzan** [comment]
@SaadAhmedSiddiqui you can remove the emojionearea placeholder and apply css to the contenteditable div like this fiddle: http://jsfiddle.net/RZZ6X/9/

**Comment by SaadAhmedSiddiqui** [comment]
@waleedramzan I dont see emojionearea in your fiddle. i mean i do need to use the emoticons as well from emojionearea on my input field plus the fix of the placeholder text on IE edge.

**Comment by waleedramzan** [comment]
@SaadAhmedSiddiqui This fiddle is showing us how to set placeholder for contenteditable div using css and js. You can use this as a reference and apply it to emojione contenteditable with class name 'emojionearea-editor'.

**Comment by SaadAhmedSiddiqui** [comment]
@waleedramzan  thanks for the help. and here is the final fiddle if anyone has gone through the same issue. 
https://jsfiddle.net/x21gL75h/8/

**Comment by waleedramzan** [comment]
> @waleedramzan thanks for the help. and here is the final fiddle if anyone has gone through the same issue. It is not an exact behavior for placeholder but considering IE case it still would work fine i think,
> https://jsfiddle.net/x21gL75h/8/

@SaadAhmedSiddiqui  that's great! Glad that it worked :)
