### ISSUE TITLE
Such a great plug-in! May I ask how to replace icons of categories and emoji button?

### ISSUE THREAD

**Issue by xiaomeng2372** [mervick/emojionearea#339]
May I ask how to replace icons of categories and emoji button with the pngs I have?

**Comment by mervick** [comment]
You can't do with current api, you need to make changes in plugin source code

**Comment by jerryliu1997** [comment]
Would you mind telling me how to do that? Thank you!

**Comment by mervick** [comment]
I think the most simple way to do that is to customize using css

**Comment by jerryliu1997** [comment]
Oh no. I suck at CSS lol. Can you give me an example? For like how to replace the button icon. Thank you!
