### ISSUE TITLE
Emojis size

### ISSUE THREAD

**Issue by GreatWhiteness** [mervick/emojionearea#340]
Where i can change size..

**Comment by GreatWhiteness** [comment]
Using new joypixels with this how ?

**Comment by mervick** [comment]
WE don't support joypixels yet

**Comment by GreatWhiteness** [comment]
Can i use this without Emojione license? and what is this http://github.com/joypixels/emojione do i have to install both ? i have just installed your Emoji Picker..

**Comment by mervick** [comment]
You should use both licenses

**Comment by GreatWhiteness** [comment]
Are these both emoji pickers..
