### ISSUE TITLE
Disable CDN. Load Files Locally

### ISSUE THREAD

**Issue by fclaussen** [mervick/emojionearea#344]
I've tried everything I could think of to load the images locally and not through a CDN.

I've added emojione.js and I am loading it before emojionearea.
I've changed my settings to `useInternalCDN: false,` which only removed the `/32/` portion of the image source.

I was able to do this with emojione. Emojis loaded around the site using PHP are loading local images. 
I want my standalone picker to do the same.

Can someone supply me with a working example of how they did it?

**Comment by carpii** [comment]
I've pushed a new internal_cdn branch, could you try with that?

https://github.com/mervick/emojionearea/blob/internal_cdn/dist/emojionearea.js

See updated README

**Comment by carpii** [comment]
@fclaussen do you still need this change? If not I will close the ticket

**Comment by fclaussen** [comment]
I'll try that asap and let you know

**Comment by carpii** [comment]
No response, closing ticket
