### ISSUE TITLE
is it possible to change launcher icon ?

### ISSUE THREAD

**Issue by ifsaud** [mervick/emojionearea#347]
Hello ,,
small question is it possible to change this icon with any icon existed in the lib or any icon else ?
thanks
![image](https://user-images.githubusercontent.com/49584287/56077491-8adacd80-5de5-11e9-8af9-b2481f557dfb.png)

**Comment by mervick** [comment]
CSS

**Comment by ifsaud** [comment]
Which one please

**Comment by mervick** [comment]
https://github.com/mervick/emojionearea/blob/master/scss/emojionearea.scss#L132-L185
