### ISSUE TITLE
Emoji's js file taking too much time to load

### ISSUE THREAD

**Issue by eriffat896** [mervick/emojionearea#348]
I am working on adding emoji in comment textarea. It has added in comment textarea, but it is loading speed is so slow (around 72ms...after analyzing it in developer tool's network column) and after adding it the functionality of a whole page has stopped working until emoji file has loaded. 
In texarea, auto_grow(this) is stop working also.
Can you help me to fix it?

Thanks in advance.

**Comment by carpii** [comment]
Can you post your demo which shows this problem?

**Comment by eriffat896** [comment]
> Can you post your demo which shows this problem?

Yeah sure,

**Comment by eriffat896** [comment]
```
<script>
       /***** emoji plugin in textarea ****/
      $(document).ready(function(){
         
           $('#commpost<?php echo $count;?>').emojioneArea({
  	             pickerPosition: "top",inline: true
            });
       })
	    /*****(end)//emoji plugin in textarea ****/
    </script>

<div style="width:95%"> <!--div for emoji textarea -->
<textarea id="commpost<?php echo $count;?>" class="comtemoji" placeholder="Comment..." oninput="auto_grow(this)"></textarea>
   
</div>
```
<script>
// functon for comment size increase
document.getElementsByClassName("emojionearea-editor").oninput()
function auto_grow(element) {
    element.style.height = "10px";
    element.style.height = (element.scrollHeight)+"px";
}

</script>

**Comment by carpii** [comment]
I meant an online demo, so I can see the full page source and the same network issues you are seeing :)
