### ISSUE TITLE
Add emojionearea in every post

### ISSUE THREAD

**Issue by raredudex** [mervick/emojionearea#349]
Hello mervick,
I just wana appreciate you for what you doing for the community.
Please i am having the same issue with Bathorus.
But in my own case i am using only PHP OOP and mysqli.
My emojionearea frontend is working, but when you make a post the emojionearea icon will not appear on the posted comment.
Please pardon me i have not used any PHP framework before and i have not used PDO before.
Please assist me.
Thanks and stay blessed.

**Comment by mervick** [comment]
See #48, #42

**Comment by raredudex** [comment]
I tried implementing your code, but i was getting an error.
sorry i am using php 5.6...
mysqli.
I am not using PDO.
And i am not using php OOP.
is there a code for this in normal php development.

**Comment by carpii** [comment]
@raredudex you need to make your MySQL database is using utf8mb4 character set, AND you have told your mysqli lib to use utfmb8, AND your page is also using utf8 character set.

**Comment by raredudex** [comment]
Yes @carpii I have done all that bro.
When i post. it shows in text, but i want to show as icons.
Thanks :)

**Comment by carpii** [comment]
@raredudex What is the exact text you're seeing when you pull it from the database? You need to be more specific on the problem you're having

**Comment by raredudex** [comment]
I have not written any backend code yet.
this is the code he set me.
I think it OOP and PDO.
I am not an expert in both.
I can manipulate oop a little bit.
how can i convert this code to procedural.
<?php

use Emojione\Emojione;
use Emojione\Client as EmojioneClient;

// your code...

$emojioneClient = new EmojioneClient();
$emojioneClient->cacheBustParam = '';
$emojioneClient->imagePathPNG = 'https://cdnjs.cloudflare.com/ajax/libs/emojione/2.1.4/assets/png/';
Emojione::setClient($emojioneClient);

$body = htmlspecialchars($field_from_db);
$body = Emojione::shortnameToImage($body);
$body = nl2br($body);

echo $body;

**Comment by carpii** [comment]
There is no PDO being used here. 
It is already mostly procedural, but it uses the EmojiOne class.

There's no reason you should try to avoid using that class, even if you're using mysqli for your database connectivity

**Comment by raredudex** [comment]
Ok thanks for enlightening me.
Do i need to create a table for emojione?

**Comment by carpii** [comment]
No, EmojiOne is just code (company has renamed to JoyPixels now). 

You may need a license to use their Emoji's in production though

https://www.joypixels.com/

**Comment by raredudex** [comment]
OK...
is that the reason is not working for me?

**Comment by carpii** [comment]
No, Its not working for you due to some other reason, which you haven't properly explained

**Comment by mervick** [comment]
Can you read all text from links?
https://github.com/mervick/emojionearea/issues/42#issuecomment-236349667

**Comment by raredudex** [comment]
> @raredudex What is the exact text you're seeing when you pull it from the database? You need to be more specific on the problem you're having



> @raredudex What is the exact text you're seeing when you pull it from the database? You need to be more specific on the problem you're having

This is what i get;
what's up?:money_mouth:
I wrote what's up and selected money mouth emoji icon and i got that.

And sorry for taking too long to reply i have gone back to school and have been very busy with school activity. Plus i didn't actually see this post before replying other post.

**Comment by mervick** [comment]
If you get `:money_mouth:` from the database, then you need to set option `shortnames` to `true`

https://github.com/mervick/emojionearea#shortnames

```js
$(".emojionearea").emojioneArea({
    shortnames: true
});
```

**Comment by raredudex** [comment]
> If you get `:money_mouth:` from the database, then you need to set option `shortnames` to `true`
> 
> https://github.com/mervick/emojionearea#shortnames
> 
> ```js
> $(".emojionearea").emojioneArea({
>     shortnames: true
> });
> 

Thanks for responding to my post Mervick,

I just changed it ("shortnames: true) to true. Nothing was posted.
And i went to my phpmyadmin, and i discovered that nothing was sent to the database and nothing was retrieved.

**Comment by mervick** [comment]
I don't know how you send data from html to your backend and how you save data to database, so I can't help you. Try to debug your code on each in every stage.

**Comment by raredudex** [comment]
> I don't know how you send data from html to your backend and how you save data to database, so I can't help you. Try to debug your code in every stage.

I am using these codes to filter what enters my database;

$body = strip_tags($body);
	$body = mysqli_real_escape_string($this->connect, $body);
	$check_empty = preg_replace('/\s+/', '', $body);

could any of them be the reason i am not getting any result?

**Comment by mervick** [comment]
```php
$body = strip_tags($body);
print_r($body); // do you have anything here?
```

**Comment by raredudex** [comment]
> ```
> $body = strip_tags($body);
> print_r($body); // do you have anything here?
> ```

No i don't have anything there.
It works as if 
print_r($body);
it not there.

**Comment by mervick** [comment]
So you don't send anything to backend

**Comment by raredudex** [comment]
But if i type ordinary word like;
cool.
it will appear in the post.
if select emoji
saveEmojisAs: "shortname"
cool:money_mouth:
But if i change it to;
shortnames: true
nothing will appear

**Comment by raredudex** [comment]
I saw this your code somewhere can it solve this issue?

in backend:

first of all, install emojione php lib,
prefer installation via composer composer require emojione/emojione

next, in your php for rendering html from db

<?php

use Emojione\Emojione;
use Emojione\Client as EmojioneClient;

// your code...

$emojioneClient = new EmojioneClient();
$emojioneClient->cacheBustParam = '';
$emojioneClient->imagePathPNG = 'https://cdnjs.cloudflare.com/ajax/libs/emojione/2.1.4/assets/png/';
Emojione::setClient($emojioneClient);

$body = htmlspecialchars($field_from_db);
$body = Emojione::shortnameToImage($body);
$body = nl2br($body);

echo $body;
