### ISSUE TITLE
getText(): one character short

### ISSUE THREAD

**Issue by glui2001** [mervick/emojionearea#35]
It appears that there is one character short of the text in content editable component when `getText()` is invoked.

I simply attached the events config below into the fiddle at https://jsfiddle.net/glui2001/ukLaz8cm/
```
events: {
         keypress: function (editor, event) {
           console.log(editor.html());
           console.log(this.getText());
         }
}
```

**Comment by mervick** [comment]
See bug https://github.com/mervick/emojionearea/issues/30
only `keyup` event return real value

your fiddle with `keyup`
https://jsfiddle.net/ukLaz8cm/6/
