### ISSUE TITLE
Parse code saved with option saveEmojisAs: 'image'

### ISSUE THREAD

**Issue by mervick** [mervick/emojionearea#351]
![photo_2019-04-25_23-47-35](https://user-images.githubusercontent.com/2429298/56767554-b5009800-67b4-11e9-8a98-9f97b5832720.jpg)

**Comment by shanoweb** [comment]
hello how, to make on the end of emoji src "png"?
coz in my in the end SVG always

**Comment by mervick** [comment]
@shanoweb create an example at https://jsfiddle.net/

**Comment by pascalf22** [comment]
Hello !
This happen to me too... if my field lost focus... all image is transformed in URL... just like your message...

How can i prevent this ?

Thanks a lot !

Pascal

**Comment by mervick** [comment]
Duplicate of https://github.com/mervick/emojionearea/issues/350
