### ISSUE TITLE
get emoji icon value

### ISSUE THREAD

**Issue by soundaraj** [mervick/emojionearea#352]
i need emoji text like "hai😆😆😆😆" but i got `"hai<img alt="😌" class="emojioneemoji" src="https://cdn.jsdelivr.net/emojione/assets/3.1/png/32/1f60c.png"><img alt="😌" class="emojioneemoji" src="https://cdn.jsdelivr.net/emojione/assets/3.1/png/32/1f60c.png"><img alt="😌" class="emojioneemoji" src="https://cdn.jsdelivr.net/emojione/assets/3.1/png/32/1f60c.png">` " how to change this

**Comment by carpii** [comment]
Post sample code.. https://jsfiddle.net/mervick/1v03Lqnu/765/
