### ISSUE TITLE
Node Count

### ISSUE THREAD

**Issue by fclaussen** [mervick/emojionearea#353]
I've been tasked to use this to add reactions to comments on a WordPress installation.
I've added this library to the plugin I was developing but we've noticed that the node count has skyrocketed.

The reason why seems to be that every comment on a post is loading one picker.

Is there a way to only have one picker that will be reused by multiple standalone instances?

I've attached a picture of what it looks like. When you click on the first "pill" you get the picker. On each comment, you have a picker. Adding a lot of nodes.

![Screen Shot 2019-04-30 at 4 46 34 PM](https://user-images.githubusercontent.com/1021860/56992314-bf7db180-6b67-11e9-9d84-5aa34e31ab18.png)

**Comment by carpii** [comment]
I'm not sure what the screenshot is showing exactly, but there is no need to create an EmojiOneArea for every post until you are actually using it.

You could just create one when they click the Reply link, or if thats not possible then just use a normal HTML input, and convert it into an EmojiOneArea when they actually display and focus it.

**Comment by fclaussen** [comment]
Hi @carpii 
The image is just to show what I meant. Each comment has one picker (first icon under Reply).

How could I only load it when they click on the pill? The pill is the standalone button created by emojionearea.

Do you want me to setup a dev link so I can share it? Maybe it will be easier that way.

**Comment by carpii** [comment]
Hi, you should not need EmojiOneArea just to display the Emoji pill.
You can just use EmojiOne library to get the image

You only need EmojiOneArea when the user tries to edit it or select a new one

**Comment by fclaussen** [comment]
Oh, I know.
I am using emojione to load the images.
But when you use emojionearea in standalone mode it creates a button that you click to open the picker.
The first "pill" is this button with changed css.

Problem is that I am loading emojionearea on every comment (not image), thus creating multiple pickers.

**Comment by carpii** [comment]
Ok, but if you create a new EmojiOneArea for every single pill, you will always have performance problems.

Why not just render the pill yourself using CSS and EmojiOne?

**Comment by fclaussen** [comment]
I need the user to click that first one and open the picker.

**Comment by fclaussen** [comment]
I'll put a dev link up tomorrow and update this with a link. I feel like there's a miscommunication.

**Comment by fclaussen** [comment]
Here's the link: http://dev.trewknowledge.com/emoji-plugin/2019/05/01/hello-world/

The buttons with actual emojis won't do anything. they are just images.
The first button is the standalone emojionearea. 

Right now if you click the first button on each comment you will see two separate pickers. That means that we have double the amount of nodes.

I am wondering if it's possible to have only **one** picker, independent on how many comments I put in and they all share it. That way we I can reduce the amount of nodes drastically.

If it's easier to understand, imagine you have 30 textareas that are using emojionearea to add a picker. You wouldn't want 30 different pickers adding nodes. How would you only have one?

**Comment by mervick** [comment]
Please create simple example at jsfiddle then I can show you how you can improve that

**Comment by fclaussen** [comment]
@mervick https://jsfiddle.net/6fxqkgzy/1/

**Comment by mervick** [comment]
https://jsfiddle.net/mervick/8jrgqzyo/51/
