### ISSUE TITLE
<br> at the end of the text

### ISSUE THREAD

**Issue by ManuQuery** [mervick/emojionearea#356]
hi! 
When I paste a text or write, I insert a < BR> at the end of the code
Is this a bug?
I need to know if the last string is a URL, but when I insert a < BR>, it destroys my algorithm. detects the BR as part of the text =(

```
< div class="emojionearea-editor" placeholder="Text" tabindex="0" dir="ltr" spellcheck="false" autocomplete="off" autocorrect="off" autocapitalize="off" contenteditable="true">
< div>wadaw adw adw awd adwa</div>
< div>w <br></div>
< div>adw <br></div>
< div>https://www.bbc.co.uk/news <br></div>
</ div>`
```

**Comment by mervick** [comment]
You should learn how works contenteditable in different browsers, some of them use <br>, <div> or <p>.
It's not related to this plugin

**Comment by mervick** [comment]
If you need to insert new line then you should insert new line, it does not support html
