### ISSUE TITLE
After implementing Emoji picker style and position of input is changed and doesn't accept old styles.

### ISSUE THREAD

**Issue by crazycodewriter** [mervick/emojionearea#357]
Before implementing the emoji picker input looked like this:

![issue](https://user-images.githubusercontent.com/45752354/58192495-ea27d980-7cd1-11e9-9187-59a3480d4df5.png)

Then after implementing emoji picker, it looks like this:
![issue2](https://user-images.githubusercontent.com/45752354/58192534-fca21300-7cd1-11e9-93e1-55c989ebfb34.png)

I tried to look via inspect on chrome and find classes for making changes but whatever I do it still stays the same.
How can I make the input textarea move to the old position with the old styles?

**Comment by mervick** [comment]
Create an example at jsfiddle

**Comment by mervick** [comment]
It does not related to plugin, emojionearea uses css styles, you can override them, it's not just a "input textarea" it's a contenteditable

**Comment by crazycodewriter** [comment]
@mervick  but what classes should be overridden. I checked all via inspect and nothing worked whatever I tried. CSS file looks very confusing. What classes should I exactly target?

**Comment by mervick** [comment]
https://github.com/mervick/emojionearea/blob/master/scss/emojionearea.scss
https://github.com/mervick/emojionearea/blob/master/dist/emojionearea.css
