### ISSUE TITLE
Submit the form with Enter key not working 

### ISSUE THREAD

**Issue by phpfreak2017** [mervick/emojionearea#359]
Dear Mervick 

please check my code submiting the form with Enter key not working 

`$(document).ready(function(){

	 
 
    $("#usermsg").emojioneArea({
    inline: true,
	hidePickerOnBlur: true,
    tones: false,
	autocomplete: false
	});
	

	//If user submits the form
	function SendMsg(){
		var clientmsg = $("#usermsg").val();
		if(clientmsg != ''){
			$.post("chat.php", {chatinput: clientmsg});				
			$("#usermsg").attr("value", "");
		}
		$("#usermsg").focus();
	}
	
	
	$("#submitmsg").click(function(){	
		SendMsg();
		$('#usermsg').val('');
		
		return false;
		
	});
	
	
	//Load the file containing the chat log
	function loadLog(){
		var oldscrollHeight = $("#chatoutbox").scrollHeight - 20;
		$.ajax({
			url: "ajaxchat.php",
			cache: true,
			success: function(html){
				$("#chatbox").html(html); //Insert chat log into the #chatbox div	
				
                var height = document.getElementById("chatoutbox").scrollHeight - $('#chatoutbox').height(); 
				
				$('#chatoutbox').scrollTop(height);	
            //var scrollval = $("#chatbox").height();
		    //$("#chatbox").animate({scrollTop: scrollval }, 1000);		
		  	},
			
			
		});
				
		//$("#chatoutbox").animate({ scrollTop: $("#chatoutbox").get(0).scrollHeight}, 1500);
	}
	
	
	setInterval (loadLog, 2500);	//Reload file every 2.5 seconds
	
	$('#usermsg').bind('keypress', function(e) {
		//alert(e.keyCode);
		var code = (e.keyCode ? e.keyCode : e.which);
		 if(code == 13) { //Enter keycode
		   	SendMsg();
			$('#usermsg').val('');
			
			return false;
		 }
	});
});`

**Comment by carpii** [comment]
Which bit isn't working?

You should probably just create an example fiddle to demo the problem...

https://jsfiddle.net/mervick/1v03Lqnu/765/

**Comment by phpfreak2017** [comment]
here you go
https://jsfiddle.net/smzcq8b2/

the problem is : before adding EmojiOneArea pressing the enter key to submit the form was perfectly working , after i added the emojionearea i can't press enter key to submit my form 

could you help me ?

**Comment by carpii** [comment]
EmojiOneArea replaces the textarea with a div, so any keypress handlers you add to your textarea aren't being triggered

Instead you need to pass some event handlers during the EmojiOneArea constructor..

See this example..

https://jsfiddle.net/up0g7k5j/1/

**Comment by carpii** [comment]
Actually I think you may need to handle the keyup event instead of keypress, to capture the Enter key..

https://jsfiddle.net/up0g7k5j/2/

**Comment by phpfreak2017** [comment]
same code dude keypress

**Comment by carpii** [comment]
I don't know what you mean

**Comment by phpfreak2017** [comment]
you mean that i need to put the pressing enter submit function inside Event: ?

**Comment by phpfreak2017** [comment]
because in the example you gave me , i tried the code , still enter key is not functioning

**Comment by phpfreak2017** [comment]
could you give me the full function to call SendMsg() function and submit the form ?

**Comment by carpii** [comment]
I didn't fix your whole code. I just added an event handler and now emojionearea responds to enter key

You need to move your logic into the events: bit

**Comment by phpfreak2017** [comment]
am not that great in js , if you could provide me an example how to handle the enter key in event , it would be great and i will be so thankfull

**Comment by carpii** [comment]
https://jsfiddle.net/xajdmsfn/

**Comment by phpfreak2017** [comment]
actually still not SendMsg function not working , but its catching the enter key
