### ISSUE TITLE
function not working in event 

### ISSUE THREAD

**Issue by phpfreak2017** [mervick/emojionearea#360]
hello after submiting enter key , the text field is cleared but it nevers call the function SendMsg()

`
    $("#usermsg").emojioneArea({
    inline: true,
	hidePickerOnBlur: true,
    tones: false,
	autocomplete: false,
	
	events: {
    keydown: function (editor, event) {
      var code = (event.keyCode ? event.keyCode : event.which);
      if (code == 13) { //Enter keycode
        //$("#chatform").submit();
			SendMsg(); // this is not working !
			$("div.emojionearea-editor").data("emojioneArea").setText('');
			$('#usermsg').val('');
        return false;
      }
    }
	}
	});
	

	//If user submits the form
	function SendMsg(){
		var clientmsg = $("#usermsg").val();
		if(clientmsg != ''){
			$.post("chat.php", {chatinput: clientmsg});				
			$("#usermsg").attr("value", "");
		}
		$("#usermsg").focus();
	}`

**Comment by mervick** [comment]
keydown event is not supported, please check all available events here https://github.com/mervick/emojionearea#events

**Comment by mervick** [comment]
ref  https://github.com/mervick/emojionearea/issues/30
