### ISSUE TITLE
Emojionearea events not work on dynamic content.

### ISSUE THREAD

**Issue by BoumBam** [mervick/emojionearea#362]
that code below works fine but not works for dynamic added content.

```            var wall_post_commment_form_id;
              var comment_text;
              var comment_id_wall_post;
              $(".wall_post_commment").emojioneArea({
                events: {
                  keyup: function(editor, event) {
                    comment_text = this.getText();
                    if (event.which == 13 && $.trim(comment_text) != "") {
                        wall_post_commment_form_id = $(this.editor).parent().parent().attr("id");
                        comment_id_wall_post = $(this.editor).closest(".panel-default").attr("data-id_wall_post");
                        if (comment_text.length < 10000) {
                          $($(this.editor).parent().parent()).submit();
                        }else{
                            .............................
                        }
                        event.preventDefault();
                    }
                  }
                }
              });
```

How could I do to make that code to work for dynamic added content?

Thanks.

**Comment by mervick** [comment]
Please create example at jsfiddle

**Comment by BoumBam** [comment]
Sorry but I don't have a jsfiddle account.
I would like to know if that code works on dynamically added input after an ajax request ?

```
 $(".wall_post_commment").emojioneArea({
              events: {
                  keyup: function(editor, event) { 
                    }
              }
 });
```

**Comment by mervick** [comment]
I can't help you without example

**Comment by mervick** [comment]
You should not to use `event.preventDefault();`

**Comment by mervick** [comment]
Yes, it will work ater ajax request, example https://jsfiddle.net/mervick/r7deLuy9/2/

**Comment by BoumBam** [comment]
I have to add that

   ```$(".CLASS_OF_THE_NEW_INPUT").emojioneArea({`
                                events: {
                                  keyup: function(editor, event) {
                                    comment_text_reply = this.getText();
                                    if (event.which == 13 && $.trim(comment_text_reply) != "") {
                           
                                          $($(this.editor).parent().parent()).submit();
                                     
                                        event.preventDefault();
                                    }
                                  }
                                }
       });
```

to my ajax result to make the new input work with emojionearea.

But if the result is appending to my page it takes some seconds to add, that is not a good user experience.

It take about 5 seconds.

If I remove the code up from my ajax result, The appending takes about 2 seconds.

IT's the code up that makes appending take too much time.

How to reduce that time ?

Do you understand me ?

**Comment by BoumBam** [comment]
In that code:

``` 

<div class="row">
  <div class="span6">
    <div class="emojionearea1">Support autocompleting, insert ":" </div>
  </div>
</div>

$(".emojionearea1").emojioneArea({
    pickerPosition: "right",
    tonesStyle: "bullet",
    events: {
      keyup: function() {
        console.log('keyup1');
      }
    }
});
```

I want to append after ajax request, another content with class="emojionearea1" and make it works with emojionearea: 

Another content like that:
```
<div class="row">
  <div class="span6">
    <div class="emojionearea1"> ANOTHER autocompleting, insert ":" </div>
  </div>
</div>
```

Have you understood ?
How to do that ?

**Comment by carpii** [comment]
If you are append more divs with `class="emojionearea1"` and then call `$(".emojionearea1").emojiOneArea(`  

You are actually calling the constructor on every single EmojiOneArea with that class. 
This will break the ones you already created

Instead generate a unique id for each one you create, such as `id="emojionearea345"`, and then call `$("#emojionearea345").emojiOneArea(` instead

**Comment by BoumBam** [comment]
@carpii 
**Instead generate a unique id for each one you create, such as id="emojionearea345", and then call $("#emojionearea345").emojiOneArea( instead**

I have tried that(It works fine) but if i'm appending the new content to my page it takes 5 seconds to append to my page.

It's a very bad user expericence and  want to reduce that delay.

**Comment by BoumBam** [comment]
I see but don't know why my content is taking time to append.

**Comment by carpii** [comment]
Ok, but my example shows its not an issue with EmojiOneAea

You need to just debug your ajax handler code and find out where the delay really is.

**Comment by BoumBam** [comment]
if I remove $("..............").emojioneArea({ part, the appending delay will be reduce to 2 seconds.
I think the problem is with  $("..............").emojioneArea({ part.

Thanks but I'm always looking for the solution.

**Comment by mervick** [comment]
Sorry, I can't understand your problem. The only way to help you is to create example at jsfiddle.
I am sure this issue does not related to emojionearea, check your code

**Comment by mervick** [comment]
Try to use `$("#id")` instead of `$(".class")`, maybe it's you problem.

**Comment by carpii** [comment]
Also use Chrome Developer Tools, where you can use the Performance tab to see what is actually taking the time. 

It sounds like you are including the time for the ajax network round-trip, in those 2 seconds
