### ISSUE TITLE
Jquery ".on" doesn't work with emojionearea

### ISSUE THREAD

**Issue by sanmiguel2019** [mervick/emojionearea#365]
Does anyone know how do I define
`var $inputMessage`
in the example below to work with emojionearea? It's working fine when I disable emojionearea, but with emojionearea nothing.

```
var $inputMessage = $('#msginput'); 

$inputMessage.on('input', function() { 
updateTyping();
});
```

**Comment by mervick** [comment]
Have you tried reading README?

ref https://github.com/mervick/emojionearea#methods
ref https://github.com/mervick/emojionearea#keyup

```js
var $inputMessage = $('#msginput'); 

$inputMessage.emojioneArea({
  events: {
    keyup: function() {
      console.log(this.getText());
      // updateTyping();
    }
  }
});
```

Example: https://jsfiddle.net/mervick/audv6xpb/1/

**Comment by sanmiguel2019** [comment]
Thank you for your reply.

Can you deomonstrate it with my case, how can I call function updateTyping()?

```
$inputMessage.on('input', function() { 
updateTyping();
});
```

**Comment by mervick** [comment]
```js
$inputMessage.emojioneArea({
  events: {
    keyup: function() {
      updateTyping();
    }
  }
});
```

**Comment by sanmiguel2019** [comment]
Unfortunately, it does not work

**Comment by mervick** [comment]
Yes, it works

**Comment by sanmiguel2019** [comment]
It does not work.

```
function updateTyping () {
if (!typing) {
typing = true;
socket.emit('typing');
}
lastTypingTime = (new Date()).getTime();

setTimeout(function () {
var typingTimer = (new Date()).getTime();
var timeDiff = typingTimer - lastTypingTime;
if (timeDiff >= TYPING_TIMER_LENGTH && typing) {
socket.emit('stop typing');
typing = false;
}
}, TYPING_TIMER_LENGTH);

}
```

And could you tell why emojionearea loads so slow, especially in mobile phones.
This version:
https://mervick.github.io/emojionearea/
works fine
but
this
https://github.com/mervick/emojionearea
is really slow. Takes some 2 seconds to appear emiji chooser in text area.

**Comment by sanmiguel2019** [comment]
Yes, it works, thanks and sorry.

**Comment by mervick** [comment]
Emojioneare works
example https://jsfiddle.net/mervick/audv6xpb/4/
