### ISSUE TITLE
Emojionearea not functioning properly when input is from mobile (e.g. android).

### ISSUE THREAD

**Issue by Antvanr** [mervick/emojionearea#367]
When a user enters text into an emojionearea from a mobile (android/chrome as an example), the user has to manually capitalize the first letter of every sentence.

**Comment by mervick** [comment]
There is attribute `autocapitalize` and it's `off` by default.
You can change it to 
- `on` or `sentences`: The first letter of each sentence defaults to a capital letter; all other letters default to lowercase
- `words`: The first letter of each word defaults to a capital letter; all other letters default to lowercase
- `characters`: All letters should default to uppercase

Example:
```js
$("#emojionearea").emojioneArea({
  attributes: {
    autocapitalize: 'on'
  }
});
```

https://github.com/mervick/emojionearea#attributes
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize
