### ISSUE TITLE
Setting the carat/cursor position

### ISSUE THREAD

**Issue by glui2001** [mervick/emojionearea#37]
I'd like a way to programmatically set the carat/cursor position in the content editable field.

**Comment by inkeytech** [comment]
Hello glui2001,

It has been a while since your comment.

Did you ever find a workaround for this?

Regards,

Ian

**Comment by carpii** [comment]
Theres a few solutions here
https://stackoverflow.com/questions/6249095/how-to-set-caretcursor-position-in-contenteditable-element-div

And a jsfiddle from deep within that page... https://jsfiddle.net/nrx9yvw9/5/
You'd need to adapt this code I guess, to treat the emojione images as a character

**Comment by inkeytech** [comment]
Hello carpii,

Thank you very much for the prompt response.

I'll check it out.

Ian

**Comment by mmccallum** [comment]
I'll just leave this here for those that need it.  It's a function that I wrote a bit a go and use a lot in my current project.

```
function gotoEnd(element: any) {
    var range, selection;
    element.focus();
    range = document.createRange();//Create a range (a range is a like the selection but invisible)
    range.selectNodeContents(element);//Select the entire contents of the element with the range
    range.collapse(false);//collapse the range to the end point. false means collapse to end rather than the start
    selection = window.getSelection();//get the selection object (allows you to change selection)
    selection.removeAllRanges();//remove any selections already made
    selection.addRange(range);//make the range you have just created the visible selection
}
```
