### ISSUE TITLE
emojionearea.min.map failed - No such file or directory

### ISSUE THREAD

**Issue by sanmiguel2019** [mervick/emojionearea#372]
I just checked my server's error logs and appear this:

`open() "/XXX/emojionearea.min.map" failed (2: No such file or directory)`

I searched emojionearea files and tis file name appears at the bottom of emojionearea.min.js file but it's commented with 2 slashes //
`//# sourceMappingURL=emojionearea.min.map`

Why I get this error in server's logfiles?

**Comment by carpii** [comment]
Are you definitely including emojionearea.min.js, rather than emojionearea.js

**Comment by mervick** [comment]
If you need map fils just use `emojionearea.js` instead of `emojionearea.min.js` while development proccess
