### ISSUE TITLE
Script errors with emoji load attempts

### ISSUE THREAD

**Issue by Emeritvs** [mervick/emojionearea#378]
When trying to implement the plugin in a textarea of ​​my site, I encounter the following issues:

![image](https://user-images.githubusercontent.com/43259638/65796622-7bf19880-e143-11e9-8934-2d445e68ab73.png)

![image](https://user-images.githubusercontent.com/43259638/65796693-a6dbec80-e143-11e9-933e-a243694613c0.png)

- When starting the emojioneArea () function, the console is repeatedly displaying this GET error, apparently trying to fetch the CDN emoji with a link from my site (??) and returning the error.

**Comment by mervick** [comment]
Try to clear you local storage:
In Chome: open developer tools (<kbd>ctrl + shift + I</kbd>), click Application -> Storage -> Local Storage -> [check your url] -> on the right panel check key `recent_emojis` and click `Delete Selected`

![Selection_268](https://user-images.githubusercontent.com/2429298/65796373-18805e80-e175-11e9-85be-5a21be243940.png)

**Comment by Emeritvs** [comment]
> Try to clear you local storage:
> In Chome: open developer tools (ctrl + shift + I), click Application -> Storage -> Local Storage -> [check your url] -> on the right panel check key `recent_emojis` and click `Delete Selected`
> 
> ![Selection_268](https://user-images.githubusercontent.com/2429298/65796373-18805e80-e175-11e9-85be-5a21be243940.png)


The GET loops in Chrome has stopped, but there is still 1 GET error on the console, but thank you for your patience and consideration.
