### ISSUE TITLE
Get only emojis from the textarea

### ISSUE THREAD

**Issue by Emeritvs** [mervick/emojionearea#379]
I'm making a web chat linked with WhatsApp, but when I write a message and use the emojis, I receive the HTML tags too (see the image).

How can I get the emojis inside the "alt=" attribute (like in the image below) and remove the rest of received string?

Example of texts and emojis messages with HTML code: 

![image](https://user-images.githubusercontent.com/43259638/65891454-ec362f00-e37a-11e9-9a5c-023bbb3341b4.png)

**Comment by pascalf22** [comment]
Hello !!!
Did you found the solution ?
