### ISSUE TITLE
Key press 

### ISSUE THREAD

**Issue by jpsilveira13** [mervick/emojionearea#382]
There are times when the keypress sends the value and there are times when not.

![image](https://user-images.githubusercontent.com/11342982/66273246-8d742800-e848-11e9-9ea6-bc0eb95c1903.png)

![image](https://user-images.githubusercontent.com/11342982/66273250-995fea00-e848-11e9-9b2f-19675fb5853e.png)

![image](https://user-images.githubusercontent.com/11342982/66273255-ab418d00-e848-11e9-933e-5fbc60f1d8f3.png)

Do you know what may be that there are times that send the value of the text and there are times when not?

**Comment by mervick** [comment]
EmojioneArea changes the input, after that it call internal events, but it does not call global event `keypress`.
You should listen EmojioneArea internal events.

ref https://github.com/mervick/emojionearea#methods
ref https://github.com/mervick/emojionearea#keyup

```js
var $input = $('#input'); 

$input.emojioneArea({
  events: {
    keyup: function() {
      console.log(this.getText());
    }
  }
});
```
Example: https://jsfiddle.net/mervick/audv6xpb/1/
