### ISSUE TITLE
EmojioneArea have trouble with passive event plug-in.

### ISSUE THREAD

**Issue by BoumBam** [mervick/emojionearea#383]
Hello,
before I add a default-passive-events plugin https://github.com/zzarcon/default-passive-events emojionearea worked well but after adding that default-passive-events plug-in to my project, emojionearea stopped working fine.

The problem is if I want to add an Emoji to the emojionearea-editor, the emoji is added at the start of the emojionearea-editor, the emoji is not adding at the current position of the cursor but at the start of emojionearea-editor.

How could I solve that problem ?
Link here: https://jsfiddle.net/L03jmfo2/
Thanks.

**Comment by mervick** [comment]
> before I add a default-passive-events plugin https://github.com/zzarcon/default-passive-events emojione worked well but after adding that default-passive-events plug-in to my project, emojione stopped working fine.

Do you have a problem with emojione or emojioneArea ?

**Comment by mervick** [comment]
If you want help please create example with issue at jsfiddle

**Comment by BoumBam** [comment]
I updated my issue.
I have problem with emojioneArea.
Is It compatible with a default-passive-events plug-in ?

**Comment by mervick** [comment]
If you want help please create example with issue at jsfiddle
