### ISSUE TITLE
getRecent() assumes localStorage 

### ISSUE THREAD

**Issue by MerlinBB** [mervick/emojionearea#39]
This causes an error on browsers that don't support local storage...

```
define([], function() {
   return function () {
        return localStorage.getItem("recent_emojis") || "";
    }
});
```

I think the following should work but haven't had time to test
```
define([], function() {
   return function () {
        return (window.localStorage) ? localStorage.getItem("recent_emojis") : "";
    }
});
```

Can make a PR later if you want?

**Comment by klaslundberg** [comment]
I think it also needs to return an empty string if recent_emojis is not set.
```
define([], function() {
   return function () {
        return window.localStorage ? localStorage.getItem("recent_emojis") || "" : "";
    }
});
```

**Comment by MerlinBB** [comment]
Yep your right :) Already added - https://github.com/mervick/emojionearea/pull/40/files#diff-96bc2fb01941113079e9877c27ef2451R6
