### ISSUE TITLE
Stay with the original ID

### ISSUE THREAD

**Issue by DanielDanielDanielD** [mervick/emojionearea#390]
Hi and thanks for the library, it is excellent :)

I have a question I haven't found a solution yet, how to save the original ID that exists for input even after the input has been changed by applying emojionearea on the ID of input?

So let say this is my input:-
`<textarea id="text" />`

And insted of getting it:-
`<div class="emojionearea-editor">`

I need to get this:-
`<div class="emojionearea-editor" id="text">`

**Comment by mervick** [comment]
`<textarea>` does not going anywhere, it stay at the same place but hidden, by html rules one html page can't have 2 elements with same `id`.

You can do that by little trick, but after that you will not have access to get emojioneArea instance using `id` like `$("#text")`

```js
var id = 'text';
var textarea = $('#' + id);
var emojionearea = textarea.data("emojioneArea");
var editor = textarea.next(".emojionearea-editor");
textarea.removeAttr('id');
editor.attr('id', id);
```
