### ISSUE TITLE
NPM is installing a previous version 3.4.1 => 3.4.0

### ISSUE THREAD

**Issue by sergiohampel** [mervick/emojionearea#396]
Hello,

I'm trying to install the version 3.4.1. `npm i emojionearea@3.4.1`. But the version actually installed is 3.4.0.

You can just click here https://registry.npmjs.org/emojionearea/-/emojionearea-3.4.1.tgz

The version installed from this link is 3.4.0.

Does anyone know why? or How could I fix it?

Thanks in advance.

**Comment by mervick** [comment]
hmm, very strange.
Fixed by publishing a new 3.4.2 version to npm

**Comment by sergiohampel** [comment]
> hmm, very strange.
> Fixed by publishing a new 3.4.2 version to npm

Thank you!!!
