### ISSUE TITLE
Change placeholder

### ISSUE THREAD

**Issue by neto737** [mervick/emojionearea#400]
Is there any way to change the placeholder? I've tried to change using jQuery but it doesn't update the 
input placeholder.

`$('#inputTxt').attr('placeholder', 'Type your message...');`

Any way to do this? I need to change the placeholder when some actions are made, and I don't know how to do that with emojionearea :(

**Comment by carpii** [comment]
`$("#inputTxt").data("emojioneArea").editor.attr("placeholder", "TEST");`
