### ISSUE TITLE
Error when uploading to MySQL using Laravel?

### ISSUE THREAD

**Issue by vgavrilovikj** [mervick/emojionearea#406]
I get the following error when I try to save it in my database: 
`SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x98\x87\xF0\x9F...' for column `challenges`.`challenges`.`description` at row 1 (SQL: insert into `challenges` (`hashtag`, `title`, `description`, `challenge_id`, `image_name`, `category_id`, `duration`, `link`, `user_id`, `updated_at`, `created_at`) values (emojitest, Emoji Test, This is an emjoit test 😇😇, 5edaaeb0a0c24, challenge-55edaaeb0a0c481591389872.png, 2, 0, ?, 5ec443a71e40b, 2020-06-05 20:44:32, 2020-06-05 20:44:32))`

**Comment by NishantTadvi** [comment]
try to make your Collation as utf8mb4_unicode_ic for description field or for whole database. i also work in laravel and this been working fine

**Comment by vgavrilovikj** [comment]
Thank you! It works now :)
    On Monday, June 8, 2020, 12:56:33 PM GMT+2, NishantTadvi <notifications@github.com> wrote:  
 
 


try to make your Collation as utf8mb4_unicode_ic for description field or for whole database. i also work in laravel and this been working fine
