### ISSUE TITLE
EmojioneArea textarea doesn't save to database in HTML

### ISSUE THREAD

**Issue by bathorus** [mervick/emojionearea#42]
Hello,

It's an awesome work. But I have an issue that need to be fixed fast.
Whatever I try to submit and save the text in textarea using emojionearea to database, it doesn't save properly in HTML and it cause the emoji become '?????????' question marks in database. Also other HTML tags like bold tag and other else also doesn't work.

For note, I use laravel PHP for my development. Do you have any solution? Thanks in advance.

**Comment by mervick** [comment]
Hi, 

1) Emojionearea saves only plain text (secure), for save emojis in html `img` tag you can use option `saveEmojisAs:true`

>the emoji become '?????????' question marks in database

2) in database you must use `utf8` or `utf8mb4` encoding

**Comment by bathorus** [comment]
Hello Mervick,

Thanks, I have converted my database to utf8_bin and change my input type to text but It still showing the same problem. Could you please explain what is plain text?

Thanks in advance. :+1:

**Comment by mervick** [comment]
Plain text !== html, it's just a text, to protect against [html injection](https://www.google.com.ua/search?q=html+injection)

**Comment by bathorus** [comment]
So I used this code for my input
`<textarea id="emojioneTextarea" name="body"></textarea>`
at the `head` I added
```
<!-- EmojiOne -->
<link rel="stylesheet" href="//cdn.jsdelivr.net/emojione/2.2.6/assets/css/emojione.min.css">
<!-- EmojiOneArea -->
<link rel="stylesheet" href="file/path/emojiOneArea/dist/emojionearea.min.css">
```
at the bottom of `body` I added
```
<!-- EmojiOne -->
<script src="//cdn.jsdelivr.net/emojione/2.2.6/lib/js/emojione.min.js"></script>
<!-- EmojiOneArea -->
<script src="{{ asset('assets/plugins/emojiOneArea/dist/emojionearea.min.js') }}"></script>
<script type="text/javascript">
        $(document).ready(function() {
            $('#emojiTextarea').emojioneArea({
                saveEmojisAs: true
            });
        });
</script>
```
emojioneArea works good in frontend
![image](https://cloud.githubusercontent.com/assets/13181901/17268609/28fd46a6-5659-11e6-86e6-2f99dd56fc85.png)

However it just won't save to proper html tag like the first and second data in this table below.
![image](https://cloud.githubusercontent.com/assets/13181901/17268571/fdd97086-5657-11e6-8137-5c17bd03d3d0.png)

I've also changed the database format as you suggested
![image](https://cloud.githubusercontent.com/assets/13181901/17268581/4a046a6a-5658-11e6-9f32-9386a7a5b145.png)

I don't understand how I would make it to plaintext in HTML. I'm sorry for bothering you about this kind of question.

It's still showing the same problem. Could you please give me the solution for this? Thanks so much in advance.

**Comment by mervick** [comment]
Hi @bathorus,

**in frontend:**
```js
  $(document).ready(function() {
       $('#emojioneTextarea').emojioneArea({
            saveEmojisAs: "shortname"
       });
   });
```

**in backend:**

first for all, install [emojione php lib](https://github.com/Ranks/emojione),
prefer installation via composer `composer require emojione/emojione`

next, in your php for rendering html from db
```php
<?php

use Emojione\Emojione;
use Emojione\Client as EmojioneClient;

// your code 

$emojioneClient = new EmojioneClient();
$emojioneClient->cacheBustParam = '';
$emojioneClient->imagePathPNG = 'https://cdnjs.cloudflare.com/ajax/libs/emojione/2.1.4/assets/png/';
Emojione::setClient($emojioneClient);

$body = htmlspecialchars($field_from_db);
$body = Emojione::shortnameToImage($body);
$body = nl2br($body);

echo $body;
```

**Comment by bathorus** [comment]
Hello @mervick!

Thank you so much, it works! It finally showing up the emojis! Is it anyway compatible with bootstrap wysihtml5? Or how do I add `bold`, `italic`, `underline`, `image`, etc?

**Comment by mervick** [comment]
Unfortunately, no

**Comment by bathorus** [comment]
Thanks @mervick!!

You're awesome!! :smile: :smile: :smile:

**Comment by raredudex** [comment]
Hello mervick,
I just wana appreciate you for what you doing for the community.
Please i am having the same issue with Bathorus. 
But in my own case i am using only PHP OOP and mysqli. 
My emojionearea frontend is working, but when you make a post the emojionearea icon will not appear on the posted comment.
Please pardon me i have not used any PHP framework before and i have not used PDO before.
Please assist me.
Thanks and stay blessed.
