### ISSUE TITLE
keypress not working

### ISSUE THREAD

**Issue by Pok4** [mervick/emojionearea#445]
hello guys, im using version 3.1.8 and i do this:

```
   var emojionestrip = $('textarea[name=com_text]').emojioneArea();
 
  var eventHandler1 = function(button, event) {
    console.log('event1');
  }
  emojionestrip[0].emojioneArea.on('paste', eventHandler1);
```

its working correctly, but when change 'paste' to 'keypress' on last line, the code not works.. 
Why keypress event didn't work ?

PS: jquery version is 3.2.1

**Comment by Pok4** [comment]
I see other topics, but can you give me best alternative to this date.

**Comment by mervick** [comment]
There is a bug with "keypress" event (https://github.com/mervick/emojionearea/issues/30),  
try to use "keyup", or attach "keypress" directly to input, e.g.
```js
$("textarea[name=com_text]").emojioneArea({
    events: {
    	ready: function() {
      	this.editor.on("keypress", function(event) {
            console.log("press", event);
        })
      }
    }
});
```
example: https://jsfiddle.net/mervick/79wLzvdm/

**Comment by Pok4** [comment]
Thank you, guys :)
