### ISSUE TITLE
I am unable to load the resources.

### ISSUE THREAD

**Issue by arjun-iihglobal** [mervick/emojionearea#459]
![image](https://github.com/mervick/emojionearea/assets/168441022/9cdb9817-5297-4ccf-91a0-d8d053c829f2)

This issue is in the mac safari browser.

**Comment by mervick** [comment]
Hello. 

The .map files are source map files that are primarily used during the development phase to help developers debug their code more effectively. They map the minified code to the original source code, making it easier to trace errors and understand the code structure.

In production environments, these .map files are usually not needed and are often excluded to enhance performance and security. If you encounter issues with .map files not opening, it should not affect the functionality of your application in a production setting.

If you need the full source code for debugging purposes, you can use the non-minified JavaScript files, which are not dependent on the .map files. This will allow you to debug the original code directly.
