### ISSUE TITLE
Show emoji inside html paragraph

### ISSUE THREAD

**Issue by martinobordin** [mervick/emojionearea#48]
The plugin is working great when attached to textbox.
However when I try to show the previous saved content in a paragraph, not all icons are showing.

Do you know what's the issue?

![image](https://cloud.githubusercontent.com/assets/1763288/17835951/54a76d24-6782-11e6-9dc3-819531fd9b7d.png)

**Comment by mervick** [comment]
Hi, for that you must use Emojione lib
please read this comment https://github.com/mervick/emojionearea/issues/42#issuecomment-236349667

**Comment by martinobordin** [comment]
Thanks
