### ISSUE TITLE
Use Sprite instead of individual png files

### ISSUE THREAD

**Issue by SaadeMotion** [mervick/emojionearea#50]
Hi!

I want to know, how can i use an sprite instead of individual png files.

I already tried to use 
"useSprite : true"
and
"emojione.sprites : true"

but seems not working.

Yes... i already included the emojione.sprites.css file in my project .. not working;

**Comment by mervick** [comment]
Hi @SaadeMotion,

Currently, option `useSprite` is no longer available (since [emojione v2.1.2](https://github.com/Ranks/emojione/releases/tag/v2.1.2)) cause in new versions of chrome was some bug with css `background-size`

**Comment by SaadeMotion** [comment]
Oh! Thanks to explain!

;)
