### ISSUE TITLE
Pasting not working

### ISSUE THREAD

**Issue by renebrain** [mervick/emojionearea#51]
I don't have a particular Use Case for this, but sometimes when my application starts something goes wrong with the editor. Typing and adding of emojis works, but pasting is not working at all. Even a rightclick on the contenteditable is not showing me the copy/cut menu options. Is it a contenteditable problem or a emojionearea problem? Any ideas?

**Comment by mervick** [comment]
Browser? OS?

**Comment by renebrain** [comment]
OS: Windows/Linux, Browser: Firefox. It seems like something dies during intialization or something like that but keeps the textarea functionally alive except for that part. that's how i initialize it:

```javascript 
var emojionearea = chatWindow.find("textarea").emojioneArea({
    pickerPosition: "top",
    filtersPosition: "bottom",
    tones: false,
    autocomplete: false,
    hidePickerOnBlur: true
});`

**Comment by mervick** [comment]
Hm, I just tried on Firefox 47.0 on Ubuntu 16.04 - it's works fine.

**Comment by mervick** [comment]
Can you try paste something on [this page](https://jsfiddle.net/1v03Lqnu/12/) with opened firefox's developer js console. 
Are there any errors in the console?

**Comment by renebrain** [comment]
We use Firefox 48.0.2 and same Linux and Windows 10. The problem with this issue is that it happens unpredictably on 1 of 10 cases. But when it happens it is annoying. Firebug and the console is not throwing any errors on paste or anything. I am keeping an eye on it right now. If i get it recreated i will show you some screenshots.

**Comment by mervick** [comment]
>  Even a rightclick on the contenteditable is not showing me the copy/cut menu options. 

It is your OS problems 
![peek 2016-09-02 13-04](https://cloud.githubusercontent.com/assets/2429298/18200565/07bb8668-710e-11e6-8217-8773db3e2262.gif)

**Comment by renebrain** [comment]
Let me recreate it and i will show it to you, should've done it in the first place

**Comment by renebrain** [comment]
The first image shows that i don't get any pasting or copy options in the context menu aswell as the keyboard functions for those actions are not getting triggered.
![pasting not working](https://cloud.githubusercontent.com/assets/9963399/18303382/28494866-74dd-11e6-8c97-ac235468052a.png)

In the second image i have the regular options and get the possibility to copy or paste
![pasting working](https://cloud.githubusercontent.com/assets/9963399/18303383/287fe8c6-74dd-11e6-8fe2-6d788a2030ff.png)

As said previous, i don't know what the cause for this is because i don't get any errors thrown from the application. This behaviour happens rarely, but it is not related to any OS because it happens across all of them. It might be an FF issue though, because i haven't tested it that far with other browsers. Is it maybe a problem with contenteditables?

**Comment by mervick** [comment]
It happend at [this page](https://jsfiddle.net/1v03Lqnu/12/) ?

**Comment by renebrain** [comment]
No, in my application it happened. We are using it for our own chat with the consctructor that i posted a few days ago. Sometimes when the application loads, the textarea plugin doesn't let us copy anything into it but accepts typing and addition of emojis. I don't have anything to grab on, because i don't have any more error informations provided by the browser. All i can say it happens directly after starting the webapp. Afterwards creating new textareas doesn't solve the problem. It happens for every instance. They are still not excecuting any paste/copy operations. We are not manipulating the textarea itself, so i don't think that anything from our side is triggering this behaviour.

**Comment by renebrain** [comment]
This issue is from our side confirmed fixed with the newer releases of emojionearea. You can close this issue.
