### ISSUE TITLE
IE Paste

### ISSUE THREAD

**Issue by oasiz** [mervick/emojionearea#52]
Hi,

When pasting into editor area, Unicode character 'INVISIBLE SEPARATOR' is prefixed to the string and shows as a dotted square: 

![image](https://cloud.githubusercontent.com/assets/2811813/18249457/42d72c42-7376-11e6-8bf8-9a9429797497.png)

Offending character is: http://www.fileformat.info/info/unicode/char/2063/index.htm

Tested on IE11, Microsoft Edge.

**Comment by oasiz** [comment]
Just an update (if it's any use to you), I've temporarily fixed this by using the following jQuery code:

```
$(".emojionearea-editor").on('paste', function() {
       $(this).html( $(this).html().replace(/[\u2063]/g, "") );
});
```

**Comment by mervick** [comment]
@oasiz symbol `\u2063` used for saving caret position, it should be invisible, but f*cking IE does everything that he wants

**Comment by mervick** [comment]
I do not have access to IE, please open developer panel and tell me maybe IE uses wrapper for this symbol (IE is unpredictable)

**Comment by oasiz** [comment]
Ah, I didn't know it was in the source!

In that case, a fix for this is to switch &#8291; for &#8203;

&#8203; is a(nother) zero width / hidden character that is actually hidden in IE (also tested on Chrome) and works the same for saving the caret position.

**Comment by mervick** [comment]
Please update your version to master and try it

**Comment by mervick** [comment]
Tell me if it's work or not
