### ISSUE TITLE
Fetching entire emoji library on initialisation 

### ISSUE THREAD

**Issue by MerlinBB** [mervick/emojionearea#55]
I think this was introduced somewhere between v3.0.4 and v3.1.4 test case here: https://jsfiddle.net/mjwxefqd/

If you check the network requests there's 1600+ request for pngs which seems to be delaying page loading process somewhat, Does the option for a sprite sheet still exist or is there a way to delay this load until it's needed?

**Comment by oasiz** [comment]
Hi @MerlinBB 

I think this thread will answer your query: https://github.com/Ranks/emojione/issues/243

I was wondering the same, hopefully a workable fix can be made for this issue.

**Comment by mervick** [comment]
Unfortunately no, in Emojione [v2.1.2](https://github.com/Ranks/emojione/releases/tag/v2.1.2) was removed support for scalable png sprites,
so you currently can't use `sprite` option

**Comment by MerlinBB** [comment]
Thanks for the info guys, will keep an eye on that issue in the emojione repo.

**Comment by mervick** [comment]
fixed
