### ISSUE TITLE
Lazy load emojis

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [mervick/emojionearea#57]
How to make the most fast download for images? 
I hoped to use SVG-sprites with gzip-compression, but seems like it's not possible any more...

**Comment by Vasiliy-Bondarenko** [comment]
with 1600 images download textarea initialisation takes a lot of time. 
is there any way to improve it?

**Comment by mervick** [comment]
Sprite support removed in https://github.com/Ranks/emojione/releases/tag/v2.1.2 , because latest version of Chome has bugs with rendering scaled background images

**Comment by mervick** [comment]
ref https://github.com/mervick/emojionearea/issues/19

**Comment by mervick** [comment]
Besides a plugin does not load all the images at initialization, emojis loaded while scrolling picker (lazy load)

**Comment by Vasiliy-Bondarenko** [comment]
i've read it. 
you mean there is no way to improve performance? on slow computers it takes up to 20 seconds to initialise textarea.

i don't see lazy load. i see complete 1600 load on init. and UI freeze. (one page app). 

may be i'm dooing something wrong? :)

**Comment by mervick** [comment]
Sorry, you are right, seems "lazy load" was broken

**Comment by mervick** [comment]
Fixed in [v3.1.5](https://github.com/mervick/emojionearea/releases/tag/v3.1.5)

**Comment by Vasiliy-Bondarenko** [comment]
Thank you. It's a lot better now! :)
