### ISSUE TITLE
Function submit / return

### ISSUE THREAD

**Issue by The-ZZ-Top** [mervick/emojionearea#6]
Hello Andrey,

nice work can you help me?
I need submit a feature to the content with the return key.
This can make an impression here is a demo:
http: // demo.like-friends.de

I would like to include in the comments, they will be sent with return.

Thanks for help
Regards, Frank

**Comment by mervick** [comment]
Hi, update your EmojioneArea to [v2.0.3](https://github.com/mervick/emojionearea/releases/tag/v2.0.3) and try this
```js
$(document).ready(function() {
  $("selector").emojioneArea({
    events: {
      keypress: function(editor, event) {
        if (event.which == 13) {
//          $('#form').submit();
          console.log("submit");
          event.preventDefault();
          return false;
        }
      }
    }
  });
});
```

**Comment by The-ZZ-Top** [comment]
so sorry, its not a form.

This is my Problem:
 
      <div class="post-footer post-comments" id="post-comments-<?php echo $wo['story']['id']; ?>">
        <div class="post-commet-textarea dropdown">
          <input id="inputText" class="form-control comment-textarea textarea"  placeholder="<?php echo $wo['lang']['write_comment'];?>" type="text" onkeyup="Wo_RegisterComment(this.value,<?php echo $wo['story']['id']; ?>,<?php echo $wo['story']['publisher']['user_id']; ?>, event, <?php echo (!empty($wo['story']['publisher']['page_id'])) ? $wo['story']['publisher']['page_id'] : '0'; ?>)" dir="auto">
        </div>
     </div>

Regards, Frank

**Comment by mervick** [comment]
I guess something like this:
```js
$(document).ready(function() {
    $("#inputText").emojioneArea({
        events: {
            keyup: function(editor, event) {
                Wo_RegisterComment(this.getText(), // or editor.html()
                    <?php echo $wo['story']['id']; ?>,
                    <?php echo $wo['story']['publisher']['user_id']; ?>,
                    event,
                    <?php echo (!empty($wo['story']['publisher']['page_id'])) ? 
                        $wo['story']['publisher']['page_id'] : '0'; ?>);
            }
        }
    });
});
```

**Comment by The-ZZ-Top** [comment]
It works...
Thank you have made me happy.

Regards, Frank

**Comment by The-ZZ-Top** [comment]
Hello Andrey,
can you help me again?

if I send in the first post he shows always the last to post.
Value is not correctly transmitted.

Example:
Post 1
<input class="form-control comment-textarea textarea ui-autocomplete-input" id="comment_text" style="display: none;" dir="auto" onkeyup="Wo_RegisterComment(this.value,53,1, event, 0)" type="text" placeholder="Schreibe einen Kommentar und drücke Enter" autocomplete="off">

Post 2
<input class="form-control comment-textarea textarea ui-autocomplete-input" id="comment_text" style="display: none;" dir="auto" onkeyup="Wo_RegisterComment(this.value,59,1, event, 0)" type="text" placeholder="Schreibe einen Kommentar und drücke Enter" autocomplete="off">

Post 3
<input class="form-control comment-textarea textarea ui-autocomplete-input" id="comment_text" style="display: none;" dir="auto" onkeyup="Wo_RegisterComment(this.value,ANYTHINK NUMBER,1, event, 0)" type="text" placeholder="Schreibe einen Kommentar und drücke Enter" autocomplete="off">

I want to install in a script something like Facebook is so with comment functions.

**Comment by PaulDesigns** [comment]
How to make it display in a comment? I either have non styled ones or it just posts the code for them

**Comment by mervick** [comment]
You must use [emojione](https://github.com/Ranks/emojione#php-conversion)

**Comment by PaulDesigns** [comment]
Oh, just the PHP conversion right?

**Comment by mervick** [comment]
No, javascript also https://github.com/Ranks/emojione#javascript-conversion
