### ISSUE TITLE
Can not submit form with event keypress

### ISSUE THREAD

**Issue by vanlong2712** [mervick/emojionearea#62]
I cant submit a form when pressing enter in textarea. It only works when I click to somewhere, then click to the textarea and press enter.
My form

```
<form id="add-msg-form">
        <div class="panel-footer">
            <div class="input-group" style="display: -webkit-box" id="txtbox">
                <textarea id="txtMessage" placeholder="Vui lòng nhập nội dung tin nhắn" ></textarea>
                <span class="input-group-btn">
                    <button class="btn btn-info" id="btnSend" type="submit">Send</button>
                </span>
           </div>
    </div>
</form>
```

```
$(document).ready(function() {
    $("#txtMessage").emojioneArea({
        events: {
            keypress: function (editor, event) {
                if(event.which == 13){
                    console.log('event:keypress'); //work
                        $('#add-msg-form').submit(); //not work
                                        $('#txtMessage').val(''); //not work
                                }
            },
        }
    });
});
```

**Comment by mervick** [comment]
seems submit works well https://jsfiddle.net/1v03Lqnu/114/

**Comment by vanlong2712** [comment]
thank you. but another problem that it increases row in the textarea instead of returning back .
and how can I show the color emoji after fetching from database ? My emoji after fetching looks like that 😂😍

**Comment by mervick** [comment]
>  increases row in the textarea instead of returning back

use `event.preventDefault()` for that https://jsfiddle.net/1v03Lqnu/131/
> how can I show the color emoji after fetching from database

use emojione for convert ASCII to images, see https://github.com/mervick/emojionearea/issues/42#issuecomment-236349667

**Comment by vanlong2712** [comment]
is it Ok ? I use nodejs

**Comment by mervick** [comment]
for nodejs emojione has client too

**Comment by mervick** [comment]
you can even convert unicode on client side

**Comment by vanlong2712** [comment]
Thank you. 
Have u had any demo about that? or just a link for me to research

**Comment by mervick** [comment]
https://github.com/Ranks/emojione

**Comment by vanlong2712** [comment]
Thank you very much

**Comment by vanlong2712** [comment]
sorry. one more question. how can I resize the emoji equal to size of emoji in textarea ?

**Comment by Fabiombrs** [comment]
@mervick 
How to use this code instead of textarea use the input? https://jsfiddle.net/1v03Lqnu/131/

**Comment by mervick** [comment]
@Fabiombrs 
Just replace `textarea` with `input`,
https://jsfiddle.net/1v03Lqnu/2341/

**Comment by Fabiombrs** [comment]
@mervick Thank you very much I'm a beginner and I'm having difficulty using the code. I'm trying to use it in a chat, but it does not work.
==========================================

                <div class="box-footer">
                 
                    <form class="input-group" id="form" onsubmit="AlteraConteudo()" >
                     <input class="form-control" type="text" maxlength="10" id="mensagem" name="mensagem" placeholder="Digite...">
                     

                    <input id="id_user" name="id_user" type="hidden" value="<?php echo $id; ?>">
                    <div class="input-group-btn">
                      <button class="btn btn-success" onclick="AlteraConteudo()"><i class="fa fa-plus"></i></button>
                      
                   </div>
                    </form>
                </div>
================================================================

// Função que faz as requisição Ajax ao arquivo PHP
function AlteraConteudo()
{
 var ajax = AjaxF();

 ajax.onreadystatechange = function(){
  if(ajax.readyState == 4)
  {
   document.getElementById('conteudo').innerHTML = ajax.responseText;
  }
 }
 // Variável com os dados que serão enviados ao PHP
 var dados = "mensagem="+document.getElementById('mensagem').value;

 ajax.open("GET", "retorna_informacoes.php?"+dados, false);
 ajax.setRequestHeader("Content-Type", "text/html");
 ajax.send();
document.getElementById('mensagem').value = "";
var minhadiv = document.getElementById("conteudo");
minhadiv.scrollTop = minhadiv.scrollHeight;

}
==============================================================

require("../inc/db_conecta.php");
			//mysql_set_charset('latin1');
    			//session_start();
	//

				$id_user_enviou = $_SESSION['user'];
				$sql = ("SELECT * FROM block WHERE id_user = '$id_user_enviou' LIMIT 1");
				$query = mysqli_query($conecta,$sql);                   
                $block = mysqli_num_rows($query);
				if($block != 1)
				{
				if (!empty($_GET['mensagem']))
				{
				$mensagem = utf8_encode($_GET['mensagem']);
				$sqlinsert = "INSERT INTO chat (iduser, data_hora, mensagem) VALUES ('$id_user_enviou', NOW(), '$mensagem')";
				$inserenome = mysqli_query($conecta,$sqlinsert);
				}
				}
					// finalmente, cria a tabela 
				//						
    				$sql = ("SELECT * FROM chat where status = 1 ORDER BY data_hora ASC LIMIT 10000");
					$query = mysqli_query($conecta,$sql);                   
                    while($dados_chat = mysqli_fetch_array($query)) {
                    $iduser = $dados_chat['iduser'];
                    $sql_user = ("SELECT * FROM usuarios WHERE id = $iduser");
                    $consulta_user = mysqli_query($conecta,$sql_user);
                    $dados_user = mysqli_fetch_assoc($consulta_user);
                    ?>
                    <div class="item">
					<?php if(!empty($dados_user['id_facebook']))
					{
					?>
					<img src="http://graph.facebook.com/<?php echo $dados_user['id_facebook']; ?>/picture?width=128&height=128" alt="user image" class="online">
					<?php } if(!empty($dados_user['imagem'])) {?>
					
					 <img src="../img/user/<?php echo $dados_user['imagem']; ?>" alt="user image" class="online">
						<?php } if(empty($dados_user['id_facebook']) && empty($dados_user['imagem']))
						{
								if($dados_user['sexo'] == "F")
								{
								?>
						 <img src="../img/user/mulher_sem_imagem.jpg" alt="user image" class="online">
						 
							<?php }
							if($dados_user['sexo'] == "M")
								{
								?>
								 <img src="../img/user/homem_sem_imagem.jpg" alt="user image" class="online">
						<?php }
						} ?>
                    <p class="message">
                      <a href="perfil/?id=<?php echo $dados_user['id']; ?>" class="name">
                        <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> <?php echo date('H:i', strtotime($dados_chat['data_hora'])); ?></small>
                        <?php echo $dados_user['nome']; ?>
                      </a>
                      <?php echo utf8_decode($dados_chat['mensagem']); ?>
                    </p> 
                      </div>
                      		<?php }  ?>
                      
                      		</div>
                      	<br>
                 </body>
                 </html>
my project hotspot.acessewififree.com.br

thank you

**Comment by Fabiombrs** [comment]
@mervick 
help!

**Comment by lasdeparq** [comment]
@Fabiombrs, what is not work? You need to be more specific.

**Comment by Fabiombrs** [comment]
@mervick 
@lasdeparq 
Thanks for the feedback, when I type the text and press enter my function "alteraconteudo" does not receive the information entered in the input. I changed the code "document.getElementById ('message'). Value" to "document.getElementById ('form'). Value". There the bank writes as undefinid.

**Comment by mervick** [comment]
@Fabiombrs Please create your example here https://jsfiddle.net/1v03Lqnu/2341/

**Comment by Fabiombrs** [comment]
@mervick 
@lasdeparq 

I tried to play as you requested https://jsfiddle.net/1v03Lqnu/2663/
I need to press enter to execute the function AlteraConteudo(), thanks for the help.

**Comment by mervick** [comment]
@Fabiombrs 
https://jsfiddle.net/1v03Lqnu/2673/

**Comment by Fabiombrs** [comment]
@mervick 
@lasdeparq 
Working perfectly in my code. Thank you very much, I hope that when you learn more you can reciprocate in some way.

**Comment by djamel2288** [comment]
![emoji](https://user-images.githubusercontent.com/46092857/56984900-70477900-6b87-11e9-96fc-0229c6a89ff1.png)
![emoji_sent](https://user-images.githubusercontent.com/46092857/56984903-70477900-6b87-11e9-96d9-6d534670b7d9.png)
![emoji_sent_mozilla](https://user-images.githubusercontent.com/46092857/56984904-70477900-6b87-11e9-87e5-f2223889d241.png)

**Comment by mervick** [comment]
@djamel2288 
see here https://github.com/mervick/emojionearea/issues/42#issuecomment-236349667
