### ISSUE TITLE
Height of editor changes as soon as something is typed

### ISSUE THREAD

**Issue by shubhamt619** [mervick/emojionearea#67]
Hi there andrey ! ! !
Hello again .

Your work helped me a lot.

I am writing this to let u know a possible  bug.

It may not be  a bug but it can be some sort of css code overriding etc.

Before typing anything into editor , editor looks like this 

![image](https://cloud.githubusercontent.com/assets/12027792/19741486/7cc5abe6-9bde-11e6-98be-92c1a5f11088.png)

After Focus it looks like 

![image](https://cloud.githubusercontent.com/assets/12027792/19741517/9b8f42f8-9bde-11e6-9e99-2ba50ed6218b.png)

After typing , it suudenly resizes to 21px  😞 

like this

![image](https://cloud.githubusercontent.com/assets/12027792/19741584/d663032e-9bde-11e6-86af-171ff35c10d2.png)

I am using jquery 3.1.0 , materializecss. . . .Please help me out bro ! ! ! ! 

Thank you

**Comment by mervick** [comment]
Hi, Shubham.

It's very strange, 
I doubt that I can help you remotely without access to your code, 
try to recreate this bug on jsfiddle https://jsfiddle.net/1v03Lqnu/12/ ,
when you do that, save jsfiddle and share with me, 
I will try to help you

**Comment by shubhamt619** [comment]
Hey bro ! ! !
The issue has been resolved. . .the issue was that i had a textarea of class="materialize-textarea". . . .the problem was being caused by it. . .

As soon as i removed the code of class="materialize-textarea" , the issue was gone ! ! !


Thanks a lot for your continuous support and hardwork bro.

❤️
