### ISSUE TITLE
how can i decode the :smile: to relevant emojione ? ? 

### ISSUE THREAD

**Issue by shubhamt619** [mervick/emojionearea#68]
Hi there Andrey , 

as i told u , i am making a chatting system.

I am able to send smiley's through your awesome plugin , could u please guide me how can i convert them back to emoji's ? ? 

What i am saying is that i am able to fo this    😄 -> :smile: 

i want to do this :smile: - > 😄 

![image](https://cloud.githubusercontent.com/assets/12027792/19755973/20c53fe2-9c37-11e6-82e2-e9c8b1527669.png)

Here's an image for you to understand better. . .Thank you

**Comment by mervick** [comment]
Hi,
You can use [emojione](https://github.com/Ranks/emojione) for converting emojis back,
something like
```js
$("p").each(function() {
    var $p = $(this);
    $p.html(emojione.shortnameToImage($p.html()));
});
```

**Comment by shubhamt619** [comment]
Yayyyyy! !
Thanks....it works now



Thank you
