### ISSUE TITLE
EmojiOne in COdeigniter

### ISSUE THREAD

**Issue by shubhamt619** [mervick/emojionearea#69]
Okay , Maybe i am asking at wrong place , nut by any chance , is anyone here good at Codeigniter 

http://git.emojione.com/demos/latest/phptoimage.php <- Visit this URL

I want to make the toImage( ) in CI.

Please help as early as possible

**Comment by mervick** [comment]
I think something like this https://github.com/mervick/emojionearea/issues/42#issuecomment-236349667

**Comment by shubhamt619** [comment]
I solved it guys ! ! ! 


Now i am able to use emojionearea in Codeigniter without any issues ! ! !
![untitled](https://cloud.githubusercontent.com/assets/12027792/19768209/29ec3192-9c74-11e6-94db-187dc30185b4.png)

**Comment by M-Husein** [comment]
Hi, how to implement in codeigniter?
Please give me guide & explain

Thanks

**Comment by shubhamt619** [comment]
Hii bro...
For using it in codeigniter. ...
First implement it in plain codeigniter page using emojione docs.


Now for decoding....use smiley helper

Whatsapp me at 7721889463 if u want v more help

**Comment by M-Husein** [comment]
Hi, @shubhamt619 

Thanks for fast respon :+1: 

I will add your whatsapp contact.

**Comment by M-Husein** [comment]
Hi, @shubhamt619 

What your prefix country code phone?

I have add your whatsapp number, but in my contact you don't have whatsapp account?

I don't have chat with people from other country, sorry for that :)

**Comment by shubhamt619** [comment]
+91 7721889463
