### ISSUE TITLE
Set emojione version in parameteres

### ISSUE THREAD

**Issue by joelcuevas** [mervick/emojionearea#7]
How about doing emojioneVersion configurable on init?

Currently it's hardcoded in emojionearea/js/emojionearea.js@56:

```
var emojioneVersion = '1.5.2';
```

I downgraded from 2.0.1 to 1.5.2 in order to have a consistent look between all the icons, but it would be cool to use any emojione version, even if, at the moment, the newer icons on the sprite are still not supported.

**Comment by mervick** [comment]
Fixed, now you can set `window.emojioneVersion="2.0.1;"` before call `emojioneArea`

**Comment by mervick** [comment]
Sorry, it can't be set in options, emojione loaded before

**Comment by joelcuevas** [comment]
Great! This will do the work. Thank you!
