### ISSUE TITLE
Ready event

### ISSUE THREAD

**Issue by piercebDev** [mervick/emojionearea#70]
Hi, on page load how do you autofocus on the input div (.emojionearea-editor), i have tried jQuery's .focus() but no worky :(

**Comment by mervick** [comment]
This will work if you load [emojione](https://github.com/Ranks/emojione) on your page in `<script/>` tag (emojionearea loads it dynamicly)
```js
$(document).ready(function() {
    $("#elem").emojioneArea();
    $("#elem").data("emojioneArea").editor.focus();
});

**Comment by piercebDev** [comment]
Hi Mervick, thanks so much, worked a charm... great work :)
