### ISSUE TITLE
Change design of emojionearea

### ISSUE THREAD

**Issue by Rubioli** [mervick/emojionearea#73]
Great package.

In my application I use `V. 2.1.4` and for opening the emojis I need to click on emoji icon.

*This is how I have it now:*
![skjermbilde 2016-10-31 kl 12 16 09](https://cloud.githubusercontent.com/assets/16593596/19852578/78c69e86-9f64-11e6-90ae-d2b72402d0b5.png)

Is it possible to make it so emojis are always open and can't be closed/removed. Like the picture below and emojis parts `width` is `100%`
![skjermbilde 2016-10-31 kl 12 31 48](https://cloud.githubusercontent.com/assets/16593596/19852858/19016c90-9f66-11e6-8bbe-be0b3827cf40.png)

Thanks in advanced!

**Comment by JWaldenback** [comment]
You can use v 2.1.1 for this purpose: http://mervick.github.io/emojionearea/

I'm not sure what the difference between version 2 and 3 is apart from CSS though. Maybe version 3 suits your needs better anyway.

**Comment by Rubioli** [comment]
Thanks. It did not helped :/
