### ISSUE TITLE
Support latest Emoji One version

### ISSUE THREAD

**Issue by sergkush** [mervick/emojionearea#74]
Emoji One 2.2.6 already released, but emojionearea supports versions up to 2.1.4. Sad ( Thanks>

**Comment by allanbrault** [comment]
@mervick any idea on when this will come ? the current version is 2.2.7

**Comment by AmirHosseinKarimi** [comment]
Hi, I am looking for emojionearea update to support emojione v2.2.7.
I try to add emojione newest version to emojionearea but tired to do this!

**Comment by stof** [comment]
Support for 2.2.7 was added in #89. This issue should be closed
