### ISSUE TITLE
Add onLoad event

### ISSUE THREAD

**Issue by sergkush** [mervick/emojionearea#78]
Because of racing conditions, editor element isn't always has emojioneArea data attr.

I've hot fixed this issue in my copy of the code by changing

editor.data(source.data());

to 

editor.data(source.data());
editor.data('emojioneArea', self);

hope this helps.

**Comment by brunomachado** [comment]
Same here. Thanks for the fix.

**Comment by carpii** [comment]
Did this ever make it into master, or is this workaround still required?

**Comment by mervick** [comment]
> Did this ever make it into master, or is this workaround still required?

The fix above is completely wrong.

EmojioneArea add `emojioneArea` data attr after loading `emojione` assets,
so if you run your code in `$(document).ready()` then `emojioneArea` still not ready and you need wait until `emojione` lib will load.
In new version of emojioneArea planned to add new event which will be trigger when `emojioneArea` will be ready.

For fix this you can use something like:
```js
$("#emojionearea").emojioneArea();
var ready = function(next) {
  var timer = setInterval(function() {
    if ($("#emojionearea").is(":hidden")) {
      clearInterval(timer);
      next();
    }
  }, 200);
};

ready(function() {
   // add your buttons to emojionearea here
});
```

p.s. PR are welcome

**Comment by carpii** [comment]
Thanks @mervick 

I'm having an issue in Firefox where emojionearea has the keyboard focus, but typing into it does not result in characters being added.
I thought maybe it was related the data() not being set properly, but I guess it's not
