### ISSUE TITLE
Autocomplete emoji

### ISSUE THREAD

**Issue by kamov** [mervick/emojionearea#8]
Hi,
First of all, congratulations for this awesome plugin, keep up good work.
I would like to integrate this example: http://git.emojione.com/demos/2.1.2/autocomplete.html
but doesn't work..
I would like to allow users to use also autocomplete.
I hope that you can show an example.
Autocomplete is great, but most important is to autoconvert shortcodes ( for example :heart: ) to correct images. At the moment if you add icon via mobile, this seem not converted.  
Thanks!

**Comment by mervick** [comment]
Hi, Thanks.
This is a really good idea.
I will keep this in mind.

**Comment by kamov** [comment]
Great, thank you!

**Comment by MerlinBB** [comment]
👍

**Comment by mervick** [comment]
Fixed in `^v3.0.0`
