### ISSUE TITLE
How do i get icon images?

### ISSUE THREAD

**Issue by rsmmukesh** [mervick/emojionearea#80]
how i can get those icon images? as far as i can see it is displaying it from a cdn. i want to load those images from my own website path. from where i can get those images and how to configure the new path?

**Comment by mervick** [comment]
you can get it from https://github.com/Ranks/emojione,
modify it as you want, after that you need add it on the same page where you use emojionearea,
```html
<script src="path/to/js/emojione.js"></script>
<link rel="stylesheet" href="path/to/assets/css/emojione.css"/>
```
and it must use your version

**Comment by rsmmukesh** [comment]
Thank you

**Comment by rsmmukesh** [comment]
Hi.. even i refer to <script src="path/to/js/emojione.js"></script>. now also the images are taking from cdn. what i need is i need to show everything from my site not from cdn.

**Comment by rsmmukesh** [comment]
can you help me? is it possible or not?

**Comment by mervick** [comment]
please look at these lines [emojione.js#L150-L1510](https://github.com/Ranks/emojione/blob/master/lib/js/emojione.js#L150-L1510), and you can see that `emojione` by default use cdn, so you can change it as you like, just like this:
```js
jQuery(document).ready(function() {
    emojione.imagePathPNG = 'wherever/you/want/assets/png/';
    emojione.imagePathSVG = 'wherever/you/want/assets/svg/';
});
```
Hope this helps

**Comment by rsmmukesh** [comment]
Hi,
   that is in emojione.js , in the emojionearea.js i found the code 

  var cdn = { 
        defaultBase: "https://cdnjs.cloudflare.com/ajax/libs/emojione/",
        base: null,
        isLoading: false
    };

This is the code to set the cdn icons for the emojionearea. is there any possibility to change it without modifying the js ?

**Comment by mervick** [comment]
You don't need to do this, since when you use external `emojione.js` this code will not execute

**Comment by rsmmukesh** [comment]
Hi,
   please check the below link. even i refer to emojione.js the emoji image path is not fetching from emojione.js. it is always getting cdn from emojionarea.js.

http://www.w3schools.com/code/tryit.asp?filename=FAX89UW1L7MO

**Comment by rsmmukesh** [comment]
did you see it?

**Comment by mervick** [comment]
I will fix this as soon as I have free time

**Comment by greenled** [comment]
@rsmmukesh try also passing a configuration object with ```useInternalCDN: false```, like this:
```javascript
jQuery(document).ready(function() {
    emojione.imagePathPNG = 'wherever/you/want/assets/png/';
    emojione.imagePathSVG = 'wherever/you/want/assets/svg/';
    $("#example1").emojioneArea(
        {
            useInternalCDN: false
        }
    );
});
```
This way it will use emojione's defined locations. It works for me with v3.1.5. Look at the source code for more config options.
