### ISSUE TITLE
use textarea or input rather than div contenteditable

### ISSUE THREAD

**Issue by toinouu** [mervick/emojionearea#81]
Hi
I would like to know if it was possible to not  hide the source and replace contenteditable by this source (textarea or input).

I would just use the picker and keep textarea or input element

Currently I am doing this

        var triggerChange = function(){
            self.trigger('change', self.editor);
        }

       var $form = $('#form'),
            $body = $('#input'),
            $submit = $form.find("[type='submit']")  ;

        var source = $body.emojioneArea({
            sprite            : false,
            hideSource        : false, 
            saveEmojisAs:     "shortname",
            autocomplete      : false,
            events: {
                keyup: function (editor, event) {
                    triggerChange();
                },
                emojibtn_click: function (button, event) {
                    triggerChange();
                },
            }
        });

        var self = source.data('emojioneArea');

`

**Comment by mervick** [comment]
Currently not, only with conteneditable
