### ISSUE TITLE
hopw to dynamically access emojionarea?

### ISSUE THREAD

**Issue by rsmmukesh** [mervick/emojionearea#82]
i have trying to develop a chat application. the textareas will come dinamically. to apply emojionarea i have used like below example 
$("#"+id).emojioneArea(...options....);
it is working fine. but i cant able to access the emojioneArea dinamically. i want to get data from the emojioneArea when the user press the enter key. how i can get it?

**Comment by carpii** [comment]
````
var emojionearea = $("#"+id).data("emojioneArea");
emojionearea.showPicker();
````
