### ISSUE TITLE
Can't access shortname values

### ISSUE THREAD

**Issue by activestylus** [mervick/emojionearea#83]
I have set up my textarea with `shortnames: true`, but when I try to get the editor value in a `keyup` callback, it returns HTML. Trying it out with `editor.text()` Just ignores the image. I also notice that my textarea which is attached to this instance has no change in its value.

How do I access the shortname text to store in the database?

My attempt (using v3.0): https://jsfiddle.net/1v03Lqnu/181/

**Comment by mervick** [comment]
Use for that `saveEmojisAs: 'shortname'`, 
ref [getDefaultOptions.js#L27](https://github.com/mervick/emojionearea/blob/master/src/var/getDefaultOptions.js#L27)

After that you can get it by `$("textarea#emoji").data("emojioneArea").getText()`
example https://jsfiddle.net/1v03Lqnu/202/
