### ISSUE TITLE
getText() removes line breaks from text

### ISSUE THREAD

**Issue by akudryav** [mervick/emojionearea#85]
When I use 
`$('#message').data("emojioneArea").getText()`
it returns text without line breaks. How could I avoid this?

**Comment by mervick** [comment]
It happens, because in some cases this functions works not correctly,
[textFromHtml](https://github.com/mervick/emojionearea/blob/master/src/function/textFromHtml.js)
[htmlFromText](https://github.com/mervick/emojionearea/blob/master/src/function/htmlFromText.js)

**Comment by dowrow** [comment]
This should be marked as critical bug and not as enhancement. This makes this lib practically unusable.

**Comment by webexperto** [comment]
I know where make the changes, but I don't know exactly what to change.
How do we solve it?

**Comment by mervick** [comment]
duplicate of https://github.com/mervick/emojionearea/issues/34
