### ISSUE TITLE
How to get the UNICODE equivalent of the emoji for database storage

### ISSUE THREAD

**Issue by EricNjue** [mervick/emojionearea#88]
How can i get the text equivalent of the emoji instead of 😄 for db storage.

**Comment by EricNjue** [comment]
And how can it be achieved using AJAX. Say using Ajax.Beginform for asp.net mvc5

**Comment by EricNjue** [comment]
The documentation says "The end result is a secure text/plain in which the image icons will be replaced with their Unicode analogues." but on my end am getting the images instead of unicode analogues

**Comment by mervick** [comment]
See #48, #42
