### ISSUE TITLE
Show emoji on div container no text area needed

### ISSUE THREAD

**Issue by ydaniels** [mervick/emojionearea#95]
Is it possible to use emojionarea without textarea

**Comment by mervick** [comment]
yes, it possible,
you can use `<input type="text"/>` or even `<div/>`
example https://jsfiddle.net/1v03Lqnu/201/

**Comment by ydaniels** [comment]
Oh sorry the question was a bit misleading. am saying for example if you use a `<div />` tag it turns the div to an input area. I am trying to display the emoji without input. Just like the way  our comment is being displayed after you submit it. I think emojionearea should support parsing of text in a div or p tag. It should convert any emoji characters found  to the appropriate image representing the characters. Thanks

**Comment by mervick** [comment]
You can do this without emojionearea, but using [emojione](https://github.com/Ranks/emojione).
I don't think what you can use CKEditor or TinyMCE or somethingelse just for display content, editors designed for edit.
