### ISSUE TITLE
Change the display to one emoji

### ISSUE THREAD

**Issue by glombers** [mervick/emojionearea#96]
how to change the display to one emoji
http://image.prntscr.com/image/8e14a2e321a6482889e4abb4a118b458.png
On my website displaying the old and would like these new

**Comment by collimarco** [comment]
I have the same problem. 
Some single emoji (e.g. emoji with multiple people) are displayed as multiple emoji when I use the text outside the textarea.

**Comment by mervick** [comment]
See #48, #42

**Comment by collimarco** [comment]
@mervick I can't use the solution given in the linked issues because the text **must** be converted to UTF-8 in order to be displayed as content in web push notifications.
