### ISSUE TITLE
[Suggestion] To make API manually to show area dialog

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [mervick/emojionearea#98]
I use TinyMCE editor, and i need to integrate Emojiarea inside, but there is no way to show Emojiarea  dialog myself.
Mabe to make function to bind any button to make popup on it of Emojiarea?
Plus manual opening and positioning dialog.

**Comment by ohenepee** [comment]
Any progress on this? @mervick

**Comment by mervick** [comment]
There are 2 methods for this:
- `showPicker` - show picker (dialog area)
- `hidePicker` - hide picker (dialog area)
Example: https://jsfiddle.net/mervick/1v03Lqnu/3655/

```js
$("#emojionearea1").emojioneArea();
$("#show_picker").on("click", function() {
    $("#emojionearea1").data("emojioneArea").showPicker();
});
$("#hide_picker").on("click", function() {
    $("#emojionearea1").data("emojioneArea").hidePicker();
});
```
